### ISSUE TITLE
Publish latest version on npm 2.0.2

### ISSUE THREAD

**Issue by kimak** [expo/sentry-expo#100]
The latest version is 2.0.2 on master https://github.com/expo/sentry-expo/commit/e369ff5a3364ec45f0cec7383b8b78eb13324a33

But npm latest is 2.0.1:
https://www.npmjs.com/package/sentry-expo

Is it possible to npm publish the 2.0.2 ?

**Comment by cruzach** [comment]
latest is now 2.0.3
