### ISSUE TITLE
Add option to manually set release name associated with sourcemaps

### ISSUE THREAD

**Issue by vijayst** [expo/sentry-expo#106]
I am using Expo 36. revision id is not supported in the app manifest. It seems to be dynamically created as part of publish process. So, I am not able to associate source maps to a specific release.

**Comment by cruzach** [comment]
It's not clear what you mean by this issue- revisionId is supported, but not in development  as stated in the docs https://docs.expo.io/guides/using-sentry/

**Comment by vijayst** [comment]
If I set revisionId in app.json, I get this error while publishing:

> Error: Problem validating fields in app.json. See https://docs.expo.io/versions/v36.0.0/workflow/configuration/
>  • should NOT have additional property 'revisionId'.

**Comment by cruzach** [comment]
revisionId is not a settable attribute, it's performed automatically as part of the publish process as you said. But why does this mean you can't associated source maps to a specific release? Do you mean you want to be able to set the release to your `expo.version` value or something similar?

**Comment by vijayst** [comment]
Yes, the product team does not want a random revisionId but set to either version in app.json, or preferably version in Info.plist. Within the app, I can set the revisionId to the Info.plist easily but finding it difficult to associate the source map to the same release.

**Comment by jtomaszewski** [comment]
In our case, we prefer to have the release version being equal to our git repo commit reference. https://github.com/expo/sentry-expo/pull/111 makes this and our case possible.

**Comment by cruzach** [comment]
addressed in https://github.com/expo/sentry-expo/pull/118
