### ISSUE TITLE
Sentry is not sending global errors

### ISSUE THREAD

**Issue by sarcadass** [expo/sentry-expo#108]
This issue is similar to the original "Sentry is not sending global errors" (#23)

But the solution provided that closed the issue (https://github.com/expo/sentry-expo/issues/23#issuecomment-398666767) is now deprecated.
The solution provided is not suitable with React v16 and functional components using hooks, because `componentDidCatch` and `getDerivedStateFromError` are not available as hooks (https://en.reactjs.org/docs/hooks-faq.html#how-do-lifecycle-methods-correspond-to-hooks).
> `getSnapshotBeforeUpdate`, `componentDidCatch` and `getDerivedStateFromError`: There are no Hook equivalents for these methods yet, but they will be added soon.

Is there a way to report errors globally and not by calling explicitly `Sentry.captureException()`?

**Comment by filipepratalima** [comment]
also interested in this

**Comment by cruzach** [comment]
not sure what you mean, the following code reports an error for me in the sentry dashboard on iOS and Android. Please provide a reproducible demo

```

Sentry.init({
  dsn:
    "MY-DSN",
  enableInExpoDevelopment: true,
});

export default function App() {
  return (
    <View style={styles.container}>
      <Text style={styles.paragraph}>
        Change code in the editor and watch it change on your phone! Save to get
        a shareable url.
      </Text>
      <Button title="throw an error" onPress={throwMyError} />
    </View>
  );
}

function throwMyError() {
  let i = 0;
  let mynewvar = i.myobject.toString();
}
```

**Comment by GuyAvraham** [comment]
I had an issue as well. but solved it.
Here is a repo working example with examples of error from component and error from redux saga
https://github.com/GuyAvraham/sentry-expo-example

**Comment by cruzach** [comment]
I think this _might_ be the same issue that was fixed by https://github.com/expo/sentry-expo/commit/f1e32047a4482cd9ce904e039147da558483cc66 and https://github.com/expo/sentry-expo/commit/72ed3c1ab80e8c9d0ea73157a791018788eae042, so I'm going to close this issue for now. If you're still having trouble with this, please open a new issue with a reproducible demo
