### ISSUE TITLE
Critical Security - Upgrade @sentry/react-native to 1.3.9

### ISSUE THREAD

**Issue by celandro** [expo/sentry-expo#112]
I received an email just now:

> Last week we were notified of a security issue related to our React Native iOS SDK that could potentially lead to access to your source map in applications that use this iOS SDK. This vulnerability does not impact Android users.

> As a matter of best practice, Sentry strongly encourages you update your app to protect your source maps, updating your React Native SDK to 1.3.9.

> Update @sentry/react-native to 1.3.9, which you can find here: https://github.com/getsentry/sentry-react-native/releases/tag/1.3.9

**Comment by chrismin** [comment]
Our team would really appreciate this being handled asap!

**Comment by darrylyoung** [comment]
I just came here to write this. Thanks for already doing it, @celandro. 👍 

For anyone else interested, `sentry-expo` currently uses `"@sentry/react-native": "^1.0.0"`.

**Comment by mkveksas** [comment]
Thanks for filling out this issue, @celandro. 

It would be highly appreciated if the Expo team could follow up on this as soon as possible. Thanks!

**Comment by fractalmarc** [comment]
update on npm?

**Comment by rvieceli** [comment]
After update (from `2.0.0` to `2.0.4`) `expo install sentry-expo` I got this message:
`Sentry Logger [Log]: Failed to get device context from native: SentryError: Native Client is not available, can't start on native.`

**Comment by tevonsb** [comment]
I'm getting the same error as @rvieceli after upgrading from 2.0.1 to 2.0.4.

**Comment by jvivaspatternag** [comment]
Same error on a fresh installation. It breaks the app as it is instantiated.

**Comment by cruzach** [comment]
if you clear your `yarn.lock` file, this will be updated. `sentry-expo`v2.0.4 uses `"@sentry/react-native": "^1.0.0",` which will resolve up to version 1.9.9. That said, we've merged a PR that upgrades this to `^1.3.9`, and will publish a new version soon.

@rvieceli what does your sentry config look like? It's really helpful if you can provide a method to reproduce your error, rather than just the message. That probably belongs in a new issue

**Comment by rvieceli** [comment]
@cruzach Sorry for that, the config is the simple. but we're using npm (I will test deleting `package-lock.json`)

```js
  const config = {
    dsn: environment.sentryDsn,
    debug: true,
    environment: `${environment.environment}`
  }
```
and then
```js
Sentry.init(config)
```

**Comment by cruzach** [comment]
@rvieceli it looks like that's caused by Sentry's [Device context integration](https://develop.sentry.dev/sdk/event-payloads/contexts/), which is added by default (although it's not listed in their [default integrations](https://docs.sentry.io/platforms/javascript/#default-integrations)). This is not particular to `sentry-expo@2.0.4`, i tested 2.0.0 and the same occurs, so it's related to the version of sentry-react-native. Just committed a fix that will fix that issue

**Comment by andrewkryshtal** [comment]
```
"@sentry/react-native": {
            "version": "1.4.3",
},
```
with
```
"sentry-expo": {
            "version": "2.1.0",
},
```
still not working for me. Should i wait for further fix?

**Comment by cruzach** [comment]
what, exactly, isn't working?

**Comment by outaTiME** [comment]
@andrewkryshtal same here using the following version with Expo SDK36:

sentry-expo: ^2.1.1
@sentry/react-native: 1.4.4

**Comment by davidwadge** [comment]
Also having this issue.

**Comment by obviouscreations** [comment]
Same issue here

**Comment by cruzach** [comment]
if you use `@sentry/react-native@1.4.2`, this error won't occur. It looks like this may have been introduced in https://github.com/getsentry/sentry-react-native/pull/902

**Comment by cruzach** [comment]
just published `sentry-expo` v2.1.2 which comes with that version pinned ^ 

not that you'll need to remove `node_modules` and `yarn.lock` and then reinstall

**Comment by andrewkryshtal** [comment]
![image](https://user-images.githubusercontent.com/26659679/84147724-8dc36380-aa66-11ea-96e6-8da40ad8e555.png)
still have an on-start error after updating ```sentry-expo``` package, version of ```@sentry/react-native``` still 1.4.2. The fix is in a 1.4.5 version, isn't it?

**Comment by cruzach** [comment]
The issue was introduced in v1.4.3, now that it's fixed we can upgrade on the next release

@andrewkryshtal you'll need to remove `node_modules` and your lock file to update appropriately. If you still hit the issue, please create a new ticket including a minimal reproducible demo, thanks!

**Comment by special-character** [comment]
Just ran into this and I am using expo. I fixed it by updating `sentry-expo` to: `"sentry-expo": "^2.1.2",`.

**Comment by luizjr** [comment]
I have the last version and this appear for me:
Failed to get device context from native: SentryError: Native Client is not available, can't start on native.

**Comment by davidwadge** [comment]
Hi @luizjr. I had the same issue and had to do the clear cache dance to get it working:

`watchman watch-del-all && rm -rf node_modules/ && yarn cache clean && yarn install && yarn start -- --reset-cache`

**Comment by luizjr** [comment]
> Hi @luizjr. I had the same issue and had to do the clear cache dance to get it working:
> 
> `watchman watch-del-all && rm -rf node_modules/ && yarn cache clean && yarn install && yarn start -- --reset-cache`

I ran the commands you recommended to me, and it doesn't seem to have worked.
![image](https://user-images.githubusercontent.com/1474563/84240471-71f6a680-aad4-11ea-85e7-eb6b8b37ddf6.png)


![image](https://user-images.githubusercontent.com/1474563/84240421-5be8e600-aad4-11ea-9b72-3b2cce69ba1d.png)

Thanks for listening, if anyone else could help.

**Comment by davidwadge** [comment]
@luizjr I definitely had this error and resolved it somehow. The only other thing I did was reset the iPhone simulator (erase all data). Perhaps that will help?

**Comment by skidding** [comment]
FYI I just followed the guide at https://docs.expo.io/guides/using-sentry, installed latest `sentry-expo` (2.1.2) and am getting the same error:

> Sentry Logger [Log]: Failed to get device context from native: SentryError: Native Client is not available, can't start on native.

Reset caches, even though I had just installed sentry related packages, but to no avail.

Is there some linking required?

Would definitely appreciate if this was looked into.

**Comment by skidding** [comment]
Note that errors _do_ get reported to Sentry, even though the Sentry Logger error is printed on every `Sentry.captureException` call.

**Comment by luizjr** [comment]
> @luizjr I definitely had this error and resolved it somehow. The only other thing I did was reset the iPhone simulator (erase all data). Perhaps that will help?

I reinstalled the package, cleared caches, checked the version ... but so far, nothing has really solved that.

**Comment by xmflsct** [comment]
Same here. Reinstalled dependencies doesn't help. It happens after first app start.

**Comment by allandiego** [comment]
Got this same error after ejecting expo, using "sentry-expo": "^3.0.4". With managed workflow it was working fine.
