### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by bradbyte** [expo/sentry-expo#116]
@cruzach besides the basic cli command if blocks, can you think of anything else that should be covered by a test or that you are manually testing before a release?

Also, any preference on testing tools? I was thinking using Jest.

**Comment by bradbumbalough** [comment]
Are we able to tap into GitHub actions or another CI platform for running the tests?

**Comment by cruzach** [comment]
https://github.com/expo/sentry-expo/pull/128
