### ISSUE TITLE
`captureException` throws error when `enableInExpoDevelopment` is set to `false`

### ISSUE THREAD

**Issue by Mighty683** [expo/sentry-expo#125]
Like in topic:

`captureException` throws error when `enableInExpoDevelopment` is set to `false`. 

After documentation in such case this method should be no-op:
https://docs.expo.io/guides/using-sentry/

![image](https://user-images.githubusercontent.com/22498910/85263293-3f06c800-b46f-11ea-80ab-a84123ceb663.png)

**Comment by cruzach** [comment]
What version of `sentry-expo` are you using

**Comment by Mighty683** [comment]
Sorry I migrated out of expo this week but then we were using `^2.0.1`

**Comment by cruzach** [comment]
This was fixed in version 2.1.2, it was due to an upstream issue with Sentry
