### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by conroywhitney** [expo/sentry-expo#14]
First off, thank you for Expo, `create-react-native-app`, and this sentry integration!

I am receiving an exception `Uncaught TypeError: Cannot read property 'replace' of undefined` from `error.stack.replace` on [line 61 of index.js](https://github.com/expo/sentry-expo/blob/master/index.js#L61).

I followed the ["Using Sentry"](https://docs.expo.io/versions/latest/guides/using-sentry.html) docs and was able to add Sentry to my Expo project. However, I was not seeing any events on the Sentry dashboard, so a Sentry Support Engineer suggested that I add `Sentry.enableInExpoDevelopment = true;` before `Sentry.config();` in order to test the integration in development. I then added a `throw "TEST"` in a `render()` method of one of my components. The good news is that the exceptions are being sent to Sentry!

The bad news is, the exceptions being sent are all `Uncaught TypeError: Cannot read property 'replace' of undefined`, and all originate from this `sentry-expo` integration file.

Let me know if you think this is on my end, or if you don't support development mode, or something like that. Also, please let me know if I can provide any more information or help do anything to resolve this issue.

Thank you in advance!

**package.json**
```
"expo": "^19.0.0"
"react-native": "^0.46.1"
"sentry-expo": "^1.6.0"
```

**Comment by brentvatne** [comment]
sorry this is old now so i'm going to close. apologies we didn't investigate it for you back when it mattered
