### ISSUE TITLE
Should we upgrade to 3.0.0-rc3?

### ISSUE THREAD

**Issue by georgiosd** [expo/sentry-expo#140]
How stable is it? Breaking changes vs 2.x?

Thanks!

**Comment by cruzach** [comment]
it's fairly stable now, we'll be releasing as `latest` soon
You can see the changes here - https://github.com/expo/sentry-expo/blob/master/CHANGELOG.md#unpublished

**Comment by georgiosd** [comment]
Thank you @cruzach

**Comment by summerkiflain** [comment]
@cruzach please publish the latest version, we want to fix the YellowBox warning after migrating to expo sdk 39.

**Comment by cruzach** [comment]
just waiting on https://github.com/getsentry/sentry-react-native/pull/1084 to land and be released, then I can update the `react-native-sentry` version and publish 🙂

**Comment by bill-pairaktaridis** [comment]
@cruzach will we also able to track performance as well or is that farther down the line?

**Comment by c316** [comment]
@cruzach that pull request was merged yesterday. https://github.com/getsentry/sentry-react-native/pull/1084

**Comment by cruzach** [comment]
and it was released this morning! `sentry-expo@latest` (3.0.2) has the upgrade, please enjoy 😄 and thanks for the patience

**Comment by c316** [comment]
Before installing the latest version of this package I was getting, 

```Sentry Logger [Error]: SDK not enabled, will not send event.```

when I'd run Sentry.captureException(error) in development. 

Now I get an error that says, 

```
TypeError: Sentry.captureException is not a function. (In 'Sentry.captureException(new Error(error), {
      extra: errorInfo
})', 'Sentry.captureException' is undefined)
```

**Comment by cruzach** [comment]
please read the changelog for the breaking changes in v3- https://github.com/expo/sentry-expo/blob/master/CHANGELOG.md#-breaking-changes

**Comment by c316** [comment]
I just read that and I don't see how that should have change what I'm doing. I initialize in the App.js 
I'm using the managed workflow.
```
Sentry.init({
  dsn: 'https://dsninfohere',
  enableInExpoDevelopment: true,
});

```

file as per the docs. Then in the ErrorBoundary file I'm doing

```
componentDidCatch(error, errorInfo) {
    console.log('Error caught');
    Sentry.captureException(error, {
      extra: errorInfo,
    });
  }
```

Are you saying I need to stop importing like this

```
import * as Sentry from 'sentry-expo';
```

And start doing 

```
import { Native, Browser } from 'sentry-expo';
```

then initialize with

```
Native.init(...
```

**Comment by cruzach** [comment]
replace `Sentry.captureException` with `Sentry.Native.captureException`

or you can fiddle with imports to use it however you'd like, such as `import {Native as Sentry} from 'sentry-expo'`

**Comment by c316** [comment]
> replace `Sentry.captureException` with `Sentry.Native.captureException`
> 
> or you can fiddle with imports to use it however you'd like, such as `import {Native as Sentry} from 'sentry-expo'`

That worked, Thank you

**Comment by superKalo** [comment]
I updated to `"sentry-expo": "3.0.2"` and changed the imports (`import { Native as Sentry } from 'sentry-expo'`). However, I got the following error, and my build breaks:

```
Failed building JavaScript bundle.
While trying to resolve module `@sentry/react-native` from file `/Users/XXX-my-project-XXX/node_modules/sentry-expo/dist/sentry.expo.js`, the package `/Users/XXX-my-project-XXX/node_modules/@sentry/react-native/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/XXX-my-project-XXX/node_modules/@sentry/react-native/dist/js/index.js`. Indeed, none of these files exist:

  * /Users/XXX-my-project-XXX/node_modules/@sentry/react-native/dist/js/index.js(.native|.ios.expo.ts|.native.expo.ts|.expo.ts|.ios.expo.tsx|.native.expo.tsx|.expo.tsx|.ios.expo.js|.native.expo.js|.expo.js|.ios.expo.jsx|.native.expo.jsx|.expo.jsx|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.wasm|.native.wasm|.wasm)
  * /Users/XXX-my-project-XXX/node_modules/@sentry/react-native/dist/js/index.js/index(.native|.ios.expo.ts|.native.expo.ts|.expo.ts|.ios.expo.tsx|.native.expo.tsx|.expo.tsx|.ios.expo.js|.native.expo.js|.expo.js|.ios.expo.jsx|.native.expo.jsx|.expo.jsx|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.wasm|.native.wasm|.wasm)
```

Any ideas why this breaks?

PS: I tried to delete `node_modules`, `yarn install` and to clean Metro bundler cache (`expo r -c`), the same result.

**Comment by cruzach** [comment]
@superKalo that sounds like some sort of caching issue to me, maybe clear your yarn cache with `yarn cache clean` ?

**Comment by superKalo** [comment]
@cruzach thanks for helping out! No effect. I tried in this order: 1) deleting `node_modules`, 2) `yarn cache clean` , 3) `yarn install`, 4) `expo r -c`. Same error :(

PS: Yarn v1.22.4, if this is any relevant. `"expo": "39.0.3", "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz"`

**Comment by c316** [comment]
@superKalo 

Wherever you are importing sentry to initialize it you still need to use
import * as Sentry from 'sentry-expo';

Not sure if that has anything to do with this error, but I just wanted to say this in case it helps.

**Comment by superKalo** [comment]
No, switching to `import * as Sentry from 'sentry-expo'` did no effect. The same issue persists.

**Comment by superKalo** [comment]
@cruzach btw, I also tried on an another Mac. Same error.

I also tried alternatively to `import * as SentryLib from 'sentry-expo'` and then `const Sentry = SentryLib.Native;`. Same error persists :(

**Comment by superKalo** [comment]
@cruzach I found another error, coming from the Metro bundler now. I hope this is a clue:

```
Starting Metro Bundler.
Your JavaScript transform cache is empty, rebuilding (this may take a minute).
transform[stderr]: The exported identifier "Sentry" is not declared in Babel's scope tracker
transform[stderr]: as a JavaScript value binding, and "@babel/plugin-transform-typescript"
transform[stderr]: never encountered it as a TypeScript type declaration.
transform[stderr]: It will be treated as a JavaScript value.
transform[stderr]:
transform[stderr]: This problem is likely caused by another plugin injecting
transform[stderr]: "Sentry" without registering it in the scope tracker. If you are the author
transform[stderr]:  of that plugin, please use "scope.registerDeclaration(declarationPath)".
```

PS: I have only 1 sentry plugin in my package.json, `"sentry-expo": "3.0.2"`.

**Comment by superKalo** [comment]
@cruzach @c316 thanks for your help, I found the issue!

```
import * as SentryLib from 'sentry-expo';

SentryLib.init({
    // bla bla
});

const Sentry = SentryLib.Native;
export const captureException = (e: any) => Sentry.captureException(e);
```

So basically, when you init, you need to always do it against the default export.
