### ISSUE TITLE
sentry-expo should support ErrorBoundary

### ISSUE THREAD

**Issue by amber-pli** [expo/sentry-expo#141]
I tried the `ErrorBoundary` from @sentry/react. Refer to https://docs.sentry.io/platforms/javascript/guides/react/. It works, but since it uses `withScope` from `@sentry/browser`, errors sent by it miss expo related data such as `manifest`.

It would be great if `sentry-expo` provides the `ErrorBoundary` that capture all expo related data.

**Comment by cruzach** [comment]
`@sentry/react-native` (exposed from sentry-expo via `Sentry.Native.`) provides an ErrorBoundary, that might work better than using @sentry/browser's

**Comment by cruzach** [comment]
Closing since the above should work
