### ISSUE TITLE
Sentry Expo authToken best practice

### ISSUE THREAD

**Issue by AnishaChhatwani** [expo/sentry-expo#144]
Using these docs:
https://docs.expo.io/versions/latest/guides/using-sentry

We were told to add:
`"hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "your organization's short name here",
            "project": "your project name here",
            "authToken": "your auth token here"
          }
        }
      ]
    }`

However, I want to keep the “authToken” secret, and I was wondering what the best practice for managing this is?
Does it make sense to wish not to commit this token to the repo?
If so, what is the best way of injecting a token into app.json, either from a gitignored file or from an environment variable?

Also, could you better explain how the postPublish hook works when building a standalone app that will be submitted to the app stores? Do we need to publish to expo prior to building the apps, so that the source code publish happens? Or will building the app (exp build) also run the postPublish hook?

**Comment by cruzach** [comment]
To use environment variables in your app.json file, you should switch over to a dynamic app.config.js file instead- https://docs.expo.io/workflow/configuration/#dynamic-configuration-with-appconfigjs (then you can use ENV vars like you would in any js file).
That being said, you can leave out the `config.authToken` in favor of the `SENTRY_AUTH_TOKEN` env variable (we state this in the docs you linked)

>could you better explain how the postPublish hook works when building a standalone app that will be submitted to the app stores?

In the managed workflow, when you run `expo build:[ios | android]`, Expo publishes your app automatically for you so you don't need to worry about that. In the bare workflow, when you build your app, Sentry has a build step (gradle step on Android) that takes care of it for you
