### ISSUE TITLE
Sourcemaps of self-hosted bundles not resolved

### ISSUE THREAD

**Issue by peter-jozsa** [expo/sentry-expo#145]
Hey there,

We are trying to use Sentry in our self-hosted managed Expo app but unfortunately sourcemaps are not resolved when an issue is reported. We upload sourcemaps of the bundle in `postExport` hook like it is suggested in the docs, but Sentry does not use them.

The main reason for this is because hardcoded Expo CDN url is used to determine how frame filenames should be normalized. Since our app does not use the Expo CDN url the original frame filename is sent along the issue and Sentry won't find the uploaded sourcemaps.

We could easily workaround the issue by adding the `RewriteFrames` integration explicitly to the `Sentry.init` call, like:
```js
Sentry.init({
  dsn: SENTRY_DSN,
  enableInExpoDevelopment: true,
  integrations: [
    new RewriteFrames({
      iteratee: (frame) => {
        if (frame.filename) {
          frame.filename = `app:///main.${Platform.OS}.bundle`
        }
        return frame
      },
    }),
  ],
})
```

I think docs should mention how people should use this package when they don't use the Expo CDN to deploy their apps.

Hope I could help someone :)

**Comment by RodolfoGS** [comment]
I have the same issue with self-hosted, the only difference is that I'm using Bare workflow (no Managed).

**Comment by peter-jozsa** [comment]
Try the workaround I shared in my original issue description, it should work as is in bare workflow too.

**Comment by RodolfoGS** [comment]
I need to import `RewriteFrames` from somewhere, how can I do?
```
ReferenceError: Can't find variable: RewriteFrames
```

**Comment by RodolfoGS** [comment]
I fixed `Can't find variable: RewriteFrames` installing `@sentry/integrations`
```
import { RewriteFrames } from '@sentry/integrations';
```
---

I applied your workaround but doesn't work for me, sentry can't found the sourcemaps.
I'm using `sentry-expo: 3.0.0-rc3`, what version you have?

I also tested change the filename but doesn't work. I'm testing on iOS
```
frame.filename = `app:///main.jsbundle`
```

**Comment by RodolfoGS** [comment]
This also happen on non self-hosted updated https://github.com/expo/sentry-expo/issues/149

**Comment by cruzach** [comment]
hm yeah seems like we should use the same `RewriteFrames` whether or not the project is Expo hosted. 

what we're trying to match here is the bundle filename, which should be the same whether you `export` or `publish` :
`index.android.bundle.map` for android, and `main.jsbundle.map` for iOS

**Comment by cruzach** [comment]
@RodolfoGS i _believe_ this is unrelated to your issue in the bare workflow

**Comment by cruzach** [comment]
added docs for this here- https://github.com/expo/expo/commit/ded7182c86cc85736bc8452d1505fb139e24c496

**Comment by peter-jozsa** [comment]
sorry for not replying, I tested this only on iOS but I think it is also related to since the built-in RewriteFrames checks the CDN URL of expo which will never work for us who self-hosts their bundles.

**Comment by cruzach** [comment]
@peter-jozsa are you saying you can't overwrite the default RewriteFrames integration? You should be able to do that

**Comment by peter-jozsa** [comment]
No, everything is okay, our app works fine with the workaround I suggested in my original issue description. I just tried to reply to your earlier message 👍

Thanks for adding it to your docs!

> hm yeah seems like we should use the same `RewriteFrames` whether or not the project is Expo hosted.
> 
> what we're trying to match here is the bundle filename, which should be the same whether you `export` or `publish` :
> `index.android.bundle.map` for android, and `main.jsbundle.map` for iOS
> 
> @peter-jozsa is this on iOS, android, or both?
