### ISSUE TITLE
Failure to compile with v3 RC3 for web in managed workflow

### ISSUE THREAD

**Issue by guyzmo** [expo/sentry-expo#148]
I'm starting a project with expo, with web and native targets, and as I was adding sentry while testing in the browser, I had the following compilation failure:

```
.../project_root/node_modules/@sentry/react-native/dist/js/integrations/debugsymbolicator.js
Module not found: Can't resolve 'react-native/Libraries/Core/Devtools/parseErrorStack' in '.../project_root/node_modules/@sentry/react-native/dist/js/integrations'
```

preventing the project from launching. 😞 

Here's the code I used in App.tsx:

```
// react imports
import * as Sentry from 'sentry-expo';

export default function App() {
   Sentry.init({
     dsn: config.sentryDsn,
     enableInExpoDevelopment: true,
     debug: true,
   });
  return (
    // react tree
  )
}
```

it does not crash when running on an iOS mobile phone. So it's either my setup that's not correctly done or there's a bug 😉

I hope this helps with the release candidate

**Comment by cruzach** [comment]
web was broken on `@next`, sorry about that! should be fixed in the above PR, please try with `sentry-expo@3.0.2` 😄
