### ISSUE TITLE
Update `react-native-sentry` dep

### ISSUE THREAD

**Issue by alexrussell** [expo/sentry-expo#15]
`react-native-sentry` is currently at 0.26.0, whereas the version requested by this package's `package.json` file is `^0.14.0` (which basically means `>=0.14.0,<0.15.0` as it's a `0.` release). If that's on purpose (i.e. we need `0.14.*` and nothing else) then that's fair enough, but if not, it'd be great to update this dep.

My reason for this is that the 0.14 version includes a *lot* of repo cruft, and I had to download >670MiB of stuff that's not required as far as I can tell (see the `appium/aws/Build` directory). This is not in the current version of `react-native-sentry` so presumably was in by mistake in `0.14`, or is no longer required for whatever reason, it'd be great to get a later version that doesn't include it in the npm package.

---

Just to make it extra painful, I had to download this package while tethering to my phone as our internet connection had not yet been installed in the new office, so using >600MiB of my data allowance, and at painfully slow speeds due to my connection strength (in fact it was so slow it timed out a couple of times, so I dread to think how much network usage it actually ate up!) was killing me.

**Comment by JulianKingman** [comment]
Also, there are performance issues with Sentry < 0.15
https://github.com/getsentry/react-native-sentry/issues/158

**Comment by HazAT** [comment]
Hey, I've submitted a PR to update the dep
https://github.com/expo/sentry-expo/pull/17

**Comment by brentvatne** [comment]
done, sorry for the delay
