### ISSUE TITLE
Sentry.setRelease is not a function

### ISSUE THREAD

**Issue by 026binit** [expo/sentry-expo#152]
![image](https://user-images.githubusercontent.com/57526408/95963943-02991680-0e28-11eb-8b9e-7d91e3cbf3b0.png)

i have imported 
import * as Sentry from "sentry-expo";    in App.js

Sentry.init({
  dsn: Keys.sentryDns
});

Sentry.setRelease(Constants.manifest.revisionId);

expo sdk :- 39
"sentry-expo": "^3.0.2",
"expo-constants": "~9.2.0",
platform :- Android/IOS

**Comment by rvieceli** [comment]
@026binit try `Sentry.Native.setRelease(Constants.manifest.revisionId);`

Look breaking change in changelog.

**Comment by cruzach** [comment]
thanks @rvieceli 👍 

I believe `setRelease` was also deprecated in favor of passing `release: <my release here>` in your call to `.init()`
