### ISSUE TITLE
Sentry.Native.ErrorComponent no longer logging errors after ejecting

### ISSUE THREAD

**Issue by ianbayne** [expo/sentry-expo#158]
`App.js`:
```JavaScript
import * as Sentry from 'sentry-expo';

Sentry.init({
  dsn: DSN
  enableInExpoDevelopment: true,
  debug: true,
});

const FallbackComponent = ({ resetError }) => (
  <SafeAreaView>
    <Text>Sorry, something went wrong.</Text>
    <TouchableHighlight onPress={() => resetError()}>
      <Text>
        Click here to reset
      </Text>
    </TouchableHighlight>
  </SafeAreaView>
);

export default function App() {
  return (
    <Sentry.Native.ErrorBoundary
      fallback={({ resetError }) => (
        <FallbackComponent resetError={resetError} />
      )}
    >
       // ...
    </Sentry.Native.ErrorBoundary>
  )
}
```

`package.json`:
```
{
  "scripts": {
    "setup": "yarn install && npx pod-install",
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "lint": "./node_modules/.bin/eslint src"
  },
  "dependencies": {
    "@apollo/client": "^3.2.5",
    "@sentry/react-native": "^2.0.2",
    "expo": "~39.0.2",
    "expo-splash-screen": "~0.6.2",
    "expo-status-bar": "~1.0.2",
    "expo-updates": "~0.3.2",
    "graphql": "^15.4.0",
    "prop-types": "^15.7.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "~0.63.3",
    "react-native-exception-handler": "^2.10.9",
    "react-native-gesture-handler": "~1.7.0",
    "react-native-reanimated": "~1.13.0",
    "react-native-screens": "~2.10.1",
    "react-native-unimodules": "~0.11.0",
    "react-native-web": "~0.13.12",
    "sentry-expo": "^3.0.3"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-jest": "~25.2.6",
    "babel-loader": "^8.1.0",
    "detox": "^17.13.1",
    "eslint": "^7.13.0",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-react": "^7.21.5",
    "eslint-plugin-react-hooks": "^4.2.0",
    "jest": "^26.6.3",
    "jest-circus": "^26.6.3",
    "react-test-renderer": "~16.13.1"
  },
  "private": true,
  "name": "NAME",
  "version": "1.0.0"
}
```

Before ejecting to the bare workflow, the above setup correctly sent errors to Sentry. I followed the instructions [here](https://github.com/expo/sentry-expo#bare-workflow-setup) after ejecting, but having done so, Sentry no longer receives error messages. 

However, if I update `App.js` to use `@sentry/react-native` instead of `sentry-expo`, errors _are_ successfully sent to Sentry. Here is `App.js` after this change:

```JavaScript
import * as Sentry from '@sentry/react-native';

Sentry.init({
  dsn: DSN
  enableInExpoDevelopment: true,
  debug: true,
});

const FallbackComponent = ({ resetError }) => (
  <SafeAreaView>
    <Text>Sorry, something went wrong.</Text>
    <TouchableHighlight onPress={() => resetError()}>
      <Text>
        Click here to reset
      </Text>
    </TouchableHighlight>
  </SafeAreaView>
);

export default function App() {
  return (
    <Sentry.ErrorBoundary
      fallback={({ resetError }) => (
        <FallbackComponent resetError={resetError} />
      )}
    >
       // ...
    </Sentry.ErrorBoundary>
  )
}
```

Is there something that I'm doing obviously wrong? From my understanding, step 2 of the [Bare workflow setup](https://github.com/expo/sentry-expo#bare-workflow-setup) will generate an extra

```JavaScript
import * as Sentry from '@sentry/react-native';

Sentry.init({
  dsn: 'YOUR DSN',
});
```

in `App.js`, but these lines should be deleted, leaving the original `import * as Sentry from 'sentry-expo';` and `Sentry.init` and everything should "Just Work." Or am I misunderstanding something?

Thanks!

**Comment by cruzach** [comment]
hey @ianbayne , from the looks of it you're not doing anything wrong 🤔 

The only thing i can imagine is that the version of `@sentry/react-native` being used was different? now that `sentry-expo` uses the latest version, could you try again?

**Comment by ianbayne** [comment]
Thanks, @cruzach, but sadly that didn't do it ☹️

Are you able to reproduce the error yourself?

**Comment by cruzach** [comment]
No, I can't reproduce this myself (using the same code as you)

I have a button _inside_ of the error boundary with
```
<Button
            title="throw error "
            onPress={() => {
              throw new Error("oopsie!!");
            }}
          />
          
```

and tapping that i see the error in sentry.

You may want to double-check your dependency versions, here's mine when I run `yarn why sentry-expo` and `yarn why @sentry/react-native`:

```
=> Found "sentry-expo@3.0.4"
=> Found "@sentry/react-native@2.1.0"
```

**Comment by ianbayne** [comment]
Thanks, @cruzach.

Running the above gives me:

```
yarn why sentry-expo
=> Found "sentry-expo@3.0.4"

yarn why @sentry/react-native
=> Found "@sentry/react-native@2.1.0"
```

so that's apparently not the issue either...

**Comment by cruzach** [comment]
@ianbayne could you try with `sentry-expo@next`? I still was never able to repro this but there was a large amount of automatic work done there now, especially on eject if you configure the `plugins` field of app.json like the README says to now.

**Comment by ianbayne** [comment]
Thanks, @cruzach. Fortunately (unfortunately in regard to getting to the root of this), we're no longer having issues with Sentry not reporting errors, although it isn't clear why this has resolved itself. At any rate, thanks for the message. I'll close this issue now, but feel free to re-open if the `sentry-expo` maintainers feel this is something you want to devote time to. Thanks again!
