### ISSUE TITLE
Update @sentry/react-native to/past 2.0.0

### ISSUE THREAD

**Issue by JoeDuncko** [expo/sentry-expo#159]
`@sentry/react-native` released v2.0.0 on Oct 30th. It adds support for the [envelope endpoint](https://develop.sentry.dev/sdk/envelopes/), which for my team manifests as more robust notifications in Zulip.

**Comment by cruzach** [comment]
done in https://github.com/expo/sentry-expo/commit/72ed3c1ab80e8c9d0ea73157a791018788eae042, and released in `sentry-expo@3.0.4`, thanks @JoeDuncko !
