### ISSUE TITLE
sentry-expo 3.0.2. Issues not reported after upgrading from 2.0.3

### ISSUE THREAD

**Issue by vichoconejeros** [expo/sentry-expo#161]
Hi some time ago i updated the whole expo stack from 35 to 39, for that updating sentry-expo from 2.0.3 to 3.0.2 was needed
the only change needed on the sentry integration was to replaced calls like
`Sentry.captureException({res,data})`
to
`Sentry.Native.captureException({res,data})`
and that for all the methods i previously call as Sentry.* to Sentry.Native.* (with the exception of Sentry.init)

now i don't get anything being reported, i checked on the DSN and for my surprise the old url changed from
https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@sentry.io/XXXXXXX
to
https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@xxxxxxx.ingest.sentry.io/XXXXXXX
i'm not sure why, but i made the update of the url, but it keeps failing to send events & exceptions
enabling debug:true on the init doesn't give me much information about what might be happening and i have set enableInExpoDevelopment:true since day one

**Comment by cruzach** [comment]
hey @vichoconejeros , sorry about the late followup. Are you still seeing this? We haven't had other reports of this on `sentry-expo` v3.0.4 so maybe you could try upgrading?

**Comment by vichoconejeros** [comment]
hi @cruzach after some investigation i think related to the usage quota. so please consider this issue as resolved
