### ISSUE TITLE
When building for iOS, error: "CocoaPods could not find compatible versions for pod "EXDevice""

### ISSUE THREAD

**Issue by realfresh** [expo/sentry-expo#163]
Good news is I worked out the issue. Figured I'd post it here in case someone else is struggling.

I'm using expos build service + managed workflow for expo app (SDK 40) + yarn package manager.

Initially, my builds were fine but after I added sentry-expo, the iOS builds started failing with this:

```
....
....
Make sure following dependencies of your project are resolving to one specific version:
 expo-updates, expo-device
Auto-linking React Native modules for target `BNODrivers`: RNCMaskedView, RNGestureHandler, RNReanimated, RNScreens, and react-native-safe-area-context
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
[!] CocoaPods could not find compatible versions for pod "EXDevice":
  In Podfile:
    EXDevice (from `../node_modules/sentry-expo/node_modules/expo-device/ios`)
Specs satisfying the `EXDevice (from `../node_modules/sentry-expo/node_modules/expo-device/ios`)` dependency were found, but they required a higher minimum deployment target.
Xcode build logs not found
Build failed: pod exited with non-zero code: 1
```

The issue is that expo SDK 40.0.1 seems to only be compatible with the package expo-device (2.4.0). However, when installing Sentry expo, yarn installs expo-device (3.0.0) causing the build issue.

To fix this, what you must do is add the following to your package.json file.

```
{
  "dependencies": {...}
  "resolutions": {
    "expo-device": "~2.4.0"
  }
}
```

This will force yarn to resolve the correct version thereby fixing the problem.

**Comment by realfresh** [comment]
So as it turns out, this was only the start of an endless stream of problems. Seems to be a lot of dependency related issues when using this library and expo sdk 40. On android is fine but iOS it always crashes after calling Sentry.init when the app starts.

Literally can't get it to work no matter what I try.

**Comment by celsoernani** [comment]
Its work

**Comment by realfresh** [comment]
Good to hear you got it working. I'm still struggling to get it to work. I don't understand exactly what's going wrong but I'm pretty sure its something dependency related. I think sentry-expo is installing expo packages with versions that are not compatible with expo 40 SDK. I've tried going through the dependencies but I was unable to pinpoint the issue.

Not sure if anyone can make sense of this but here's one of the iOS crash logs from the iPhone.

![image](https://user-images.githubusercontent.com/7835503/103254865-0e758d00-49c2-11eb-89e1-3746f37894ea.png)

**Comment by LRNZ09** [comment]
It seems to be a problem with unimodules searching within `sentry-expo` node_modules folder too.

**Comment by CLASHERBROs** [comment]
Hi try changing platform to a higher ios in podflie

**Comment by thanh90** [comment]
changing platform from 10 to 11 fixed

**Comment by ajgrover** [comment]
I had to pin both `expo-device=~2.3.0` and `expo-constants=~9.2.0` to fix the build issues with SDK v39. Found those versions by `expo install`ing those packages and seeing what compatible version was chosen. For `expo-constants` this meant adding it to the `resolutions` section of the package.json, even though it was already pinned to a single version in the dependencies section.

I'm also still getting a crash on app startup, before sentry is initialized, with my EAS builds. I don't think it's related to sentry-expo though as it was happening before I added that to my app

**Comment by LRNZ09** [comment]
Changing platform to a higher iOS version in Podfile is NOT a solution.

**Comment by cruzach** [comment]
Hi all, sorry about this! It should be fixed in `sentry-expo@3.0.5` which is currently published as `next`

Please install that, and re-run `pod install`, and you can keep your deployment target at 10. (Will probably release a new version of `sentry-expo` soon that supports iOS 11 and up)

**Comment by cruzach** [comment]
Just wanted to follow-up here and see how that fix was working for those that have implemented it?

**Comment by allan-simon** [comment]
I just got the problem, I'm going to tell you very soon it that fix the issue :)

**Comment by allan-simon** [comment]
I confirm to you now the build pass

**Comment by alcidesbsilvaneto** [comment]
I was having the same problem with managed app when trying to build with eas build --local. My problem was I installed "expo-device" package with yarn instead of expo install. Running expo install expo-device worked.

**Comment by bartemb** [comment]
I had this problem with expo-system-ui. Version 2.4.0 showed a minimal version 12.0 in podspec, which matched the platform in the Podfile. I downgraded with npm i expo-system-ui@2.4.0, did pod install at it's working now.
