### ISSUE TITLE
Empty DSN resulting in standalone app crash at startup

### ISSUE THREAD

**Issue by xmflsct** [expo/sentry-expo#167]
I accidentally forgot to include DSN environment variable during my CI build. That results in standalone app crashing at launch without much debug info available. Think this can be taken more gracefully?

**Comment by cruzach** [comment]
So if there's no DSN I think the SDK just doesn't send any data to Sentry...

Do you have a stack trace of the crash?

**Comment by cruzach** [comment]
It's possible this crash was due to some other error, since I wasn't able to reproduce it. If you can provide a stack trace that points to sentry-expo, happy to re open and investigate
