### ISSUE TITLE
expo install sentry-expo has no effect

### ISSUE THREAD

**Issue by giautm** [expo/sentry-expo#171]
**Summary**

Currently sentry-expo not listed in [bundledNativeModules](https://github.com/expo/expo/blob/master/packages/expo/bundledNativeModules.json). So, `expo install sentry-expo` has no effect, and install wrong verion 

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android, iOS, Web

**SDK Version (managed workflow only)**

40

**Environment**

  Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.19.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.2/12B5025f - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

run `expo install sentry-expo`

**Comment by cruzach** [comment]
What version is it installing, and what version do you expect to be installed?

**Comment by giautm** [comment]
Is sentry-expo dependence on @sentry/react-native? Which version of `@sentry/react-native` I can use on Expo SDK 38, 39, 40. If I'm on SDKv38 and installed the latest version of sentry-expo, it will use [`@sentry/react-native@2.1.0`](https://github.com/expo/sentry-expo/blob/19abb5dfb1891ffb9341d1c10de0269b6748d05f/package.json#L30). So, Is it correct?

I want to use [`@sentry/react-native@2.2.0`](https://github.com/getsentry/sentry-react-native/releases/tag/2.2.0) on SDKv40 - it has `React Navigation Instrumentation` supported

**Comment by cruzach** [comment]
none of the native code from @sentry/react-native is included in the managed workflow, for that you should use the bare workflow

If the feature you want is a JS feature, then it will be included when we upgrade sentry-expo to rely on 2.2.0

**Comment by cruzach** [comment]
issue to track the upgrade to 2.2.0 is here- https://github.com/expo/sentry-expo/issues/173
