### ISSUE TITLE
Issue tracking user sessions, release adoption, and version health 

### ISSUE THREAD

**Issue by pweisensee** [expo/sentry-expo#176]
**Summary**

 I am having issues getting user session tracking working in `3.0.5`. So I tried upgrading to `sentry-expo@next`. However, the `expo publish` never works. How can I get the Sentry Releases to show user adoption rate and general version health?

1. I ran `yarn add sentry-expo@next`
2. Added `"plugins": ["sentry-expo"],` to my `app.json`
3. I run `expo publish`
4. I get error:
```
Building optimized bundles and generating sourcemaps...
Error: Problem validating fields in app.json. See https://docs.expo.io/workflow/configuration/
 • should NOT have additional property 'plugins'.
Couldn't publish because errors were found. (See logs above.) Please fix the errors and try again.
```

5. So I remove the plugin config from `app.json`, run `expo publish`, and I get:
```
Building optimized bundles and generating sourcemaps...
Unable to load postPublish hook: 'sentry-expo/upload-sourcemaps'. The module does not export a function.
Please fix your postPublish hook configuration
```

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android, iOS

**SDK Version (managed workflow only)**

40

**Environment**

  Expo CLI 4.2.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.24.0 - ~/.nvm/versions/node/v10.24.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v10.24.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3
        System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6821437
      Xcode: 11.7/11E801a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.2.1
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

My Init code:
```
    Sentry.init({
        dsn: 'https://......ingest.sentry.io/xxxxxxx',
        enableAutoSessionTracking: true,
    });
```

```
"hooks": {
    "postPublish": [
        {
            "file": "sentry-expo/upload-sourcemaps",
            "config": {
                "organization": "xxxxx",
                "project": "xxxxx",
                "authToken": "xxxx"
            }
        }
    ]
}
```

**Comment by pweisensee** [comment]
Related issue #173

**Comment by cruzach** [comment]
the `plugins` field will be supported in SDK 41 (currently it doesn't affect managed workflow projects unless you're attempting to use EAS Build in the managed workflow)

can you run `yarn why sentry-expo`? I'm not able to repro the postPublish hook problem on `expo-cli@4.1.6` and `sentry-expo@3.1.0`

**Comment by pweisensee** [comment]
Okay, good to know. I'm using `expo-cli@4.2.1`, could that be an issue? I tried `yarn remove sentry-expo` and then `yarn add sentry-expo@next` but it still throws the error. Same code works fine in `sentry-expo@3.0.5`. 

Here is the output running `yarn why sentry-expo`:
```
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "sentry-expo"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "sentry-expo@3.1.0"
info Has been hoisted to "sentry-expo"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "7.09MB"
info Disk size with unique dependencies: "23.7MB"
info Disk size with transitive dependencies: "7.09MB"
```

Still getting this error running `expo publish --release-channel testing`:
```
› Expo SDK: 40.0.0
› Release channel: testing
› Workflow: Managed

Building optimized bundles and generating sourcemaps...
Unable to load postPublish hook: 'sentry-expo/upload-sourcemaps'. The module does not export a function.
Please fix your postPublish hook configuration
```

I also get `TypeError` errors when I try to run the app:
`TypeError: undefined is not an object (evaluating 'Sentry.Native.setExtras')`

**Comment by pweisensee** [comment]
Upon reading issue #177, running `expo publish` in a `Node.js 14.16.0` environment succeeds. Node 12 fails. 

The `Sentry.Native` errors remain even in Node 14 environment.

**Comment by cruzach** [comment]
might be fixed in sentry-expo@3.1.2, please try it out

**Comment by pweisensee** [comment]
thanks, that does seem to resolve the build errors. I look forward to testing this version in production

**Comment by pweisensee** [comment]
@cruzach I rolled this out to production, and it seems to all be working except Session Tracking. (`enableAutoSessionTracking`). Is there something wrong with my `Sentry.init`? Is auto session tracking supported anymore in sentry expo?

**Comment by brunohkbx** [comment]
Session tracking is not working for me as well

**Comment by cruzach** [comment]
I'm not sure what the problem here could be- are you using the managed or bare workflow? Was sessionTracking working before on a previous version? If it was, which version?

It might be better to open a new issue with all that info, and close this one

**Comment by pweisensee** [comment]
Sure, I've opened a new issue. Closing this in favor of #181
