### ISSUE TITLE
sentry-expo has no exported member "Native"

### ISSUE THREAD

**Issue by Neodern** [expo/sentry-expo#178]
### Summary

I'm trying to upgrade sentry-expo to the last version (from 3.0.3) and i've an error when trying to use Native object (Normally accessible from Sentry.Native.*)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

40

### Environment

  Expo CLI 4.1.4 environment info:
    System:
      OS: macOS 11.2.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.9.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.5.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
    npmGlobalPackages:
      expo-cli: 4.1.4
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

import { Native } from "sentry-expo";

[...]

Native.getCurrentHub();

<img width="1403" alt="Capture d’écran 2021-03-04 à 08 45 29" src="https://user-images.githubusercontent.com/5598626/109929387-ad6e7c00-7cc6-11eb-81b0-dbd637f0273b.png">

![WhatsApp Image 2021-03-04 at 08 53 36](https://user-images.githubusercontent.com/5598626/109930120-8d8b8800-7cc7-11eb-97b0-75ce4948e2d1.jpeg)

**Comment by cruzach** [comment]
I see what I did wrong here- will push out a fix for this tomorrow

**Comment by cruzach** [comment]
fixed in https://github.com/expo/sentry-expo/commit/3556dc1c10675ea41d7e9d52181f6bce6315444f

**Comment by cruzach** [comment]
released in 3.1.2 (install with `yarn add sentry-expo@next`)

**Comment by Neodern** [comment]
@cruzach Hello ! 

Thanks for the fix, it's now working on simulator, but on real device i've still this error: 

![59614074-9659-4FC1-B3BC-3298D0FEE0B2_1_102_o](https://user-images.githubusercontent.com/5598626/110212420-8e751300-7e9b-11eb-94fb-0fd2738f933a.jpeg)

**Comment by cruzach** [comment]
If you’re using “Native.init”, then you should make sure you’re in the bare workflow and have gone through those install steps

**Comment by Neodern** [comment]
I'm in the managed workflow. i've this error (from the screenshot) with this snippet of code: 

```
import * as Sentry from "sentry-expo";

Sentry.init({
[...]
});
[...]
Sentry.Native.captureException(error);
```

Should i use sentry-expo in a different way ?
