### ISSUE TITLE
Captured exception not flushed before app reload

### ISSUE THREAD

**Issue by mackenziekira** [expo/sentry-expo#185]
We have a top level error boundary that captures an exception and then reloads the app with the latest OTA update:

```
Sentry.captureException(error, {
      extra: { componentStack: errorInfo.componentStack },
    });
Updates.reloadAsync();
```

But the captured error does not make it to Sentry. I think the most likely issue is that the exception is not getting flushed; is it possible to expose something like `Sentry.flush` on the api? A suboptimal workaround I tried is to throw the reload in a setTimeout.

versions:
```
sentry-expo:"2.1.2"
expo-updates:"0.4.1"
expo:"40.0.0"
```

**Comment by cruzach** [comment]
All of the native `Sentry` methods are exposed via `Sentry.Native`, but @sentry/react-native doesn't expose a `.flush` method. You may want to refer to [Sentry's own repo](https://github.com/getsentry/sentry-react-native) and docs for this, I don't believe it's a problem with the `sentry-expo` wrapper (unless you have more info that does point to it specifically being a problem with `sentry-expo`?)
