### ISSUE TITLE
Upgrade expo-update for SDKv41

### ISSUE THREAD

**Issue by giautm** [expo/sentry-expo#190]
https://github.com/expo/sentry-expo/blob/334cbdc8379c42e42dfd6c6fbfe7f397da7cd49c/package.json#L50

**Comment by cruzach** [comment]
This will be addressed in v4.0.0 (releasing now) as you will install your own versions of `expo-updates` (as well as `expo-constants`, `expo-application`, and `expo-device`)

**Comment by giautm** [comment]
sound good, 👍
