### ISSUE TITLE
Unable to seamlessly switch between Native and Browser because of function signature incompatibility

### ISSUE THREAD

**Issue by znmto** [expo/sentry-expo#191]
During investigation, it was found that both `@sentry/browser` and `@sentry/react-native` use types from `@sentry/types`. So in order for users to be able to seamlessly switch between `Native` and `Browser` objects, its imperative that they depend on non-conflicting versions of `@sentry/types`. 

The current version of `sentry-expo` has the following dependency tree:

```
sentry-expo@3.1.4
  @sentry/browser@^6.2.0
    @sentry/core@6.4.0
    @sentry/types@6.4.0
    @sentry/utils@6.4.0
  @sentry/react-native@^2.2.1
    @sentry/browser@6.2.1
      @sentry/core@6.2.1
      @sentry/types@6.2.1
      @sentry/utils@6.2.1
```

This can be fixed if `sentry-expo` locks the versions of the problematic sub-dependencies, which will resolve `@sentry/types@6.2.1`:
```
"@sentry/browser": "6.2.1",
```

Here is an example temporary fix using the resolutions field in `package.json`:
```
"resolutions": {
    "sentry-expo/@sentry/browser": "6.2.1"
  },
```

Thank you for your attention!

**Comment by cruzach** [comment]
Hm, I think I would rather have people rely on their own `resolutions`, rather than pin that version of a sentry package, otherwise we'll have to release new versions of sentry-expo for each patch release of `@sentry/browser`
