### ISSUE TITLE
App hangs on Sentry.init

### ISSUE THREAD

**Issue by asalha** [expo/sentry-expo#198]
### Summary

I have App.tsx exactly as it is in the snack below. When I start the app, it just hangs and does not run. When I comment Sentry.init in App.tsx, the app starts without any problem. However, in the Snack it works fine, but not on my Android emulator! No idea why.
When I run "expo build:android -t apk" I receive a message saying:
Error uploading sourcemaps to Sentry: project not found

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41.0.1

### Environment

  Expo CLI 4.7.2 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
      npm: 7.6.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ~41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@raselmat/expo-sentry

**Comment by cruzach** [comment]
Hi! Have you tried solutions from similar issues- https://forums.expo.io/t/error-uploading-sourcemaps-to-sentry-project-not-found/47522/4?

**Comment by asalha** [comment]
> Hi! Have you tried solutions from similar issues- https://forums.expo.io/t/error-uploading-sourcemaps-to-sentry-project-not-found/47522/4?

Yep, it was exactly that. Thank you for your help
