### ISSUE TITLE
undefined is not an object (evaluating 'expo_constants_1.ExecutionEnvironment.Bare')

### ISSUE THREAD

**Issue by GiverDead** [expo/sentry-expo#199]
### Summary

Expo managed project does not have expo_constants_1.ExecutionEnvironment

error when `import * as Sentry from 'sentry-expo';`

package.json
`{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.15.4",
    "@react-native-community/datetimepicker": "^3.4.3",
    "axios": "^0.21.1",
    "expo": "~39.0.2",
    "expo-app-loading": "^1.0.1",
    "expo-application": "~2.3.0",
    "expo-barcode-scanner": "~9.0.0",
    "expo-constants": "~9.2.0",
    "expo-device": "~2.3.0",
    "expo-facebook": "~9.0.0",
    "expo-font": "~8.3.0",
    "expo-google-app-auth": "^8.1.4",
    "expo-image-picker": "~9.1.1",
    "expo-linear-gradient": "~8.3.0",
    "expo-linking": "^2.0.0",
    "expo-localization": "~9.0.0",
    "expo-notifications": "~0.7.2",
    "expo-permissions": "~9.3.0",
    "expo-status-bar": "~1.0.2",
    "expo-updates": "~0.3.3",
    "i18n-js": "^3.8.0",
    "moment": "^2.29.1",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz",
    "react-native-draggable": "^3.3.0",
    "react-native-gesture-handler": "^1.9.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-paper": "^4.4.1",
    "react-native-qrcode-svg": "^6.0.6",
    "react-native-reanimated": "~1.13.0",
    "react-native-screens": "~2.10.1",
    "react-native-svg": "12.1.0",
    "react-native-web": "~0.13.12",
    "react-vue": "0.0.5",
    "react-vue-helper": "0.0.7",
    "sentry-expo": "^4.0.0",
    "vue-native-core": "^0.1.4",
    "vue-native-helper": "^0.1.4",
    "vue-native-router": "^0.2.0",
    "vuex": "^3.6.2"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "react-vue-loader": "^0.1.2",
    "vue-native-scripts": "^0.1.4"
  },
  "private": true
}
`

expo_constants_1 variable dump
`{
  "AppOwnership": Object {
    "Expo": "expo",
    "Guest": "guest",
    "Standalone": "standalone",
  },
  "UserInterfaceIdiom": Object {
    "Handset": "handset",
    "Tablet": "tablet",
    "Unsupported": "unsupported",
  },
  "default": Object {
    "addListener": [Function anonymous],
    "appOwnership": "expo",
    "deviceId": "3b39105b-b989-4b75-b2c6-c01749ca2681",
    "deviceName": "M6 Note",
    "deviceYearClass": 2014,
    "experienceUrl": "exp://192.168.0.111:19000",
    "expoVersion": "2.19.3",
    "getWebViewUserAgentAsync": [Function anonymous],
    "installationId": "3b39105b-b989-4b75-b2c6-c01749ca2681",
    "intentUri": "exp://192.168.0.111:19000",
    "isDetached": false,
    "isDevice": true,
    "isHeadless": false,
    "linkingUri": "exp://192.168.0.111:19000",
    "linkingUrl": "exp://192.168.0.111:19000",
    "manifest": Object {
      "_internal": Object {
        "dynamicConfigPath": null,
        "isDebug": false,
        "packageJsonPath": "D:\\kiddo\\package.json",
        "projectRoot": "D:\\kiddo",
        "staticConfigPath": "D:\\kiddo\\app.json",
      },
      "android": Object {
        "config": Object {
          "googleSignIn": Object {
            "certificateHash": "AD8BE7AF50750D63807470E4D8605FB8EEA3F684",
          },
        },
        "package": "com.mykkiddo.app.test",
      },
      "assetBundlePatterns": Array [
        "**/*",
      ],
      "bundleUrl": "http://192.168.0.111:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false&minify=false",
      "debuggerHost": "192.168.0.111:19001",
      "developer": Object {
        "projectRoot": "D:\\kiddo",
        "tool": "expo-cli",
      },
      "env": Object {},
      "facebookAppId": "3968424089857391",
      "facebookDisplayName": "MyKidDo",
      "facebookScheme": "fb3968424089857391",
      "hooks": Object {
        "postPublish": Array [
          Object {
            "config": Object {
              "authToken": "dc152499557d44e3a2b22ca095de9f03f34cba44532940f180084cf48f8384b2",
              "organization": "getruck",
              "project": "mykiddo",
            },
            "file": "sentry-expo/upload-sourcemaps",
          },
        ],
      },
      "hostUri": "192.168.0.111:19000",
      "icon": "./assets/images/icon.png",
      "iconUrl": "http://192.168.0.111:19001/assets/./assets/images/icon.png",
      "id": "@giverdead/kiddo",
      "ios": Object {
        "supportsTablet": true,
      },
      "isVerified": true,
      "logUrl": "http://192.168.0.111:19000/logs",
      "mainModuleName": "node_modules\\expo\\AppEntry",
      "name": "MyKidDo",
      "orientation": "portrait",
      "packagerOpts": Object {
        "dev": true,
        "devClient": false,
        "hostType": "lan",
        "https": false,
        "lanType": "ip",
        "minify": false,
        "scheme": null,
        "urlRandomness": "mt-c84",
      },
      "platforms": Array [
        "ios",
        "android",
        "web",
      ],
      "primaryColor": "#023C69",
      "scheme": "mychildconnect",
      "sdkVersion": "39.0.0",
      "slug": "kiddo",
      "splash": Object {
        "backgroundColor": "#ffffff",
        "image": "./assets/images/splash.png",
        "imageUrl": "http://192.168.0.111:19001/assets/./assets/images/splash.png",
        "resizeMode": "contain",
      },
      "updates": Object {
        "fallbackToCacheTimeout": 0,
      },
      "version": "0.0.01",
      "web": Object {
        "favicon": "./assets/favicon.png",
      },
    },
    "nativeAppVersion": "2.19.3",
    "nativeBuildVersion": 149,
    "platform": Object {
      "android": Object {
        "versionCode": null,
      },
    },
    "removeListeners": [Function anonymous],
    "sessionId": "7b5981db-f699-4988-b495-7d7a82afe4dc",
    "statusBarHeight": 22,
    "supportedExpoSdks": Array [
      "41.0.0",
      "40.0.0",
      "39.0.0",
      "38.0.0",
    ],
    "systemFonts": Array [
      "normal",
      "notoserif",
      "sans-serif",
      "sans-serif-light",
      "sans-serif-thin",
      "sans-serif-condensed",
      "sans-serif-medium",
      "serif",
      "Roboto",
      "monospace",
    ],
    "systemVersion": "7.1.2",
  },
}
`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

39

### Environment

 Expo CLI 4.4.3 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 16.0.0 - C:\Program Files (x86)\nodejs\node.EXE
      npm: 7.10.0 - C:\Program Files (x86)\nodejs\npm.CMD
    npmPackages:
      expo: ~39.0.2 => 39.0.5
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

expo install sentry-expo

in app.js add `import * as Sentry from 'sentry-expo';`

**Comment by cruzach** [comment]
as we state in [the docs](https://docs.expo.io/guides/using-sentry/#install-and-configure-sentry): 

> If you're using SDK 39 or lower, run yarn add sentry-expo@~3.0.0

**Comment by GiverDead** [comment]
Unable to resolve "./version" from "node_modules\sentry-expo\node_modules\@sentry\core\dist\index.js" 

yarn add sentry-expo@~3.0.0
