### ISSUE TITLE
trouble with android sourcemaps and exceptions

### ISSUE THREAD

**Issue by alxyuu** [expo/sentry-expo#2]
few issues: 
* upload-sourcemaps.js is using the ios map for android: `fs.writeFileSync(tmpdir + '/main.android.map', iosSourceMap, 'utf-8');`
* the source often indicates the wrong line (like 5-10 lines off). this is after I updated the upload to send the androidSourceMap instead, it was pointing at entirely wrong files before that.
* apparently meaningful traces are only generated when the app crashes/restarts, and not all errors seem to crash the app. Performing `Sentry.captureException('some string message')` results in no stack trace being generated on android (it does on ios).
* Throwing an exception in the componentWillMount of a screen will not crash the app but causes the view to become unresponsive, and sentry will receive an error with a few `? [native code]`s as a stack trace. interestingly enough, the navigation header is still responsive (I'm using ex-navigation). Once I click a button in the header that tries to push another route, the app crashes citing the previous error thrown in componentWillMount. This generates another error in sentry, this time with a proper stack trace (we're now at 2 events for the same error?). For reference, iOS will crash immediately on the same error in componentWillMount and send the correct stack trace to sentry. Alternatively, throwing an error in an onPress callback does crashes the app immediately on both ios and android and sends the expected data to sentry.

All that said, I suspect the sourcemap being off and not collecting stack traces aren't actually issues directly from this project, as the base raven client has the same trouble generating stack traces on android as well.

**Comment by brentvatne** [comment]
Thanks @alxyuu! This was a last minute typo when refactoring, totally my fault for letting it through. Fixed in 1.0.1
