### ISSUE TITLE
ErrorUtils flow error

### ISSUE THREAD

**Issue by quincycs** [expo/sentry-expo#20]
ErrorUtils is used without being imported on index.js.

Can you please update index.js to import it?

The fix:
import { Constants, ErrorUtils } from 'expo';

**Comment by quincycs** [comment]
oh sorry, i'm not sure where ErrorUtils is actually defined.  It's not defined in expo. Hmm

**Comment by kylefoo** [comment]
Any solution to this yet?

**Comment by andresespinosapc** [comment]
I think ErrorUtils is defined globally with React Native. I have not been able to handle errors though, I think `setGlobalHandler` is being override after I define it.

**Comment by aldegoeij** [comment]
I'm getting this error trying to use `sentry-expo` on web (using `expo start -w`) any clue how to fix this? ErrorUtils is included in React Native, but not meant to be imported, it's just available.

Does this have something to do with running on web?

**Comment by AdamGerthel** [comment]
Importing with `import ErrorUtils from 'ErrorUtils'` seems to work. However, I still haven't managed to find a way to use a custom error handler using ErrorUtils.setGlobalHandler :/
