### ISSUE TITLE
Some dependencies no longer included by default in SDK42

### ISSUE THREAD

**Issue by jedahan** [expo/sentry-expo#201]
### Summary

I am trying to update to SDK42. I think a lot of dependencies were removed that sentry depends on.

Two that I have seen error out:

* `expo-device`
* `expo-updates`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

```
  Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.3 - /opt/homebrew/opt/node@14/bin/node
      npm: 6.14.13 - /opt/homebrew/opt/node@14/bin/npm
      Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

```
expo init --npm --yes
expo install sentry-expo
echo 'import * as Sentry from \'sentry-expo\'' >> App.js
expo start
```

Open QR code with expo go on iOS

**Comment by cesargdm** [comment]
I'm also getting after updating expo 42 and expo-sentry 4

```
Failed building JavaScript bundle.
Unable to resolve module expo-updates from /Users/admin/Developer/web/nure/neo-app/node_modules/sentry-expo/build/sentry.js: expo-updates could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  22 | exports.init = exports.Native = void 0;
  23 | const react_native_1 = require("react-native");
> 24 | const Updates = __importStar(require("expo-updates"));
     |                                       ^
  25 | const expo_constants_1 = __importStar(require("expo-constants"));
  26 | const Application = __importStar(require("expo-application"));
  27 | const integrations_1 = require("@sentry/integrations");
  ```

**Comment by jedahan** [comment]
btw my workaround is manually adding expo-updates to my projects package.json, even though we dont import it directly.

**Comment by s3131212** [comment]
It seems that [the official sentry-expo guide](https://docs.expo.io/guides/using-sentry/) has been updated to mention the additional dependencies.

Related commit:
https://github.com/expo/expo/commit/499ef3f64c9dccdc1b5abaf62cda4b15e708dc88#diff-f8cfbda2c23f6dea31fa010ae582041b68973b2830214f1efcc2dfeb9cab45dd

**Comment by cruzach** [comment]
Yep, this is mentioned as a breaking change in the changelog- https://github.com/expo/sentry-expo/blob/master/CHANGELOG.md#-breaking-changes

Make sure to always read through that when upgrading!
