### ISSUE TITLE
No Release Health/Performance Monitoring telemetry in SDK 42 Managed App

### ISSUE THREAD

**Issue by andres-j** [expo/sentry-expo#202]
### Summary

Attempting to add Sentry to a managed app using directions provided at https://docs.expo.io/guides/using-sentry/ & this repository's readme. 

Unfortunately after several releases with sentry added a lot of the functionality appears to be disabled and we cannot determine why. At the moment our releases show up in our sentry.io project view and custom events we fire show up as well (ie, Sentry.captureMessage). However none of the out-of-the-box functionality associated with "Release Health" or "Performance Monitoring" seems to work. Our Sentry.io project behaves as though these features are disabled (Our "Releases" view prompts to add Release Health, "Crash Free Sessions" in the dashboard points to set up, several fields in Project Details view are disabled and say Release Health/Performance Monitoring is not implemented). I understood that crashes could not be captured by Sentry in managed but expected much of the rest to work - perhaps this is not the case? Thanks in advance for any help!

Current sentry init looks like this: 

```
Sentry.init({
  dsn: "{Project Dsn, copied from project settings, omitted here}",
  enableInExpoDevelopment: true,
  enableAutoSessionTracking: true,
  debug: true,
  tracesSampleRate: 1.0,
  integrations: [
    new Sentry.Native.ReactNativeTracing({ tracingOrigins: ["*"] })
  ]
});
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

42

### Environment

Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 11.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.4.2 - ~/.nvm/versions/node/v16.4.2/bin/node
      npm: 7.18.1 - ~/.nvm/versions/node/v16.4.2/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.0 => 42.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

In SDK 42, managed typescript app using:
`sentry-expo@^4.0.0`
`@sentry/react-native@2.6.0`

```
import { StatusBar } from 'expo-status-bar';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

export default function App() {

Sentry.init({
  dsn: "{{Project DSN}}",
  enableAutoSessionTracking: true,
  tracesSampleRate: 1.0,
  integrations: [
    new Sentry.Native.ReactNativeTracing({ tracingOrigins: ["*"] })
  ]
});

  return (
    <View style={styles.container}>
      <Text>This won't send any session data!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

**Comment by andres-j** [comment]
Closing this issue - never figured out the root cause but we've gone with an alternate solution for app telemetry for the time being.

**Comment by meharajM** [comment]
@andres-j what was the alternate solution ?
