### ISSUE TITLE
Usage with Expo Web

### ISSUE THREAD

**Issue by LinusU** [expo/sentry-expo#205]
### Summary

I'm having some problems using this module with Expo Web. We have an app that we build for all three platforms, and I'm not really sure what the intended usage for this module is.

The exports from this module is both `Browser` and `Native`, and when building for Expo Web `Native` isn't available at all. Is the intended usage that we ourselves needs to create a `.web.ts` and `.native.ts` files to make sure that the correct export is used on the correct platform?

There are also things missing from `Browser`, e.g. `ErrorBoundary` and the `ReactNavigationV5Instrumentation`.

I think that the best outcome would be for this module to export platform-independent versions of all things, instead of having two exports which seems to be intended for different platforms. Is this a goal that you think is aligned with this project? and would you accept pull requests to move towards that?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

42

### Environment

```text
  Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.5.0 - /opt/homebrew/bin/node
      Yarn: 1.22.10 - node_modules/.bin/yarn
      npm: 7.19.1 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.dev/@linusu/expo-sentry-web-issues

This snack works great on native, but errors out on web.

**Comment by sreuter** [comment]
@EvanBacon @brentvatne Could any of you clarify?

**Comment by LinusU** [comment]
ping @EvanBacon @brentvatne, any thoughts on this? ☺️

**Comment by pors** [comment]
I think it would make things easier if the expo-sentry package would detect the platform and export either `Native` or `Browser` when it is applicable.

Currently I use a hack by exporting this from App.js and importing it from files that need it:

`export const S = (Platform.OS === 'web') ? Sentry.Browser : Sentry.Native;`

**Comment by LinusU** [comment]
@pors I think it's a bit more complicated than a conditional export, since `Native` and `Browser` doesn't have the same properties.

Something like this is what we are currently using:

**`sentry.ts`**

```typescript
import { NavigationContainerRef } from '@react-navigation/core'
import { RefObject } from 'react'
import * as Sentry from 'sentry-expo'

import { SENTRY_DATA_SOURCE_NAME } from '../lib/config'

const routingInstrumentation = new Sentry.Native.ReactNavigationV5Instrumentation()

Sentry.init({
  dsn: SENTRY_DATA_SOURCE_NAME,
  integrations: [new Sentry.Native.ReactNativeTracing({ routingInstrumentation })]
})

export const addBreadcrumb = Sentry.Browser.addBreadcrumb
export const captureException = Sentry.Native.captureException
export const ErrorBoundary = Sentry.Native.ErrorBoundary

export function registerNavigationContainer (navigation: RefObject<NavigationContainerRef<any>>): void {
  routingInstrumentation.registerNavigationContainer(navigation)
}
```


**`sentry.web.ts`**

```typescript
import * as SentryReact from '@sentry/react'
import * as Sentry from 'sentry-expo'

import { SENTRY_DATA_SOURCE_NAME } from '../lib/config'

Sentry.init({
  dsn: SENTRY_DATA_SOURCE_NAME
})

export const addBreadcrumb = Sentry.Browser.addBreadcrumb
export const captureException = Sentry.Browser.captureException
export const ErrorBoundary = SentryReact.ErrorBoundary

export function registerNavigationContainer (_: any): void {}
```

**Comment by pors** [comment]
@LinusU Ah, that's very helpful, thanks!

**Comment by kbrandwijk** [comment]
There's no intention to unify the interface between `@sentry/react-native` and `@sentry/browser` within the scope of this project, as you mentioned, they have different methods available for native and web.

The solution to create a .web.js/.web.ts is a good solution for this.

**Comment by itsramiel** [comment]
> @pors I think it's a bit more complicated than a conditional export, since `Native` and `Browser` doesn't have the same properties.
> 
> Something like this is what we are currently using:
> 
> **`sentry.ts`**
> 
> ```ts
> import { NavigationContainerRef } from '@react-navigation/core'
> import { RefObject } from 'react'
> import * as Sentry from 'sentry-expo'
> 
> import { SENTRY_DATA_SOURCE_NAME } from '../lib/config'
> 
> const routingInstrumentation = new Sentry.Native.ReactNavigationV5Instrumentation()
> 
> Sentry.init({
>   dsn: SENTRY_DATA_SOURCE_NAME,
>   integrations: [new Sentry.Native.ReactNativeTracing({ routingInstrumentation })]
> })
> 
> export const addBreadcrumb = Sentry.Browser.addBreadcrumb
> export const captureException = Sentry.Native.captureException
> export const ErrorBoundary = Sentry.Native.ErrorBoundary
> 
> export function registerNavigationContainer (navigation: RefObject<NavigationContainerRef<any>>): void {
>   routingInstrumentation.registerNavigationContainer(navigation)
> }
> ```
> 
> **`sentry.web.ts`**
> 
> ```ts
> import * as SentryReact from '@sentry/react'
> import * as Sentry from 'sentry-expo'
> 
> import { SENTRY_DATA_SOURCE_NAME } from '../lib/config'
> 
> Sentry.init({
>   dsn: SENTRY_DATA_SOURCE_NAME
> })
> 
> export const addBreadcrumb = Sentry.Browser.addBreadcrumb
> export const captureException = Sentry.Browser.captureException
> export const ErrorBoundary = SentryReact.ErrorBoundary
> 
> export function registerNavigationContainer (_: any): void {}
> ```

@LinusU is `export const addBreadcrumb = Sentry.Browser.addBreadcrumb` in sentry.ts a typo? shouldn't it use native?

**Comment by LinusU** [comment]
@itsramiel looks like a typo indeed (alltough seems to have worked 😅) I'll edit my post 👍

**Comment by bombillazo** [comment]
I cant get this to work on web, I get the following error:

```sh
event - compiled client and server successfully in 1284 ms (2931 modules)
Sentry Logger [log]: Integration installed: InboundFilters
Sentry Logger [log]: Integration installed: FunctionToString
Sentry Logger [log]: Integration installed: TryCatch
Sentry Logger [log]: Integration installed: Breadcrumbs
Sentry Logger [log]: Global Handler attached: onerror
Sentry Logger [log]: Global Handler attached: onunhandledrejection
Sentry Logger [log]: Integration installed: GlobalHandlers
Sentry Logger [log]: Integration installed: LinkedErrors
Sentry Logger [log]: Integration installed: Dedupe
Sentry Logger [log]: Integration installed: HttpContext
Sentry Logger [warn]: Session tracking in non-browser environment with @sentry/browser is not supported.
```
