### ISSUE TITLE
Error uploading sourcemaps to Sentry: spawn /.../node_modules/@sentry/cli/sentry-cli ENOENT

### ISSUE THREAD

**Issue by jackkinsella** [expo/sentry-expo#206]
### Summary

The hook to upload sourcemaps calls a non-existent file: `@sentry/cli/sentry-cli`. Instead it should probably call a file that exists is in the `bin` subfolder - i.e. `@sentry/cli/bin/sentry-cli`.

This can be reproduced by installing the same package versions as `expo install expo-sentry` installs:

```
    "sentry-expo": "^3.1.0",
    "sentry-sdk": "^0.1.3"
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

41 Expo. Sentry -> see above.

### Environment

  Expo CLI 4.10.0 environment info:
    System:
      OS: macOS 11.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.8.0 - ~/.nvm/versions/node/v15.8.0/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 7.5.2 - ~/.config/yarn/global/node_modules/.bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.10.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

See above.

**Comment by melanger** [comment]
I had the same error when using `expo export` with `--merge-src-url`. When debugging with NODE_DEBUG=child_process, it seems that sentry-expo spawns first child process (sentry-cli) to create a release, which succeeds. Then `--merge-src-url` activates the merging, and during this process something changes. Then sentry-expo spawns another process to upload the sourcemaps (sentry-cli again), but this time it fails.

When I remove `--merge-src-url`, the two sentry-cli calls happen together and the upload succeeds.

**Comment by jackkinsella** [comment]
A workaround for now is to modify the config for sentry in the `app.config.js` to have

```javascript
{
   useGlobalSentryCli: true,
}
```

Make sure you install Sentry Cli with `npm install -g @sentry/cli` first.

**Comment by cruzach** [comment]
@jackkinsella can you list out the exact steps to reproduce? just tested on a new project and postPublish hooks worked fine

**Comment by kbrandwijk** [comment]
Unable to reproduce with the current version.
