### ISSUE TITLE
Doesn't log on TestFlight

### ISSUE THREAD

**Issue by borasumer** [expo/sentry-expo#207]
### Summary

I get Sentry error logs in dev mode, and also production mode running `expo start --no-dev --minify`, but in a build deployed to TestFlight, I don't see any logs. Not sure if I am missing anything or this is a known bug. Thanks

My sentry config:
```
Sentry.init({
  dsn: SENTRY_DSN,
  normalizeDepth: 10,
  debug: true,
});
```

And the way I capture the log:
`Sentry.Native.captureException(networkError);`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.9.1 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.6.3 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.9.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Blank

**Comment by cruzach** [comment]
Tested this on the most recent version and can't reproduce- without a reproducible demo I'm not sure I'll be able to help you debug your issue

**Comment by grantmagdanz** [comment]
Running into this same issue. Not sure what is going on testflight calls to Sentry are failing with `Native module not found`. Don't have more info right now, but am going to keep digging.
