### ISSUE TITLE
Clarify auth token scopes in documentation

### ISSUE THREAD

**Issue by ottob** [expo/sentry-expo#209]
### Summary

The documentation now says:
> The correct authToken value can be generated from the Sentry API page.

It would be very helpful if the docs included the scopes necessary for least possible privilege for writing events to sentry. Without this there is a risk that users just click all scopes and create a token with too much privilege.

<img width="798" alt="Screenshot 2021-08-23 at 10 00 50" src="https://user-images.githubusercontent.com/67104/130412452-98487be2-73f9-4485-8fea-9f1a8ecea2fb.png">

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

42

### Environment

sentry-expo-4.0.1

### Reproducible demo or steps to reproduce from a blank project

read docs at https://docs.expo.dev/guides/using-sentry/#install-and-configure-sentry

**Comment by cruzach** [comment]
We state in the docs: "Go to the Sentry API section, and create an auth token. **The token requires the scopes: org:read, project:releases, and project:write**. Save this, too."
