### ISSUE TITLE
Sentry.context when enableInExpoDevelopment = false

### ISSUE THREAD

**Issue by remeryAGS** [expo/sentry-expo#21]
If a function is wrapped in a `Sentry.context` call, the function is not executed when `enableInExpoDevelopment=false`. I would expect the passed-in function to be executed while ignoring the extra context information.

Example:
```
Sentry.enableInExpoDevelopment = false;
Sentry.config('https://example@sentry.io/123456').install();

Sentry.context({
  "extra": {
    "stuff": [1, 2, 3]
  },
  () => {
    alert("I'm an important function call!");
  }
);
```
The alert will not be executed.

This makes development difficult when you have a lot of extra context information for different function calls as these calls just won't happen in development mode.

**Comment by brentvatne** [comment]
hi there! I'm not sure what a good solution is here. you can keep it enabled in development if you like and sub in a different DSN config than what you use in prod maybe?
