### ISSUE TITLE
sentry needs to be updated 

### ISSUE THREAD

**Issue by nick0504k** [expo/sentry-expo#210]
### Summary

We recommend you update your SDK from sentry.javascript.react-native@v2.6.1 to sentry.javascript.react-native@v3.0.0 (All sentry packages should be updated and their versions should match)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

42

### Environment

 Expo CLI 4.11.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.5.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.20.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.3 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

sentry needs to be updated

**Comment by lucasvieceli** [comment]
up

**Comment by cvburgess** [comment]
Upgrading to 3.1.0 would also allow for support of React Navigation v6
https://github.com/getsentry/sentry-react-native/issues/1756

**Comment by cruzach** [comment]
Thanks for the issue, will make the upgrade soon. This is related to https://github.com/expo/sentry-expo/issues/212

**Comment by cruzach** [comment]
Fixed in `sentry-expo@4.0.2` (published under `next` for now, will move to `latest` in a couple days) 🎉

**Comment by cvburgess** [comment]
Hey there! My team would like to upgrade, when will 4.0.2 be available?

**Comment by cruzach** [comment]
hi! Released a new version (4.0.3) available now, under `next` with that fix and more. Will probably promote to `latest` tomorrow
