### ISSUE TITLE
[SOLVED] RNSentry.deviceContexts is not a function

### ISSUE THREAD

**Issue by sospedra** [expo/sentry-expo#211]
### Summary

There's currently a mismatch between `@sentry/react-native` and the `sentry-expo` dependency. Following the [normal setup](https://docs.expo.dev/guides/using-sentry/) yields this error:

```
Sentry Logger [Log]: Failed to get device context from native: TypeError: RNSentry.deviceContexts is not a function. (In 'RNSentry.deviceContexts()', 'RNSentry.deviceContexts' is undefined)
```

I couldn't dig too much into this but I believe `deviceContexts` has been renamed to `fetchNativeDeviceContexts`. Hence, there are **no** functions called `deviceContexts` in the Sentry Native Component.

A **quick solution** is to force the package resolution with `yarn`:

```js
// in package.json

"resolutions": {
    "@sentry/react-native": "YOUR INSTALLED VERSION"
}
```

That's it! I don't know this project that much but probably it's just about bumping the dependency and publishing back to `npm`.

Have a nice day!

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

Expo CLI 4.10.1 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.13.0 - ~/.asdf/installs/nodejs/12.13.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.12.0 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/sospedra/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.2 => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

1. Create new bareflow project
2. Follow expo instructions
3. (per stated in point 2) Install `@sentry/react-native`
4. Throw from JS (`throw new Error('test')`)

**Comment by cruzach** [comment]
Updating our version of sentry/react-native soon! Thanks for the issue @sospedra 👍
