### ISSUE TITLE
Not compatible with @sentry/react-native v3

### ISSUE THREAD

**Issue by jembach** [expo/sentry-expo#212]
### Summary

Hi,

I'm currently implementing sentry into my bare expo project, that is deployed using expo eas.
After installing the latest version of `@sentry/react-native` I discovered an compatibility problem with `sentry-expo`.

`sentry-expo` is using `@sentry/react-native@^2.5.2`.

A possible solution could be updating `@sentry/react-native` to the latest version. By doing so all upcoming projects using `sentry-expo` could use the latest performance features from sentry.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

42.0.3

### Environment

Expo CLI 4.11.0 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.5 - /usr/local/bin/node
      Yarn: 1.22.10 - ~/.npm-packages/bin/yarn
      npm: 6.14.11 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: 42.0.3 => 42.0.3 
      react: 17.0.2 => 17.0.2 
      react-native: 0.63.4 => 0.63.4 
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

1. `expo init --template bare-minimum`
2. `expo install expo-sentry`
3. `yarn add @sentry/react-native@latest`

**Comment by darrylyoung** [comment]
Hi, @jembach. I'm also having trouble with `sentry-expo` and `@sentry/react-native`. I'm not sure if it's directly related to my issue but it seems like it might be. I have an open issue in the Sentry GitHub [here](https://github.com/getsentry/sentry-react-native/issues/1773).

**Comment by cruzach** [comment]
hi! thanks for the issue- this is **probably** due to using a different version of @sentry/react-native than what comes bundled with sentry-expo. We can update this and make a fix

**Comment by jembach** [comment]
Thank you @cruzach for investigation time in this issue

**Comment by cruzach** [comment]
Fixed in `sentry-expo@4.0.2` (published under `next` for now, will move to `latest` in a couple days) 🎉
