### ISSUE TITLE
SentryError: Native Client is not available, can't start on native

### ISSUE THREAD

**Issue by cvburgess** [expo/sentry-expo#216]
### Summary

Appears to be similar/identical to https://github.com/expo/sentry-expo/issues/120 but with the latest version.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

42

### Environment

```
  Expo CLI 4.12.1 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.2.0 - /usr/local/bin/node
      npm: 7.20.5 - /usr/local/bin/npm
      Watchman: 2021.08.23.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.15.0 => 0.15.0 
      expo: ~42.0.1 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.12.1
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

Happens consistently after using this library on 4.0.3

**Comment by cvburgess** [comment]
Thank you

**Comment by opsline-jrios** [comment]
I'm using Expo SDK 42 and I have installed expo-sentry following the guide here https://docs.expo.dev/guides/using-sentry/, but I'm still receiving

```
[Unhandled promise rejection: SentryError: Native is disabled]
at node_modules/@sentry/react-native/node_modules/@sentry/utils/dist/error.js:9:20 in SentryError
at node_modules/@sentry/react-native/dist/js/wrapper.js:395:26 in <global>
at node_modules/@sentry/react-native/dist/js/tracing/reactnativetracing.js:4:0 in <global>
at node_modules/@sentry/react-native/dist/js/tracing/index.js:1:0 in <global>
at node_modules/@sentry/react-native/dist/js/measurements.js:2:0 in <global>
at node_modules/@sentry/react-native/dist/js/index.js:7:0 in <global>
at node_modules/sentry-expo/build/integrations/bare.js:30:30 in <global>
at node_modules/sentry-expo/build/sentry.js:28:22 in <global>
at node_modules/sentry-expo/build/index.js:26:20 in <global>
at App.js:10:0 in <global>
at node_modules/expo/AppEntry.js:3:0 in <global>
at http://192.168.0.216:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:430439:3 in global code
```

**Comment by lubeina** [comment]
> I'm using Expo SDK 42 and I have installed expo-sentry following the guide here https://docs.expo.dev/guides/using-sentry/, but I'm still receiving
> 
> ```
> [Unhandled promise rejection: SentryError: Native is disabled]
> at node_modules/@sentry/react-native/node_modules/@sentry/utils/dist/error.js:9:20 in SentryError
> at node_modules/@sentry/react-native/dist/js/wrapper.js:395:26 in <global>
> at node_modules/@sentry/react-native/dist/js/tracing/reactnativetracing.js:4:0 in <global>
> at node_modules/@sentry/react-native/dist/js/tracing/index.js:1:0 in <global>
> at node_modules/@sentry/react-native/dist/js/measurements.js:2:0 in <global>
> at node_modules/@sentry/react-native/dist/js/index.js:7:0 in <global>
> at node_modules/sentry-expo/build/integrations/bare.js:30:30 in <global>
> at node_modules/sentry-expo/build/sentry.js:28:22 in <global>
> at node_modules/sentry-expo/build/index.js:26:20 in <global>
> at App.js:10:0 in <global>
> at node_modules/expo/AppEntry.js:3:0 in <global>
> at http://192.168.0.216:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:430439:3 in global code
> ```

same here

**Comment by opsline-jrios** [comment]
@cruzach any insights about why this error is still happening? I'm using `expo build:*` not EAS, and I didn't install `@sentry/react-native`

**Comment by robbertrosario** [comment]
Same issue here, I am not using EAS build and did install `@sentry/react-native` I even followed the new README but no luck. Still: Sentry Logger [Warn]: SentryError: Native is disabled

**Comment by seyaobey-dev** [comment]
I have encountered the same error today with `sdk 43`, Expo Go (Managed). I have followed all the instructions [from official guideline](https://docs.expo.dev/guides/using-sentry/)

**Comment by MoSattler** [comment]
@cruzach I also followed the instructions, but the warning comes nonetheless. What's the best way for us to give you an env to reproduce?

**Comment by remcorakers** [comment]
I have the same error `SentryError: Native is disabled`. I'm using the managed Expo flow, and having the error both in Expo Go and when running on native iOS. I've run `expo install sentry-expo` and `expo install expo-application expo-constants expo-device expo-updates @sentry/react-native`. I didn't have this error while running on SDK 41, it only started after upgrading to SDK 44. It looks like this issue isn't (completely) resolved and should be re-opened. @cruzach, do you have any suggestions?

**Comment by sstedik** [comment]
I have the same error `SentryError: Native is disabled` when trigger Sentry.Native.* methods. Moreover, native crashes are not reported in Sentry!
It's critical problem!

I installed `@sentry/react-native` and added in plugins `'sentry-expo' ` according to https://docs.expo.dev/guides/using-sentry/ 
 
Expo of 43 version

**Comment by RRaideRR** [comment]
Same problem running on expo 43

**Comment by alexis-regnaud** [comment]
Same here with expo 42.0.4

**Comment by pors** [comment]
Also with Expo 44. Is related to this: https://github.com/expo/sentry-expo/issues/218#issuecomment-966787263

**Comment by Alex-vn-boulme** [comment]
Same here with sdk 42, can't find a solution for the moment :/

**Comment by daddou-ma** [comment]
I got the same issue with `sdk 42`. It worked after doing the following. 
 - Installing `@sentry/react-native ^3.2.13`
 - Installing `expo-tracking-transparency ~1.0.1`.
 - downgrading `sentry-expo` from `4.0.2` to `4.0.1`.
 - add `expo-tracking-transparency` plugin to `app.json`

**Comment by tsheaff** [comment]
Yes confirmed that `expo@46.0.13`, `sentry-expo@5.0.3` and `@sentry/react-native@4.2.2` (e.g. the latest for all as of today Oct 13, 2022), cause this every time for me.

I am on a dev client built with `eas build` (not Expo Go), built with those packages in place.

Downgrading to `sentry-expo@4.0.1` and `@sentry/react-native@3.4.3` resolves this.

**Comment by tsheaff** [comment]
Hmm, I think I may have an alternative solution that may have been the issue here.

The docs say to include `"plugins": ["sentry-expo"]`to your expo app config. However, for me if I use "sentry-expo" as a raw string in the top-level `plugins` array, I think this was the source of my issues.

When I do this instead it works:

```
    "plugins": [
      [
        "sentry-expo",
      ],
      [
        "expo-notifications",
        { ... }
      ],
      [
        "expo-image-picker",
        { ... },
      ],
      ...
    ]
```

I haven't tested every permutation of this and all the package libs, but it seems like the latest versions are working properly for me once I make a new native build with this change. Perhaps change the docs to say ``"plugins": [["sentry-expo"], ... ]` instead of `"plugins": ["sentry-expo"]`?
