### ISSUE TITLE
setTransport?

### ISSUE THREAD

**Issue by jmatsushita** [expo/sentry-expo#22]
Hi,

I'd like to use either the [`transport` config key](https://docs.sentry.io/clients/javascript/config/) or the `.setTransport()` function but it doesn't seem to work. Is that by design, or could it be added?

Cheers,

Jun

**Comment by brentvatne** [comment]
it looks like this client was deprecated. you can use sentry-expo in the same way you can use react-native-sentry so i'd just check out what options are available for you on that
