### ISSUE TITLE
Having a warning deprecation message Constants.deviceYearClass after upgrading expo SDK to v43

### ISSUE THREAD

**Issue by Marian0** [expo/sentry-expo#221]
### Summary

When running `expo start`  I get a warning message on the console:

```
Constants.deviceYearClass has been deprecated in favor of expo-device's Device.deviceYearClass property. This API will be removed in SDK 45.
at node_modules/@sentry/utils/dist/instrument.js:111:20 in <anonymous>
at node_modules/expo-constants/build/Constants.js:56:12 in constantsPropertiesGetter.deviceYearClass
at node_modules/sentry-expo/build/integrations/managed.js:61:47 in DEFAULT_EXTRAS.forEach$argument_0
at node_modules/sentry-expo/build/integrations/managed.js:59:8 in ExpoManagedIntegration#setupOnce
at node_modules/@sentry/core/dist/integration.js:46:4 in setupIntegration
at node_modules/@sentry/core/dist/integration.js:61:24 in getIntegrationsToSetup.forEach$argument_0
at node_modules/@sentry/core/dist/integration.js:59:4 in setupIntegrations
at node_modules/@sentry/core/dist/baseclient.js:155:33 in BaseClient.prototype.setupIntegrations
at node_modules/@sentry/hub/dist/hub.js:58:12 in Hub.prototype.bindClient
at node_modules/@sentry/core/dist/sdk.js:19:4 in initAndBind
at node_modules/@sentry/react-native/dist/js/sdk.js:75:4 in init
at node_modules/sentry-expo/build/sentry.js:98:15 in init
at src/components/AppBootstrap/AppBootstrap.tsx:21:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at src/index.tsx:5:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at App.tsx:1:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/expo/AppEntry.js:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:201:44 in guardedLoadModule
at http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:171628:3 in global code
```

Any ideas how to fix it ?

Thanks

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

  Expo CLI 4.12.11 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28, 29, 30
        Build Tools: 23.0.1, 25.0.2, 25.0.3, 26.0.2, 27.0.3, 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0
        System Images: android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7621141
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 43.0.1
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.2 => 0.64.2
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      expo-cli: 4.12.11
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

I didn't try to reproduce this in a new project but I see that commenting the sentry init the warning disappears, this is how i'm initializing it:

//.....
import * as Sentry from "sentry-expo";
//.....

Sentry.init({
  dsn: "url",
  enableInExpoDevelopment: true,
  debug: true,
  environment: getEnvironment().name,
});

**Comment by day-me-an** [comment]
Fix is here https://github.com/expo/sentry-expo/pull/220

**Comment by Bruno02** [comment]
Hello,
Is there anyone to review this fix ?
It is not blocking to use expo sentry but could be fine to remove this warning popping all the time in dev mode :)

Thanks a lot,

Cheers

**Comment by cruzach** [comment]
fixed in https://github.com/expo/sentry-expo/commit/19a5a0a9a36c97ab4db79ffb0c9c668489c6451d, will release sentry-expo4.0.5 as `next` today

**Comment by cruzach** [comment]
released in `sentry-expo@next` (v4.0.5)

**Comment by Marian0** [comment]
Thank you! Now it's working without warning messages on (v4.0.5).

**Comment by audrew** [comment]
Constants.deviceYearClass has been deprecated in favor of expo-device's Device.deviceYearClass property. This API will be removed in SDK 45. How to fix this warning?

**Comment by NastuzziSamy** [comment]
@audrew , you just need to upgrade to next version. Either with:
`yarn upgrade sentry-expo@next`
or
`yarn upgrade sentry-expo@4.0.5`

**Comment by Saviourise** [comment]
> @audrew , you just need to upgrade to next version: `yarn upgrade sentry-expo@next`

Worked like a charm, thanks
