### ISSUE TITLE
Error: SentryError: Native Client is not available, can't start on native with Custom Development Client

### ISSUE THREAD

**Issue by Borduhh** [expo/sentry-expo#222]
### Summary

When loading a custom dev client, we get the following error:

```
Sentry Logger [Error]: Error while triggering instrumentation handler.
Type: console
Name: callback
Error: SentryError: Native Client is not available, can't start on native.
at node_modules/@sentry/utils/dist/logger.js:90:12 in consoleSandbox$argument_0
at node_modules/@sentry/utils/dist/logger.js:32:25 in consoleSandbox
at node_modules/@sentry/utils/dist/logger.js:89:22 in Logger.prototype.error
at node_modules/@sentry/react/node_modules/@sentry/utils/dist/instrument.js:81:16 in triggerHandlers
at node_modules/@sentry/react/node_modules/@sentry/utils/dist/instrument.js:108:31 in <anonymous>
at node_modules/sentry-expo/build/sentry.js:103:12 in init
at src/App.tsx:55:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at index.js:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:201:44 in guardedLoadModule
at http://192.168.1.156:8081/index.bundle?platform=ios&dev=true&hot=false&minify=false:425623:3 in global code
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

43

### Environment

```
Expo CLI 4.12.12 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - /usr/local/bin/node
      npm: 8.1.2 - /opt/homebrew/bin/npm
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 43.0.2 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: ^0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.12.12
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

App.tsx
```ts
import { init as SentryInit } from 'sentry-expo';

// Init Sentry error reporting
SentryInit({
  dsn: 'https://fabd7602f75e4eae8d1cae1c3d489444@o963056.ingest.sentry.io/6058706',
  enableInExpoDevelopment: ENVIRONMENT.NODE_ENV === 'dev' ? true : false,
  debug: ENVIRONMENT.NODE_ENV === 'dev' ? true : false,
});

```

app.config.js
```js
export default {
  plugins: [
    [
      '@stripe/stripe-react-native',
      {
        merchantIdentifier: [],
        enableGooglePay: false,
      },
    ],
    'sentry-expo',
  ],
  hooks: {
    postPublish: [
      {
        file: 'sentry-expo/upload-sourcemaps',
        config: {
          organization: 'xxx',
          project: 'xxx',
          authToken: 'xxx',
        },
      },
    ],
  },
};
```

eas.json
```
    "dev": {
      "android": {
        "buildType": "apk"
      },
      "ios": {
        "image": "latest"
      },
      "developmentClient": true,
      "distribution": "internal",
      "releaseChannel": "dev",
      "cache": {
        "key": "2021-11-04"
      }
    }
```

We are using a custom dev client which lead us to : 
1. Add `sentry-expo` as a plugin (derived from https://github.com/expo/sentry-expo/issues/216#issuecomment-948861440).
2. Rebuild our dev clients using `eas build`

**Comment by bpmct** [comment]
Running into the same thing. I have looked at all the past docs and issues and still have no idea what to do. I'm just using Expo Go and hoping to use `routingInstrumentation`. When I comment it out, it works fine.

**Comment by mcavaliere** [comment]
I'm running into this on a bare workflow, but on iOS only. I don't have the sentry-expo plugin in app.json, but have run the sentry wizard and it has updated my native modules. 

Expo version is ^42.0.1.

**Comment by naraB** [comment]
We are also running into the same thing. Is this a known issue?

**Comment by mvincent7891** [comment]
I'm running into the same. Followed all steps in setup and just trying to send an event in local development.

expo 43.0.3
sentry-expo 4.0.0

```
Sentry Logger [Error]: Error while triggering instrumentation handler.
Type: console
Name: callback
Error: SentryError: Native Client is not available, can't start on native.
```

**Comment by Justinohallo** [comment]
Currently running into same issue. It has to do with routingInstrumentation. When I include it, sentry fails as mentioned above.

**Comment by eladgoeuro** [comment]
Running into the same issue, any updates?
expo ^44.0.0
sentry-expo 4.0.0

**Comment by jnoleau** [comment]
`sentry-expo` now requires dependencies like `@sentry/react-native` (see the docs https://docs.expo.dev/guides/using-sentry/#step-1-installation) , after install it and rebuild the dev-client, sentry is not failing anymore. 

NB : Before install it,  I run into this issue only in the custom dev build and I found this thread. Production build works without but I don't know why exactly !

**Comment by hbriese** [comment]
Encountered this issue after adding `ReactNativeTracing` and fixed it by using the direct init export from 'sentry-expo'
```ts
import { Native, init } from 'sentry-expo';

 // Errors
Native.init(...) 

// Works
init(...)  
```

**Comment by rahmanharoon** [comment]
Any solution for this issue?

**Comment by LuizHGodoy** [comment]
i run into this now with expo

**Comment by claudesortwell** [comment]
@LuizHGodoy @rahmanharoon Not sure if you fixed your issue but removing: 

`enableInExpoDevelopment: false` 

in my init call worked for me.
