### ISSUE TITLE
Error: Unable to resolve module react-native/Libraries/promiseRejectionTrackingOptions

### ISSUE THREAD

**Issue by LFMAKER** [expo/sentry-expo#224]
### Summary

Hello everyone, I have a problem with this lib, I noticed that this week when I went to run a project in a working version, the following problem occurred and my app crashed.

ERROR:

`error: bundling failed: Error: Unable to resolve module react-native/Libraries/promiseRejectionTrackingOptions from node_modules/@sentry/react-native/dist/js/integrations/reactnativeerrorhandlers.js: react-native/Libraries/promiseRejectionTrackingOptions could not be found within the project.
`
I got this only in RELEASE mode

I noticed this was reported in the sentry-react-native lib
https://github.com/getsentry/sentry-react-native/issues/1922

They released a release that fixed it, and in fact it looks ok if you run the .init with their lib.

However if I run with this lib, the above problem occurs.

I forked this project(sentry-expo) and released a temporary lib to try and analyze the problem.
https://github.com/LFMAKER/sentry-expo
I was able to run my app only after the lib of sentry-expo had the following dependencies:

   ```
 "@expo/config-plugins": "^2.0.2",
    "@expo/config-types": "^41.0.0",
    "@expo/spawn-async": "^1.2.8",
    "@sentry/browser": "6.12.0",
    "@sentry/integrations": "6.12.0",
    "@sentry/react-native": "3.2.3",
    "@sentry/types": "6.12.0",
    "mkdirp": "^1.0.3",
    "rimraf": "^2.6.1"
```

So, this library is probably having problems running with the latest version of the following libraries:
    "@sentry/integrations",
    "@sentry/react-native",

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS and Android

### SDK Version (managed workflow only)

v42.0.0

### Environment

  Expo CLI 4.12.8 environment info:
    System:
      OS: macOS 11.5.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
      Watchman: 2021.10.11.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 23, 28, 29, 30
        Build Tools: 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.0, 30.0.2
        System Images: android-25 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.5 
      react: 17.0.2 => 17.0.2 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.66.3 => 0.66.3 
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

- Init a bare react native project in version 0.66.3
- Add support to expo
- Add expo-sentry
- Setup expo-sentry with init in this project
- Try to do a build in release mode in IOS and Android.

**Comment by johnsoncwb** [comment]
hey, i got this same issue on my project when i try to build iOS version (Release)
using here:
React-native : 0.63.1
@sentry/react-native: "^3.1.1"
sentry-expo: "^4.0.3"

**Comment by LFMAKER** [comment]
@johnsoncwb can you test my fork with old dependencies and see if it works there?

**Comment by johnsoncwb** [comment]
@LFMAKER i tried your fork here and works perfectly! 
<img width="1381" alt="Screen Shot 2021-12-03 at 21 16 24" src="https://user-images.githubusercontent.com/80973949/144688735-4c13faf1-20a5-4933-9d96-e4b4a6cb4d8f.png">

**Comment by LFMAKER** [comment]
https://github.com/getsentry/sentry-react-native/pull/1928

**Comment by LFMAKER** [comment]
https://github.com/getsentry/sentry-react-native/pull/1928

Fixed it
