### ISSUE TITLE
Sentry is not sending global errors

### ISSUE THREAD

**Issue by mfru** [expo/sentry-expo#23]
So I have tried to install Sentry as specified in the Expo section for Sentry / Sentry section for Expo.

My App.js contains the Sentry import, I enabled it in development and called `Sentry.config(<MyPublicDSN>).install()`.

When trying to throw a test error like so: `throw new Error("TestError)`, Sentry does not pick up on it, even though the application crashes as expected. 

However, using `Sentry.captureException(new Error("TestError")` yields the expected results. 

Am I missing something?

EDIT: I also tried reloading the app (as it is stated that errors will get reported on next startup) a few times in the meantime, but it is not sending then either.

**Comment by saleemjaffer** [comment]
@mfru You have closed this issue. Is the issue solved?

**Comment by mfru** [comment]
I don't know if it is my fault or sentry-expos, but when running in prod mode, Errors get indeed reported while in dev mode it seems to not report everything (some errors yes, some not). 

I closed the issue, because it kind of is resolved for me.

**Comment by saleemjaffer** [comment]
@mfru Thanks.

**Comment by andresespinosapc** [comment]
I'm having the same problem but it is not working even on production. I have tried using `Sentry.config('DSN', { logLevel: 3 }).install();` to have more information of the Raven process, but it doesn't log anything when I throw an error, it only log if I run explicitly `Sentry.captureException`.

**Comment by freeall** [comment]
I get the same. I only see errors in production if I explicitly call `Sentry.captureException`.

**Comment by andresespinosapc** [comment]
In my case, the problem was because of using a different entry point than the expo’s default. I imported an index.js from App.js. Moving the index.js content to App.js solved the problem.

**Comment by summerkiflain** [comment]
Using above method and ```Sentry.enableInExpoDevelopment = true```, I am able to log errors from local env, but its not working for me in production, i have published my changes and using sentry-expo v1.13.0.

**Comment by AdamGerthel** [comment]
Same problem for me - I'm initiating Sentry in App.js right after module imports, and it still never catches fatal errors, only those that I explicitly call using `Sentry.captureException` are sent to Sentry.
