### ISSUE TITLE
SentryError: Native is disabled

### ISSUE THREAD

**Issue by annasychugina** [expo/sentry-expo#230]
### Summary

I have installed @sentry/react-native and added in plugins `'sentry-expo' `according to guide https://docs.expo.dev/guides/using-sentry/

When I use Sentry.Native.* methods (Sentry.Native.crash, captureExeption and etc), I get error:

```
[Unhandled promise rejection: SentryError: Native is disabled]
at http://127.0.0.1:19000/src/index.mobile.ts.bundle?platform=ios&dev=true&hot=false&minify=false:233787:25 in new SentryError
at node_modules/sentry-expo/node_modules/@sentry/react-native/dist/js/wrapper.js:10:22 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:4 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:210:11 in guardedLoadModule
at node_modules/metro-runtime/src/polyfills/require.js:128:6 in metroRequire
at http://127.0.0.1:19000/src/index.mobile.ts.bundle?platform=ios&dev=true&hot=false&minify=false:246107:17 in <unknown>
at node_modules/metro-runtime/src/polyfills/require.js:349:4 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:210:11 in guardedLoadModule
at node_modules/metro-runtime/src/polyfills/require.js:128:6 in metroRequire
at http://127.0.0.1:19000/src/index.mobile.ts.bundle?platform=ios&dev=true&hot=false&minify=false:246073:28 in <unknown>
```

Related issues: [226](https://github.com/expo/sentry-expo/issues/216)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

```
  Expo CLI 4.5.2 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.17.6 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.2 => 43.0.2 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.5.2
    Expo Workflow: managed

```

### Reproducible demo or steps to reproduce from a blank project

Happens consistently after using this library

**Comment by maticzav** [comment]
Is there any progress with this issue or at least a suggested an alternative approach to adding Sentry to our Expo projects?

**Comment by mprevdelta** [comment]
> I experienced the same issue using SDK 44 after migrating from the classic build to EAS just recently. Sentry seemed not to be linked into the build as it would not show up in the logs from EAS.
> 
> I added `"@sentry/react-native": "^3.2.13"` to my project's package.json, executed yarn install and created a new build using EAS. Now Sentry would be linked correctly so I assume there is some kind of linking issue with the @sentry/react-native version which is currently used by sentry-expo.
> 
> After a quick test with the development client on iOS it seems `Sentry.Native.capture*()` as well as `Sentry.Native.setUser()` would all work perfectly fine again with this setup. I haven't tested it extensively or in a production build yet though, so I can't say for sure that there are no compatibility issues.

I experienced this issue too and realized I was missing that addition to package.json. The docs do state it but it's kinda unexpected that we'd need to add this dependency by hand.  The docs state:

"
sentry-expo requires some additional dependencies, so you should also run:
 'expo install expo-application expo-constants expo-device expo-updates @sentry/react-native'
"

**Comment by calebcarithers** [comment]
still seeing this issue running 
`
@sentry/react-native@^4.1.3
expo@^46.0.0
sentry-expo@~5.0.0
`

reproducible example here [https://github.com/calebcarithers/test-sentry](https://github.com/calebcarithers/test-sentry)

steps to reproduce
1: `yarn`
2: `yarn ios`
3: Click 'crash' button 

<img width="989" alt="Screen Shot 2022-08-10 at 12 08 40" src="https://user-images.githubusercontent.com/26444558/183962518-f7d942bd-3a7a-41d2-bcdd-1fdf7317a16f.png">

**Comment by kbrandwijk** [comment]
`yarn ios` will load your app in Expo Go. While Sentry works for JS errors, `@sentry/react-native` has native dependencies, so this requires you to create a development build to be able to use native crash reporting. A note about that is also in the docs here: https://docs.expo.dev/guides/using-sentry/, so this warning is expected in Expo Go.
![image](https://user-images.githubusercontent.com/852069/183966459-1f9f221f-5e09-4103-b5c2-a6f05db0871f.png)

**Comment by calebcarithers** [comment]
Ah okay - understood - thanks @kbrandwijk

**Comment by calebcarithers** [comment]
> 

@kbrandwijk is there a recommendation for getting crash reports while using Expo Go? Attempting to log crashes while testing via EAS Update previews

**Comment by bit-void** [comment]
@kbrandwijk is there a recommended way to test this locally with expo go?
