### ISSUE TITLE
npm registry displays 4.0.3 as recent version, but 4.0.5 is released already

### ISSUE THREAD

**Issue by n0mer** [expo/sentry-expo#232]
### Summary

https://www.npmjs.com/package/sentry-expo

![image](https://user-images.githubusercontent.com/1862997/149672182-c6461561-f22e-46e9-b15d-743cbe6ee0cf.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

44

### Environment
```
  Expo CLI 5.0.3 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.17.6 - C:\projects\externals\nodejs\node.EXE
      Yarn: 1.22.11 - C:\projects\externals\nodejs\yarn.CMD
      npm: 6.14.15 - C:\projects\externals\nodejs\npm.CMD
      Watchman: 20210110.135312.0 - c:\projects\externals\watchman-v2021.01.11.00-windows\bin\watchman.EXE
    SDKs:
      Android SDK:
        API Levels: 29, 30, 31
        Build Tools: 29.0.2, 30.0.2, 31.0.0
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64
        Android NDK: 22.1.7171670
    npmPackages:
      babel-preset-expo: 9.0.2 => 9.0.2
      expo: 44.0.5 => 44.0.5
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.66.4 => 0.66.4
      react-native-web: 0.17.5 => 0.17.5
    Expo Workflow: bare
```
### Reproducible demo or steps to reproduce from a blank project

https://www.npmjs.com/package/sentry-expo

**Comment by n0mer** [comment]
https://github.com/expo/sentry-expo/commit/f28c68439af249a620e323d8d971fcbfc68496a2 - Nov 23, 2021 release for 4.0.5

**Comment by pweisensee** [comment]
@brentvatne @quinlanj Any update on this issue? Is this library still maintained up-to-date on `npm`? It seems like [its months out of date](https://www.npmjs.com/package/sentry-expo)

**Comment by brentvatne** [comment]
@pweisensee - updated latest to 4.0.5. @cruzach doesn't work at expo anymore so i'm not totally sure on the context of why this wasn't promoted, sorry!
