### ISSUE TITLE
Sentry wrap app not working 

### ISSUE THREAD

**Issue by tnandwani** [expo/sentry-expo#234]
### Summary

Getting the error: 
`Cannot read properties of undefined (reading 'wrap')` 

App is actually sending crash report to expo- but App is not showing 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

^43.0.0

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.10.0 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 7.24.2 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 43.0.4 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Create expo react app 

`export default function App() {

  return (
    <Provider store={store}>
      <AppContent />
    </Provider>
  );
}

Sentry.Native.wrap(App);
`

works great on iOS. not working on web. I believe it because it root component is not defined before the wrap is called. however root definition is in the build

**Comment by tnandwani** [comment]
figured out i need to use Sentry.Browser.wrap for web. Would be helpful to include in documentation on Expo.io

**Comment by curtcox** [comment]
@tnandwani Can you post or point me toward a more complete working example? I'm having the same issue.

**Comment by felipecsl** [comment]
```typescript
import * as Sentry from "sentry-expo";
Sentry.init({ ... });
function App() {
  return (<>
    your app here
  </>);
}
export default Sentry.Native.wrap(App);
```
