### ISSUE TITLE
No bugs are reported with enableNative: false

### ISSUE THREAD

**Issue by RRaideRR** [expo/sentry-expo#235]
### Summary

When setting enableNative: false in Sentry.init() no bugs will be reported towards Sentry with the initial app version. However, after an expo OTA update everything works fine.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

44

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.1 - /opt/homebrew/opt/node@14/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 6.14.13 - /opt/homebrew/opt/node@14/bin/npm
      Watchman: 2021.12.13.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.46.0
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1. I setup Sentry exactly like on this page: https://docs.expo.dev/guides/using-sentry/

2. I set `enableNative` to `false` on Sentry.init
`Sentry.init({
  dsn: 'XXXXX',
  enableInExpoDevelopment: false,
  debug: false, 
  enableNative: false,
});`

3. I use a custom URL in my Sentry settings (postPublishHook).

4. I use EAS build to build an Android/iOS version of the following repro: https://github.com/RRaideRR/expo-sentry-test

5. I force an error - nothing get's reported.

However, with enableNative: true, everything works as expected. It seems that after using an expo OTA update, everything works also as expected.

**Comment by yashSangai** [comment]
Same issue here
