### ISSUE TITLE
Adding plugin to app.config.js causes an error with eas cli

### ISSUE THREAD

**Issue by Jamesking56** [expo/sentry-expo#239]
### Summary

I've installed sentry-expo following the guide on Expo's docs.

When I add the line `sentry-expo` into `plugins` in my `app.config.js` file (dynamic config) and run `eas submit --platform ios` I get the following error:

```
    AssertionError: Wrong number of arguments provided for static config plugin, expected either 1 or 2, got 3
    Code: ERR_ASSERTION
```

If I remove the plugin line, the CLI works as normal.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

`expo diagnostics` only runs without the plugin line, so here it is:

```
  Expo CLI 5.2.0 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      npm: 8.1.4 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.67.2 => 0.67.2 
      react-native-web: 0.17.6 => 0.17.6 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.2.0
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

I don't think a Snack will allow you to test `eas submit` so might be a little difficult for me to get a reproducible demo

**Comment by Jamesking56** [comment]
It does work, I wasn't adding the config in the right spot in my config file

**Comment by pradeipp** [comment]
Hi @Jamesking56 , where is the "right spot" to add it? I'm facing the same issue while adding any more than 2 config plugins.

**Comment by Jamesking56** [comment]
@pradeipp It was quite misleading so to make it easier I made a `plugins` variable in my config file:

```js
  let plugins = [
    [
      'expo-facebook',
      {
        userTrackingPermission: false,
      },
    ],
    [
      'expo-image-picker',
      {
        photosPermission:
          'The app accesses your photos to let you upload a profile picture.',
      },
    ],
  ];
  if (process.env.SENTRY_DSN && process.env.SENTRY_DSN.length > 0) {
    plugins.push(['sentry-expo']);
  }
```

And then used it:

```
...
plugins: plugins,
...
```

**Comment by Erbel-jay** [comment]
@pradeipp where is your config file located?

**Comment by jaypee-0** [comment]
mine's in app.json
Try editing it there and it would work

**Comment by cabmeron** [comment]
thanks, I ran into this issue when I put

 "expo-build-properties",
        {
          "ios": {
            "useFrameworks": "static"
          }
        }


into my app.json
