### ISSUE TITLE
Huge build size

### ISSUE THREAD

**Issue by BrodaNoel** [expo/sentry-expo#244]
### Summary

I just ran `npx react-native-bundle-visualizer` in order to analyze the bundle size of my app, and I just realized that sentry is 25% of my `node_modules`.

Take a look at the Top Right corner (sentry-expo and @sentry)
<img width="1436" alt="Screen Shot 2022-03-15 at 11 38 28" src="https://user-images.githubusercontent.com/1837969/158402298-5f24c132-b567-42d6-ac9a-7a12c759653d.png">

Why does Sentry contains a react-native dependency inside, instead of using the peerDependency?

`react-native` size is 655kb, and `sentry-expo` size is 363kb and `@sentry` size is 142kb.
Seems like sentry-expo + @sentry, are soon going to get even bigger than react-native.

Does this makes sense? Or is my react-native-bundle-visualizer that is getting crazy?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

43

### Environment

```
  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 11.6.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 8.3.2 - ~/.nvm/versions/node/v14.18.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 27, 29, 30
        Build Tools: 23.0.1, 23.0.3, 25.0.3, 26.0.1, 27.0.3, 28.0.3, 29.0.2
        System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 43.0.1
      react: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
    npmGlobalPackages:
      eas-cli: 0.48.0
      expo-cli: 5.3.0
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

On any project with sentry-expo, run `npx react-native-bundle-visualizer` in order to see the bundle size

**Comment by matthewford** [comment]
Any chance we can get an on this?

**Comment by danshilm** [comment]
Looking at that the visualisation, that's not the `react-native` package that you're probably referring to under the `@sentry` heading. Those are just all the `@sentry/<package name>` packages; that one in particular being `@sentry/react-native` and not the `react-native` package.
