### ISSUE TITLE
Invalid Bundle - App Store Connect

### ISSUE THREAD

**Issue by adaryabegi** [expo/sentry-expo#245]
### Summary

Hey all!

I wanted to add a bug report tool to my fully expo managed app. I saw there is a tool called sentry and also for expo! Great!
So I followed the instructions on these docs: https://docs.expo.dev/guides/using-sentry/
I followed everything until step 3 and it seemed to work, since I saw the errors in the dashboard. Till now all good.

Now I build the app with: `eas build -p ios` which worked!
After that I wanted to submit the app to App Store Connect: `eas submit -p ios` also worked!
But then I got an email from Apple where they reviewed my app and they said:

**ITMS-90562: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.**

**ITMS-90562: Invalid Bundle - There's an issue with the app's bitcode compilation. Rebuild the app using the current public (GM) version of Xcode and upload it again.**

Before that everything worked fine, after I added sentry I got this error.

I dont know what I can do? Please help!?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
      Watchman: 2022.02.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/armin/.rvm/rubies/ruby-2.7.1/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 23, 28, 29, 30
        Build Tools: 28.0.3, 30.0.1, 30.0.2
        System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project
```javascript
# App.js

import * as Sentry from "sentry-expo"

Sentry.init({
  dsn: "<DSN>",
  enableInExpoDevelopment: true,
  debug: true
})
```
```json
# app.json
"plugins": ["sentry-expo"],
 "hooks": {
   "postPublish": [
     {
       "file": "sentry-expo/upload-sourcemaps",
       "config": {
         "organization": "<organization-slug>",
         "project": "<project>",
         "authToken": "<auth token>"
       }
     }
   ]
 }
```

**Comment by app-arianamini** [comment]
This is an Apple/ Xcode bug. https://developer.apple.com/forums/thread/701949
