### ISSUE TITLE
User string treated as array when submitting Sentry messages

### ISSUE THREAD

**Issue by yolpsoftware** [expo/sentry-expo#250]
### Summary

Our app is using Expo, and we use `sentry-expo` version `4.1.1`.

This is how we set the user:

```
const sentry = require("sentry-expo").Native;
sentry.setUser(userId);
```

This is how the user is displayed in the Sentry dashboard:

![image](https://user-images.githubusercontent.com/1302357/164412073-61516fc4-e527-4b98-8d7d-9b0e1c3167e7.png)

Seems somewhere the user string is treated as an array of single characters.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

```

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.8.0 - /opt/homebrew/bin/node
      Yarn: 1.22.18 - /opt/homebrew/bin/yarn
      npm: 8.5.5 - /opt/homebrew/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.49.0
      expo-cli: 5.3.1
    Expo Workflow: managed

```

### Reproducible demo or steps to reproduce from a blank project

* Setup a blank Expo app.
* Add sentry-expo as described in the [docs](https://docs.expo.dev/guides/using-sentry/).
* Call `sentry.setUser("my User")`
* Submit a message or error to Sentry

Look up the user string in the message.

**Comment by yolpsoftware** [comment]
Oh yes this helps, thanks!

I leave the ticket open because I still think this is a bug. `sentry-expo` should either warn the user that they should submit an object, or accept strings as well.

**Comment by kbrandwijk** [comment]
All methods in `Native` are just exposed methods from `@sentry/react-native`, so feel free to open an issue in their repo to have this addressed. This is unfortunately out of our control.
