### ISSUE TITLE
eas build --local failing, remote is fine

### ISSUE THREAD

**Issue by erisvaldojunior** [expo/sentry-expo#257]
### Summary

Error happens only on eas build --local , eas build remotely works fine and Sentry is working properly.

[RUN_FASTLANE] ▸ 	PhaseScriptExecution Upload\ Debug\ Symbols\ to\ Sentry /Users/erisvaldojunior/Library/Developer/Xcode/DerivedData/TestProject-bkvxhzoibuawapfepgnwbuzutbag/Build/Intermediates.noindex/ArchiveIntermediates/TestApp/IntermediateBuildFilesPath/TestApp.build/Debug-iphoneos/TestApp.build/Script-DCEECFB20F5D44BA927830C2.sh (in target 'TestProject' from project 'TestProject')

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.2 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.5.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.3 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.6
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1. Start an expo project (managed workflow), install sentry and use EAS for building
2. eas build -p ios --profile development (remote) works fine, but eas build -p ios --profile development --local gives the error

**Comment by NERO2k** [comment]
Pretty sure i had the same issue as you, very hard to tell but otherwise just check the contents of the .sh file displayed in the error and start digging from there. Myself I had to install the sentry cli locally, you can do that here. https://docs.sentry.io/product/cli/installation/

**Comment by grossadamm** [comment]
Do you have your sentry auth token as a secret on was but not set on the local env? I've done that...

**Comment by erisvaldojunior** [comment]
Hi guys, digging into the .sh file I found this is the error:

error: An organization slug is required (provide with --org)

How are you guys passing organization slug for EAS local builds?

**Comment by NERO2k** [comment]
You can pass it via environment variables, example.

```
export SENTRY_AUTH_TOKEN=123123123
export SENTRY_PROJECT=123123123
export SENTRY_ORG=123123123
```

You can find all of them here
https://docs.sentry.io/product/cli/configuration/

**Comment by erisvaldojunior** [comment]
@NERO2k thanks man, that was it. After including the missing env variables (project and org) I'm still getting another sentry-related error on the same phase though:

```
[RUN_FASTLANE] › Generating debug TestApp » TestApp.app.dSYM
[RUN_FASTLANE] ▸ ** ARCHIVE FAILED **
[RUN_FASTLANE] ▸ The following build commands failed:
[RUN_FASTLANE] ▸ 	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/erisvaldojunior/Library/Developer/Xcode/DerivedData/TestApp-ekmgnvutdarnnjfkczoaukqzwfov/Build/Intermediates.noindex/ArchiveIntermediates/TestApp/IntermediateBuildFilesPath/TestApp.build/Release-iphoneos/TestApp.build/Script-00DD1BFF1BD5951E006B06BC.sh (in target 'TestApp' from project 'TestApp')
[RUN_FASTLANE] ▸ (1 failure)
[RUN_FASTLANE] 2022-07-01 16:55:42.275 xcodebuild[46673:10247115] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
[RUN_FASTLANE] 2022-07-01 16:55:42.276 xcodebuild[46673:10247115] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
[RUN_FASTLANE] ** ARCHIVE FAILED **
[RUN_FASTLANE] 
[RUN_FASTLANE] 
[RUN_FASTLANE] The following build commands failed:
[RUN_FASTLANE] 	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/erisvaldojunior/Library/Developer/Xcode/DerivedData/TestApp-ekmgnvutdarnnjfkczoaukqzwfov/Build/Intermediates.noindex/ArchiveIntermediates/CurebaseDev/IntermediateBuildFilesPath/TestApp.build/Release-iphoneos/TestApp.build/Script-00DD1BFF1BD5951E006B06BC.sh (in target 'TestApp' from project 'TestApp')
```

By doing sh <pathToShFileAbove> I got:

```
error: Need to run this from Xcode

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

```

And this is the mentioned .sh file content:

```
#!/bin/sh
export SENTRY_PROPERTIES=sentry.properties
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"
export NODE_BINARY=node

# The project root by default is one level up from the ios directory
export PROJECT_ROOT="$PROJECT_DIR"/..

`node --print "require.resolve('@sentry/cli/package.json').slice(0, -13) + '/bin/sentry-cli'"` react-native xcode --force-foreground `node --print "require('path').dirname(require.resolve('react-native/package.json')) + '/scripts/react-native-xcode.sh'"`

```

Any thoughts on solving this?
