### ISSUE TITLE
Sentry does not send events on production build using EAS

### ISSUE THREAD

**Issue by georgiosd** [expo/sentry-expo#259]
### Summary

Sentry.capture* throws an exception with message "Native module not found" on iOS builds only (following a successful build through EAS).

This is in a monorepo setup (https://docs.expo.dev/guides/monorepos/) and related packages versions are:

```
"@sentry/react-native": "^3.4.3",
"expo-application": "~4.0.0",a
"expo-constants": "~12.1.3",
"expo-device": "~4.0.3",
"sentry-expo": "^4.2.0"
```

Everything works perfectly on development mode (running expo locally) and Android build. Any clues or ideas?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.15.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.5.5 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.4 => 43.0.5 
      react-native: 0.64.3 => 0.64.3 
    npmGlobalPackages:
      eas-cli: 0.53.0
      expo-cli: 5.4.7
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Not Available but can perhaps provide one although an actual build will be needed and test on an actual device.

**Comment by bmikaili** [comment]
Same issue. This is breaking for us and a reason to eject / not use Expo.

**Comment by jameswilddev** [comment]
I can reproduce this; while `Sentry.Native.captureException` DOES send events under Expo Go and when built using Turtle/classic builds, it does not send anything when the exact same app is built using EAS.

Anyone know if there are any plans to keep Turtle going?  The migration to EAS has been painful and largely unsuccessful for the most trivial of apps.

**Comment by ShaneBurkhart** [comment]
we've had the same experience with our transition to EAS. can't get sentry to work at the moment.

**Comment by georgiosd** [comment]
I am amazed that there is no official response on this

**Comment by erikhSSI** [comment]
Maybe fixed here? https://github.com/expo/sentry-expo/pull/302

**Comment by ShaneBurkhart** [comment]
i wrote a python script that builds and uploads sourcemaps.

```python
#!/usr/bin/env python3
import os

IOS_PACKAGE_NAME = ""
PROJECT_NAME = ""
ORG_NAME = ""

# list the files in ./dist/bundles
build_command = "NODE_ENV=production npx -y eas-cli update -p ios --branch production --auto 2>&1 | tee build.log"
# build_command = "NODE_ENV=production npx -y eas-cli update -p ios --branch development --message 'update' 2>&1 | tee build.log"
print("build_command: " + build_command)

# run the build command, capture the output as it comes in
os.system(build_command)
output = os.popen("cat build.log").read()
# parse the output for the iOS update ID
update_id = output.split("iOS update ID")[1].split("\n")[0].strip()
print("iOS update ID: " + update_id)

# get the name of the file in ./dist/bundles that matches *.map
filename = os.popen("ls dist/bundles | grep map").read().strip()
print("filename: " + filename)

# read ./app.json and get the version number
version = os.popen("cat app.json | grep version | cut -d '\"' -f 4").read().strip()
print("version: " + version)

# copy the .js file to main.jsbundle
js_filename = filename.replace(".map", ".js")
os.system("cp dist/bundles/{} dist/bundles/main.jsbundle".format(js_filename))

command = "npx sentry-cli releases --org {} -p {} files {}@{}+1 upload-sourcemaps --dist {} --rewrite dist/bundles/main.jsbundle dist/bundles/{}".format(ORG_NAME, PROJECT_NAME, IOS_PACKAGE_NAME, version, update_id, filename)
print("command: " + command)

# run the command
source_output = os.popen(command).read()
print(source_output)
```

**Comment by javascripter** [comment]
I wrote the below GitHub Action steps. Unfortunately I needed to drop automatic build version increment functionality to make it work.

```yaml
      - name: 🚀 EAS Update
        uses: expo/expo-github-action/preview@v8
        id: eas-update
        with:
          working-directory: ./apps/xxx
          command: eas update --branch XXX --auto
          comment: false
          github-token: ${{ secrets.GH_PAT }}

      - name: 🚀 Upload Sourcemaps to Sentry
        working-directory: ./apps/xxx
        run: |
          # https://docs.expo.dev/guides/using-sentry/#uploading-source-maps-for-updates
          organizationName="XXX" # From sentry
          projectName="XXX" # From sentry
          version="1.0.0" # You can do something like "jq '.expo.version' < app.json"

          # iOS
          iosBuildNumber="1"
          iosBundleIdentifier="com.example.xxx"
          iosUpdateId="${{ steps.eas-update.outputs.iosId }}"

          cp dist/bundles/ios-*.js dist/bundles/main.jsbundle

          npx -y sentry-cli releases \
            --org ${organizationName} \
            --project ${projectName} \
            files ${iosBundleIdentifier}@${version}+${iosBuildNumber} \
            upload-sourcemaps \
            --dist ${iosUpdateId} \
            --rewrite \
            dist/bundles/main.jsbundle dist/bundles/ios-*.map

          # Android
          androidPackage="com.example.xxx"
          androidVersionCode="1"
          androidUpdateId="${{ steps.eas-update.outputs.androidId }}"

          cp dist/bundles/android-*.js dist/bundles/index.android.bundle

          npx -y sentry-cli releases \
            --org ${organizationName} \
            --project ${projectName} \
            files ${androidPackage}@${version}+${androidVersionCode} \
            upload-sourcemaps \
            --dist ${androidUpdateId} \
            --rewrite \
            dist/bundles/index.android.bundle dist/bundles/android-*.map
```
