### ISSUE TITLE
Installing sentry-expo clears all plugins in app.json

### ISSUE THREAD

**Issue by itsramiel** [expo/sentry-expo#261]
### Summary

I am adding sentry-expo. Instead of appending the config plugin of sentry-expo to the list of config plugins, it is wiping out all other config plugins and just adding sentry-expo's plugins.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

45

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-212.5712.43.2112.8609683
    npmPackages:
      expo: ^45.0.0 => 45.0.4
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

Just add some config plugins prior to installing sentry-expo using `expo install sentry-expo`.  You will see that other config plugins were removed.

**Comment by kbrandwijk** [comment]
This was an issue in `expo-cli` with the `expo install` command, which has since been resolved (see linked PR).
