### ISSUE TITLE
Problem - Sentry performance - TypeError: undefined is not an object (evaluating 'this._navigation.events')

### ISSUE THREAD

**Issue by AmineMed95** [expo/sentry-expo#272]
### Summary

Hello, I'm setting up Sentry performance monitoring in my react native Expo project, but I have the following problem

![unknown (1)](https://user-images.githubusercontent.com/108055010/179967116-bcb1ea85-6d0b-40ad-8bcd-f0b7f6c841b5.png)
![unknown (2)](https://user-images.githubusercontent.com/108055010/179967119-5771c7c5-d6ef-43b2-8694-98492c921fa6.png)
![unknown (3)](https://user-images.githubusercontent.com/108055010/179967121-b1d84d04-a047-44e1-9b54-fca413661553.png)
![unknown](https://user-images.githubusercontent.com/108055010/179967124-5ff928bf-9d07-4adc-9e0e-13fbdc84d017.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### Environment

 Expo CLI 4.13.0 environment info:
    System:
      OS: Windows 10 10.0.17763
    Binaries:
      Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    npmPackages:
      expo: ~43.0.2 => 43.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```js
// Construct a new instrumentation instance. This is needed to communicate between the integration and React
const routing =
  new Sentry.Native.ReactNativeNavigationInstrumentation()

Sentry.init({
  dsn: "https://611ec48f956948b5bbdce87bcce97357@o1125431.ingest.sentry.io/6581300", // is avalable in your project's Settings > Projects > Project name > Client Keys (DSN) tab
  enableInExpoDevelopment: true,
  debug: true, // If `true`, Sentry will try to print out useful debugging information if something goes wrong with sending the event. Set it to `false` in production
  tracesSampleRate: 1.0,
  autoSessionTracking: true,
  //environment :"production",
  integrations: [
    new Sentry.Native.ReactNativeTracing({
     // tracingOrigins: ["localhost", "my-site-url.com", /^\//],
      routingInstrumentation: routing,
    }),
  ],
});

export default function App () {
  //console.log('routingInstrumentationV4' , routingInstrumentation)

  const navigation = React.useRef();
 <NavigationContainer
                linking={deeplinking}
                ref={navigation}
                onReady={() => {
                  // Register the navigation container with the instrumentation
                  routing.registerRoutingInstrumentation(
                    navigation
                  );
                }}
              >
               <Stack.Navigator initialRouteName="onboarding">
                  <Stack.Screen
                    name="home"
                    component={Home}
                    options={{ headerShown: false }}
                  />
                </Stack.Navigator>
 </NavigationContainer>


}

```

**Comment by kbrandwijk** [comment]
You have used `ReactNativeNavigationInstrumentation`, but it seems you are not using `react-native-navigation`, from your code snippet it seems like you use `react-navigation`. Make sure you use the right instrumentations.

This doesn't seem to be an issue with `sentry-expo`.

**Comment by AmineMed95** [comment]
ok thank you for your help 👌
