### ISSUE TITLE
postPublish upload sourceMaps organization case-sensitive

### ISSUE THREAD

**Issue by pwellner** [expo/sentry-expo#273]
### Summary

When the `postHook` `organization` property has any uppercase letter, uploading sourceMaps to Sentry fails, because their URL `https://sentry.io/organizations/orgname/ ` requires the organization to be all lower-case.

`organization` property needs to be down-cased before use in that URL, even when the organization name includes an upper-case letter in the Sentry account.

See https://github.com/expo/sentry-expo/issues/237#issuecomment-1186686345

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

$ npx expo-env-info

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 3.2.1 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 8.13.1 - ~/node_modules/.bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 29, 30, 31, 32
        Build Tools: 28.0.3, 29.0.0, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0
        System Images: android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom
    npmPackages:
      expo: ^45.0.6 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.55.1
      expo-cli: 5.6.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

I believe that changing any letter to upper-case in the `organization` property of the `postPublish` hook should reproduce the bug.

**Comment by kbrandwijk** [comment]
The specs say to specify the organization shortname (or slug). Which is the same thing Sentry uses and expects in their own API. This is not something we're going to wrap in any additional functionality on 'our' end.
