### ISSUE TITLE
» android: sentry-expo: Could not find react.gradle script in android/app/build.gradle. Please open a bug report at https://github.com/expo/sentry-expo.

### ISSUE THREAD

**Issue by hirbod** [expo/sentry-expo#279]
### Summary

» android: sentry-expo: Could not find react.gradle script in android/app/build.gradle. Please open a bug report at https://github.com/expo/sentry-expo.

SDK 46, all versions up 2 date. Not sure how I can help more. The CLI told me to file a bug :)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

46

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 0.59.0
      expo-cli: 6.0.2
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

I have none

**Comment by izakfilmalter** [comment]
Same issue. Busy updating from 45 to 46.

**Comment by JouHouFin** [comment]
Same here. Maybe related to this, I just noticed that source maps haven't been uploaded to Sentry since this bug started appearing in EAS build logs.

**Comment by gretzky** [comment]
Any updates on this? We're experiencing the same issue

**Comment by hirbod** [comment]
Not

**Comment by kbrandwijk** [comment]
No repro or further context for the error message provided, closing.
