### ISSUE TITLE
Source maps always fail to upload to Sentry

### ISSUE THREAD

**Issue by megalithic** [expo/sentry-expo#28]
Presently, on Expo SDK 26 (also happened with 25), we are unable to get source maps to upload to Sentry.

Here is a screenshot of the publishing log from Expo XDE:
<img width="1191" alt="screen shot 2018-05-07 at 5 10 44 pm" src="https://user-images.githubusercontent.com/3678/39727790-c4a9d41c-5219-11e8-9a38-96edf151daf5.png">

Here's the relevant error message: `Error uploading sourcemaps to Sentry: bad json: missing field 'version' at line 1 column 47`

Here is our `app.json` config:
```json
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "our-org-name",
            "project": "our-org-native",
            "authToken":
              "<redacted>"
          }
        }
      ]
    }
```

Please let me know if there are any other pieces of information I might be able to provide to help debug.

Thanks.

**Comment by brentvatne** [comment]
can you provide a small project that repros this?

**Comment by coulix** [comment]
I confirm the issue with expo 55

```
[13:13:50] Running postPublish hook: sentry-expo/upload-sourcemaps
[13:13:52] Error uploading sourcemaps to Sentry: API request failed
  caused by: sentry reported an error: Invalid token (http status: 401)
[13:13:52] Verify that your Sentry configuration in app.json is correct and refer to https://docs.expo.io/versions/latest/guides/using-sentry.html
 
```

**Comment by veedeo** [comment]
Have similar issue:

> Error uploading sourcemaps to Sentry: API request failed
>   caused by: sentry reported an error: unknown error (http status: 504)

Api token scopes:

> event:admin, event:read, member:read, org:read, project:read, project:releases, team:read

**Comment by brentvatne** [comment]
hi there! I just tried a project that was recently working and encountered the same issue.

it appears to be an issue on sentry's end, you can track it here: https://github.com/getsentry/react-native-sentry/issues/463

**Comment by brentvatne** [comment]
this appears to be resolved on sentry's end. tried it again and it worked as expected.

**Comment by actuallymentor** [comment]
To anyone who finds this in 2020: Sentry doesn't like project names with dashes in the name.
