### ISSUE TITLE
Fails in expo 46 - `_core.getIntegrationsToSetup) is not a function`

### ISSUE THREAD

**Issue by mirkokiefer** [expo/sentry-expo#281]
### Summary

Initializing Sentry fails with this output:

```
TypeError: (0, _core.getIntegrationsToSetup) is not a function. (In '(0, _core.getIntegrationsToSetup)(passedOptions)', '(0, _core.getIntegrationsToSetup)' is undefined)
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo/build/errors/ExpoErrorManager.js:25:19 in errorHandler
at node_modules/expo/build/errors/ExpoErrorManager.js:30:24 in <anonymous>
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:203:6 in guardedLoadModule
at http://192.168.1.19:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:null in global code
```

Sentry was initialized as described in the readme:

```
Sentry.init({
  dsn: "...",
  enableInExpoDevelopment: false,
  debug: true
});
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

46

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
      Watchman: 2022.03.14.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.7 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      expo-cli: 6.0.5
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Running `expo start` and launching in iOS simulator triggers the failure.

**Comment by kbrandwijk** [comment]
Is this happening in Expo Go, or in a standalone build?

**Comment by mirkokiefer** [comment]
It's happening in Expo Go for us.

**Comment by Joshandrews43** [comment]
sentry is also not working after upgrading to expo 46

**Comment by haikov** [comment]
It looks like during the upgrade 2 different versions of `@sentry/react-native` get installed (one as a strict dependency of `sentry-expo` and another one is automatically upgraded by expo-cli), and metro gets confused.

As a temporary solution, forcing a single version of `@sentry/react-native` via `resolutions` did the trick for me (according to [sentry-expo peerDependencies 4.2.2](https://github.com/expo/sentry-expo/blob/main/package.json#L45) is a correct version):

```json
"resolutions": {
    "@sentry/react-native": "4.2.2"
},
```

**Comment by gregdburns** [comment]
Confirmed that adding the resolution works.  Thanks for the workaround @haikov !

**Comment by kbrandwijk** [comment]
The versions endpoint for SDK 46 has been adjusted to pin the sentry dependency to 4.2.2. like this library does, so there should be no version conflicts anymore caused by the SDK upgrade.
