### ISSUE TITLE
Overriding release version when using sentry-expo/upload-sourcemaps doesn't seem to change anything

### ISSUE THREAD

**Issue by kylegwalsh** [expo/sentry-expo#287]
### Summary

It's very possible that I'm just doing something wrong, but based on the [documentation on the posthook](https://docs.expo.dev/guides/using-sentry/#31-configure-a--postpublish--hook), it seems like I'm using it correctly.

I am trying to add additional configuration options for the postPublish `sentry-expo/upload-sourcemaps` hook. I would like to set a custom release version so that the app version aligns with my backend and web versions (handled by a mono-repo).

However, when I add a custom `release` parameter based on the "additional configuration options" on that documentation, it seems to be ignored. For example, I provide the version '1.1.9', but it appears as '1.1.9 (1.1.9)' inside of Sentry once the source maps get published (this is what it was doing before I added that `release` parameter).

My end goal would be to have all app versions align with '1.1.9' and also have the mobile source maps associated with this version.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

46.0.9

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.6.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 3.2.2 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.3.0 - ~\AppData\Roaming\npm\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

To reproduce, you should just have to add the following to your expo app config.

```
    hooks: {
      postPublish: [
        {
          file: 'sentry-expo/upload-sourcemaps',
          config: {
            organization: 'XXX',
            project: 'app-mobile',
            authToken: process.env.SENTRY_AUTH_TOKEN,
            setCommits: true,
            deployEnv: 'prod',
            release: '1.1.9',
          },
        },
      ],
    },
```

**Comment by kylegwalsh** [comment]
Bumping so this doesn't close.

**Comment by kylegwalsh** [comment]
Does anyone have any insight into this issue? Have we configured it wrong? Is this an actual bug?

**Comment by jongbelegen** [comment]
Further investigation explains the issue.

In the [expo docs](https://docs.expo.dev/guides/using-sentry/#uploading-source-maps-at-build-time) the following is mentioned:
```actually, we are relying on Sentry's native scripts to handle that```

With eas build the postPublish hook is not being called and the `upload-sourcemaps` is not ran, (this is for the old build system), 
The postPublish hook is still used to get some config to add to the sentry.properties file which is being used by **eas build**
Like @luca-betcha pointed out, only **organization**, **project**, and **authToken** are being used.

Looking at the underlying implementation there seems to be an issue open to add the release and dist properties:
https://github.com/getsentry/sentry-react-native/issues/2450.

At the moment the only way to overwrite the release and dist is by using the environment variables: SENTRY_RELEASE and SENTRY_DIST, you could, for example, add these in your eas.json file.

**Comment by bradjones1** [comment]
Re: https://github.com/expo/sentry-expo/issues/287#issuecomment-1419215252, this is less than ideal but it is the way it is. I'm going to open an issue on the Expo docs to make this less confusing (especially since `expo publish` is deprecated) but in the meantime, I whipped this up during my CI to inject the dynamic values for the environment variables in my `eas.json`. Perhaps it will help someone.

```sh
$ IFS=' ' yarn --silent expo config -t public --json 2>/dev/null | jq -rj '[.version,.runtimeVersion,.android.package]|join(" ")' | { read -r version runtime package; jq ".build.production.env.SENTRY_RELEASE=\"$version\" 
| .build.production.env.SENTRY_DIST=\"$package-$runtime-$version\"" eas.json; } > test.json && mv test.json eas.json
```
