### ISSUE TITLE
Unable to modify build script 'Bundle React Native code and images'

### ISSUE THREAD

**Issue by CharlyPoppins** [expo/sentry-expo#288]
### Summary

`npx expo prebuild`

Give me this warning :

`» ios: sentry-expo: Unable to modify build script 'Bundle React Native code and images'. Please open a bug report at https://github.com/expo/sentry-expo.
`

This warning is triggered by `node_modules/sentry-expo/plugin/build/withSentryIOS.js` 
`function modifyExistingXcodeBuildScript(script) {
...
`

Content of `script.shellScript` is :

```export SENTRY_PROPERTIES=sentry.properties\nexport EXTRA_PACKAGER_ARGS=\"--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map\"\nexport NODE_BINARY=node\n\n# The project root by default is one level up from the ios directory\nexport PROJECT_ROOT=\"$PROJECT_DIR\"/..\n\n`node --print \"require.resolve('@sentry/cli/package.json').slice(0, -13) + '/bin/sentry-cli'\"` react-native xcode --force-foreground `node --print \"require('path').dirname(require.resolve('react-native/package.json')) + '/scripts/react-native-xcode.sh'\"`\n"```

Splited by \n :
`[
  '"export SENTRY_PROPERTIES=sentry.properties',
  'export EXTRA_PACKAGER_ARGS=\\"--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map\\"',
  'export NODE_BINARY=node',
  '',
  '# The project root by default is one level up from the ios directory',
  'export PROJECT_ROOT=\\"$PROJECT_DIR\\"/..',
  '',
  '`node --print \\"require.resolve(\'@sentry/cli/package.json\').slice(0, -13) + \'/bin/sentry-cli\'\\"` react-native xcode --force-foreground `node --print \\"require(\'path\').dirname(require.resolve(\'react-native/package.json\')) + \'/scripts/react-,
  '"'
]`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

46.0.0

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v14.19.1/bin/yarn
      npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
      Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
      Android SDK:
        API Levels: 30, 31, 32
        Build Tools: 29.0.2, 30.0.2, 31.0.0, 32.0.0
        System Images: android-30 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: Chipmunk 2021.2.1 Patch 2 Chipmunk 2021.2.1 Patch 2
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.13 => 46.0.13
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
      react-native-web: ~0.18.7 => 0.18.7
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Execute `npx expo prebuild`

**Comment by bencollinsuk** [comment]
Same issue

**Comment by eabais-arc** [comment]
Any updates for this? Same issue as well
