### ISSUE TITLE
Provide authToken from an external source for security reasons

### ISSUE THREAD

**Issue by dincozdemir** [expo/sentry-expo#29]
I think it would be great to allow an alternative way to provide the authToken from an external source, for security reasons. 
Something like this maybe:
```
Sentry.config(config.sentry.publicDSN, {
      authToken: config.sentry.authToken
}).install();
```

**Comment by byCedric** [comment]
I would love this too! Maybe even adding a simple "fallback" with a environment variable in `upload-sourcemaps.js` will fix this too.

e.g.
```
    const childProcessEnv = Object.assign({}, process.env, {
        SENTRY_ORG: config.organization,
        SENTRY_PROJECT: config.project,
        SENTRY_AUTH_TOKEN: config.authToken || process.env.SENTRY_AUTH_TOKEN,
        SENTRY_URL: config.url || 'https://sentry.io/',
    });
```

**Comment by brentvatne** [comment]
what are the security reasons?

**Comment by byCedric** [comment]
The security reasoning behind this is that _all tokens_ must _not_ be present in the repository. Even though this Sentry token should only create new releases and nothing more, it still is a token. Because of this, I would absolutely love having this not-included in the manifest (and the repository). 😄

**Comment by brentvatne** [comment]
if that is the concern then create a `config.example.js` and `config.js` file and just commit `config.example.js` and leave out any of the tokens

**Comment by byCedric** [comment]
I'm not sure what the case of @dincozdemir is, and I'm sorry if I took over your original issue!

I totally agree with you @brentvatne, Sentry has made it clear that there is a difference between public DSN and private DSN. The public version is specifically built for front end javascript apps, and should only include the "app id" (not key). The private version is for "controlled environments", like servers, to verify it's allowed to log the issue.

The docs also provide this, which is perfect!
> Note that for Expo you have to use you public DSN instead of the private one.

So, in my case I'm using a public DSN which may be included in the build. It doesn't contain any issues regarding security. But that's a different story for the `release-authentication token`, to upload the source maps of new releases to your Sentry project.

Right now it's hardocoded into the Expo Manifest, which is available in the build (as you stated). As far as I know, this is token is only relevant for uploading source maps therefore the build/publish stages. If we can find a way to include this token, outside of the manifest, we can have best of all worlds; not writen in the Expo Manifest, but still available during builds from CI without overhead.

I tried to explain that this change is possible by adding a fallback to the environment in [`upload-sourcemaps.js`](https://github.com/expo/sentry-expo/blob/master/upload-sourcemaps.js#L40). I'm sorry if that wasn't clear enough. If we change this line:

```
SENTRY_AUTH_TOKEN: config.authToken,
```

to

```
SENTRY_AUTH_TOKEN: config.authToken || process.env.SENTRY_AUTH_TOKEN, 
```

will fix this issue, I think.

**Comment by brentvatne** [comment]
Sentry config and any other private keys in app.json aren't included in the Expo manifest, we remove them. If you're not seeing this behavior then let me know as that's a bug that should be resolved.

**Comment by byCedric** [comment]
I stand corrected! But still, I find the extra overhead you create for building from CI/cloud environments not the best solution compared to the relatively simple change.

**Comment by brentvatne** [comment]
it's not really much overhead, we just don't include anything that's part of the build process in the final manifest. so any postpublish config is entirely removed

**Comment by brentvatne** [comment]
that said, i'll review your env var PR today because it doesn't hurt to have an option if someone prefers that. i personally don't see why but i am glad that people have different opinions than me because the world would be boring otherwise :P

**Comment by Elijen** [comment]
@byCedric @brentvatne 
We're trying to set `expo publish` on Bitbucket Pipeline, but it looks like the script is unable to access `SENTRY_AUTH_TOKEN` from env variables (using v1.10.0). It works locally though. Any idea what could be causing the issue? (The variable is set in the pipeline settings and other env variables are readable).

**Comment by brentvatne** [comment]
that doesn't make much sense to me, i'd try just moving it back to the node_modules hook and it'll probably work, i imagine it was some environment issue

**Comment by enderandpeter** [comment]
It should be obvious why someone would want API tokens/secrets in untracked config files. Apparently, @brentvatne is the kind of guy who wouldn't mind sharing his AWS API credentials with me, for example. But for everyone else, you can use a [react-native-specific implementation of dotenv](https://github.com/zetachang/react-native-dotenv) to at least keep your Public DSN private.

**Comment by brentvatne** [comment]
@enderandpeter - i don't think you understand that the library you linked to just inlines whatever env vars you use into your js bundle. i have no idea how you think that it works, but i suspect you just assume it is some kind of security magic and really don't have a clue. why you would want to keep your *public DSN* private is beyond my understanding. so i will lock this thread and just recommend that anyone ignore @enderandpeter whenever he attempts to provide guidance.

**Comment by brentvatne** [comment]
if you want to store your dsn somewhere outside of your code, consider having a `config.js` that you don't commit to git, then a `config.example.js` that demonstrates some placeholder values.
