### ISSUE TITLE
postPublish not running in sdk 47 causing the source maps to not upload

### ISSUE THREAD

**Issue by jamesloper** [expo/sentry-expo#306]
### Summary

I followed the guide to install `sentry-expo` which resulted in sentry-expo 5.0.0 being installed. I already fixed this myself by updating manually to  `"sentry-expo": "6.0.0"`

If I run `eas update` an OTA is published successfully and the client receives the update however the source maps are missing from sentry. To debug, I add a `console.log('HERE123')` to upload-sourcemaps.js I noticed that HERE123 does not show when running `eas update`.

I have postPublish and plugins declared in app.json
```
    "plugins": [
      "sentry-expo"
    ],
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "<secret>",
            "project": "<secret>",
            "authToken": "<secret>"
          }
        }
      ]
```

the result? postPublish script is not being called!

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

47

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.21.1 - /opt/homebrew/opt/node@14/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 6.14.17 - /opt/homebrew/opt/node@14/bin/npm
      Watchman: 2022.11.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.0 => 47.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.70.6 => 0.70.6 
    npmGlobalPackages:
      eas-cli: 2.8.0
      expo-cli: 6.0.8
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

https://docs.expo.dev/guides/using-sentry/

**Comment by krystofwoldrich** [comment]
For OTA updates you need to upload the bundle and the source maps manually.

https://docs.expo.dev/guides/using-sentry/#uploading-sourcemaps-for-updates

Maybe this repo (managed workflow) can also help with finding the bug.
https://github.com/krystofwoldrich/sentry-expo-sample-app

**Comment by krystofwoldrich** [comment]
Based on [the docs](https://docs.expo.dev/guides/using-sentry/#uploading-sourcemaps-for-updates) I believe you are right @jamesloper if you want to automatize the process.

Disclaimer, I maintain the `@sentry/react-native`, so when it comes to `sentry-expo` my knowledge is limited.

**Comment by gregdburns** [comment]
For what it's worth, I have this working for Expo 47, and the key for me was to omit the "release" property in the Sentry config (it was causing multiple release to be created when errors were generated, which were not tied to the build time release).

More more details on my config, take a look at https://github.com/expo/sentry-expo/issues/285 (my last comment).  I'm happy to elaborate if anything isn't clear or more info is needed.
