### ISSUE TITLE
Importing Sentry causes error dealing with fetch.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [expo/sentry-expo#31]
Adding `import Sentry from 'sentry-expo'` to my `App.js` causes my app to crash:

```
Unhandled JS Exception: Requiring module "fetch", which threw an exception. 
TypeError: undefined is not an object (evaluating 'self.fetch').
```

Digging around, I've seen issues crop up in `react-native` [here](https://github.com/facebook/react-native/issues/9599) and `fetch` [here](https://github.com/github/fetch/issues/125) and `isomorphic-fetch` [here](https://github.com/matthew-andrews/isomorphic-fetch/pull/63). AFAICT, `isomorphic-fetch` is the root of the problem, it's not maintained and didn't support React Native, and now people are moving to other packages (`cross-fetch`, `fetch-everywhere`, `fetch-ponyfill`, etc.) as a replacement.

Are other people running into this problem? Right now, following the Expo docs, I'm unable to get Sentry to work for React Native. 😞 

Versions:

```
"expo": "^27.0.2",
"react-native": "https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz",
"sentry-expo": "^1.9.0"
```

**Comment by mxstbr** [comment]
✋ We're also running into this exact same error! Interestingly, it did work in SDK 27 but as soon as we try upgrading to SDK 28 this red screen error pops up on boot. withspectrum/spectrum#3372

**Comment by brentvatne** [comment]
hey @AndrewSouthpaw I cannot repro this in a branch new app. I created a new app and added sentry-expo and it worked as expected. Perhaps another package that you and @mxstbr have in your app is causing an unexpected interaction?

**Comment by AndrewSouthpaw** [comment]
FYI we resolved the issue by changing our `.babelrc` file. It used to contain a bunch of stuff:

```
presets: ['es2015', 'react', 'stage-2', 'flow', 'babel-preset-expo']
```

We changed it to

```
presets: ['babel-preset-expo']
```

and the problem resolved itself.

**Comment by brentvatne** [comment]
@mxstbr ^
