### ISSUE TITLE
Sentry is not sending global errors

### ISSUE THREAD

**Issue by wamphlett** [expo/sentry-expo#32]
I am having problems with global errors not getting sent to Sentry in development. This has been raised before in #23 however it was never officially answered and I feel there are still people experiencing the same thing. It would be nice to get an offical answer on it. 

```
Sentry.enableInExpoDevelopment = true
Sentry.config('DSN'}).install()

Sentry.captureMessage('TestMessage') // expected result
Sentry.captureException(new Error('TestError')) // expected result

throw new Error('TestError') // Not in Sentry
```

Is this expected in development, am I missing something, or is there something wrong here?

**Comment by brentvatne** [comment]
errors in development are caught by a global error handler in expo then passed along to the original handler: https://github.com/expo/expo/blob/deb7e9497ed09f5e1f5ca3409f2b6d020d15646e/packages/expo/src/launch/RootErrorBoundary.tsx#L21-L52

if you can post an example project with this problem i'd be happy to look!

**Comment by brettdh** [comment]
@brentvatne I've got one:

https://github.com/theliturgists/app/pull/159

Nothing shows up in Sentry. Not sure if there's a better way to test that I've hooked things up correctly, but this seems like a pretty simple error that ought to be reported. (It causes a redbox in development)

**Comment by brettdh** [comment]
FWIW, `Sentry.captureMessage` works fine with my configuration.

**Comment by brettdh** [comment]
Hmm. Tried again with my dev server running in production, and Sentry received the error this time (albeit after a delay). I guess I'll chalk this up to me not realizing that no errors are reported if they result in a dev redbox (per https://github.com/getsentry/react-native-sentry/issues/6).

(And with me not realizing that sentry-expo is a thin wrapper around react-native-sentry)
