### ISSUE TITLE
postPublish not running on android expo SDK 48 for Android

### ISSUE THREAD

**Issue by RRaideRR** [expo/sentry-expo#329]
### Summary

Not quite sure how already closed issue (#320 #292 ) are observed - probably not so much, so that's the reason why I'm opening up this issue.

I took this [sample app](https://github.com/krystofwoldrich/sentry-expo-sample-app) and updated my dependencies to match the latest Expo SDK 48 release. In addition, I'm also using the url parameter because I have my own Sentry server. The source maps are not uploaded for Android eas builds.

I can see "Upload Debug Symbols to Sentry" in my fastlane logs but not in my gradle logs.

My specific dependencies:
```
    "expo": "~48.0.6",
    "expo-status-bar": "~1.4.4",
    "react": "18.2.0",
    "react-native": "0.71.3",
    "sentry-expo": "~6.1.0",
    "expo-application": "~5.1.1",
    "expo-constants": "~14.2.1",
    "expo-device": "~5.2.1",
    "expo-updates": "~0.16.3",
    "@sentry/react-native": "4.13.0"
```

However: iOS upload works. Two minor things that I changed in comparison to your project:

I've made use of the SENTRY_AUTH_TOKEN variable
I use my own sentry server.
Thus, my postPublish hook looks like this:

```
     "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "myOrg",
            "project": "expo-test",
            "url": "https://sentry.myServer.com/"
          }
        }
      ]
    },

```

[It seems like I'm not the only one where this is happening.](https://github.com/expo/sentry-expo/issues/292#issuecomment-1477816950)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

48

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
      Watchman: 2023.03.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.6 => 48.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
    npmGlobalPackages:
      eas-cli: 3.8.1
    Expo Workflow: managed

```

### Reproducible demo or steps to reproduce from a blank project

Take this [sample app](https://github.com/krystofwoldrich/sentry-expo-sample-app) and update the dependencies to match the latest Expo SDK 48 release.

**Comment by RRaideRR** [comment]
Nope the problem still exists.

**Comment by thomasgrivet** [comment]
Hello, this issue is still present and is preventing us from upgrading to SDK 48

**Comment by anirudhsama** [comment]
Hi, we are also facing this issue!

**Comment by karbone4** [comment]
Hey, I have same issue on sdk 48

**Comment by lobotomoe** [comment]
Same iOS either.

**Comment by Alex1899** [comment]
I am getting the same issue on Android, Expo sdk 48. Has anybody managed to fix this? I would really appreciate it if you could share a solution.

**Comment by krystofwoldrich** [comment]
Hello everyone,
thank you for using the sample app it makes debugging these issues much easier. 

I've updated the sample to Expo SDK 48 and reproduced the same issue.

To fix it simply bump the `@sentry/react-native` to the latest v4 version. 
Currently, that is `@sentry/react-native@4.15.2`.

After that, the automatic source map upload on Android will be working again.
- https://github.com/krystofwoldrich/sentry-expo-sample-app/tree/b196f6ea4938b35d586963e32ebd8c3d9bdabffd

For anyone interested this (https://github.com/getsentry/sentry-react-native/pull/2759) is the fix on the undelaying `sentry-react-native` package.
