### ISSUE TITLE
Sentry.init not initiating when offline - causes a crash

### ISSUE THREAD

**Issue by NOxDriver** [expo/sentry-expo#333]
### Summary

I recently moved from expo-go to expo-dev-client and since then, the app crashes on start up if there is slow or no internet. 

I have this in my app.js:

try {
  Sentry.init({
    dsn: 'https://XXX@XXX.ingest.sentry.io/XXX',
  });
}
catch (e) {
  console.log('Sentry error: ', e)
}

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

46.0.0

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.5.5 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.3.17 => 0.3.19 
      expo: ^46.0.0 => 46.0.20 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.9.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Yarn Start --dev-client

Then open up the app when there is no internet, it crashes.

**Comment by kbrandwijk** [comment]
Our `init` method is pretty much a wrapper around the `init` method from `@sentry/react-native`. Can you confirm that you're seeing the same behavior using `init` from `@sentry/react-native` instead of `sentry-expo`, just to rule out `sentry-expo` as the cause of this?

**Comment by NOxDriver** [comment]
I updated to 5.0.3 and it seems to have fixed the issue.
