### ISSUE TITLE
captureException does not log `extra` data

### ISSUE THREAD

**Issue by benburton** [expo/sentry-expo#34]
I'd like to capture some additional metadata around an exception. From the docs I've read regarding Raven, I would expect to be able to capture this by making a call to `captureException` as follows:

```
Sentry.captureException(new Error('My iPhone is on fire!'), { 
    extra: {
        fireTemperature: {
            f: 1100,
            c: 585
        }
    }
});
```

Is this possible? Am I doing this correctly?

**Comment by slorber** [comment]
this works fine for me

**Comment by brentvatne** [comment]
I copied the exact code above and ran it in prod and it produced the expected result:

<img width="705" alt="screen shot 2018-10-03 at 2 47 01 pm" src="https://user-images.githubusercontent.com/90494/46441443-63f75c80-c71b-11e8-8708-cf2e9f655a50.png">
