### ISSUE TITLE
"undefined is not a function" error with addTracingExtensions

### ISSUE THREAD

**Issue by kevinhu** [expo/sentry-expo#345]
### Summary

I'm trying to use sentry-expo in iOS while also using expo-router. However, my app immediately crashes with an error stating that "undefined is not a function" while the trace points to an `addTracingExtensions` call.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

48

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.1 - ~/.asdf/installs/nodejs/18.14.1/bin/node
      Yarn: 1.22.19 - ~/.asdf/installs/nodejs/18.14.1/.npm/bin/yarn
      npm: 9.3.1 - ~/.asdf/plugins/nodejs/shims/npm
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.19 => 48.0.19
      react: ^18.2.0 => 18.2.0
      react-dom: ^18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
      react-native-web: ~0.18.10 => 0.18.12
    npmGlobalPackages:
      eas-cli: 3.13.3
      expo-cli: 6.3.8
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

- Install expo-router and sentry-expo
- In any router file, use the following:
```typescript
import * as Sentry from 'sentry-expo';
Sentry.init({
  dsn: "<DSN>",
  debug: true
});
```

**Comment by a-eid** [comment]
facing the same error 

![Screenshot 2023-06-18 at 03 06 03](https://github.com/expo/sentry-expo/assets/19273413/9cdcd0a6-f318-4b75-9db8-e4fd997eb8e4)

**Comment by a-eid** [comment]
this solution seem to work for me 

```json
"workspaces": {
    "packages": [
      "apps/*",
      "packages/*"
    ],
    "nohoist": [
      "**/@sentry/react-native"
    ]
  },
  ```

**Comment by zackify** [comment]
```
import "expo-router/entry";
import * as Sentry from "sentry-expo";
import * as SentryNative from "@sentry/react-native";
Sentry.init({
  integrations: [new SentryNative.ReactNativeTracing()],
});
```

fixed this by importing from the actual @sentry/react-native package when using the expo library

**Comment by SleeplessByte** [comment]
This still happens. Will try the workaround by https://github.com/expo/sentry-expo/issues/345#issuecomment-1620832670
