### ISSUE TITLE
Source code was not found

### ISSUE THREAD

**Issue by jackmatrix** [expo/sentry-expo#35]
I cannot display my original code in sentry dashboard. 

I've configured the `app.json` as indicated in the docs

```
"hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "xxxxx",
            "project": "xxxxxxx",
            "authToken": "xxxxxxxxxx"
          }
        }
      ]
    }
```

My sentry dashboard display these two following errors 

`Discarded invalid parameter 'type'`

    Source code was not found for app:///crna-entry.delta? 
    platform=ios&dev=true&minify=false`

Any solution ?

**Comment by jackmatrix** [comment]
i don't understand. I published my expo app with `exp publish` so many times. So it's seems something is going wrong. Because i received some errors from my production built but it still was the same problem. Any solution ?

Is there a possibility to upload sourcemap manually ?

**Comment by brentvatne** [comment]
the error message you pasted is for a project in development, not in production. as in you are opening the project from the development URL and not the production URL. sure you can publish them manually just look at the source for sentry-expo.

**Comment by jackmatrix** [comment]
I have another error from my production app and the issue is still there : 

```app:///%40user%2Fmyappname%2F1.0.1%2F614xxxxxxxxxxxxxxxxxxc-0.0.0.0-ios.js```

i'm afraid i didn't understand how to do manual uploading. Where should i look at the sentry-expo source ?

**Comment by brentvatne** [comment]
https://github.com/expo/sentry-expo/blob/master/upload-sourcemaps.js

**Comment by jaychenjun** [comment]
@brentvatne I am in the right channel, and I can see source map generated successfully under the Artifacts tab in the Sentry UI, but still got this error, maps are not working.

**Comment by brentvatne** [comment]
can you ask for support from sentry? I'm not sure what's happening, as far as I know we are doing what we are supposed to do here

**Comment by ltankey** [comment]
I'm finding the same thing happening, and am not sure which end it's on (sentry or expo).

My artefacts are uploaded fine and appear to have source maps correctly mapped to the bundles:

```
+-----------------------+--------------+------------------+--------+
| Name                  | Distribution | Source Map       | Size   |
+-----------------------+--------------+------------------+--------+
| ~/main.android.bundle |              | main.android.map | 2.40MB |
| ~/main.android.map    |              |                  | 8.26MB |
| ~/main.ios.bundle     |              | main.ios.map     | 2.41MB |
| ~/main.ios.map        |              |                  | 8.30MB |
+-----------------------+--------------+------------------+--------+
```

This is correctly shown under the release for which I expect these to have been uploaded.

When an issue is received for this release, it correctly shows in Sentry:
![image](https://user-images.githubusercontent.com/5369670/48456334-c790a180-e812-11e8-8b17-4a9b446938c2.png)

However the actual issue shows this:
![image](https://user-images.githubusercontent.com/5369670/48456362-e7c06080-e812-11e8-8b4f-4956faa0f761.png)

With the non-sourcemapped stacktrace:
![image](https://user-images.githubusercontent.com/5369670/48456386-045c9880-e813-11e8-8de1-01637b5abb87.png)


So, given all of this, do we think the error lies upstream?

**Comment by brentvatne** [comment]
@ltankey - yes you should follow up with sentry. please let me know what you find as it could help others in this thread

**Comment by brentvatne** [comment]
![screen shot 2019-01-08 at 11 05 01 am](https://user-images.githubusercontent.com/90494/50852882-a5f4f780-1335-11e9-83dd-bf48c3d27784.png)

I just tried this and it worked as expected with sentry-expo@1.11.1

**Comment by ltankey** [comment]
@brentvatne supposedly it works with the SaaS offering but not self-hosted sentry instances. 

Issue being discussed here: https://github.com/getsentry/react-native-sentry/issues/481

**Comment by ltankey** [comment]
Just a follow-up:
- my issue was related to the on-prem sentry
- artefacts are being uploaded fine
- the issue seems to be in sentry's internal file resolution (weird)
