### ISSUE TITLE
Warning error when running dev app

### ISSUE THREAD

**Issue by RSNFreud** [expo/sentry-expo#355]
### Summary

![image](https://github.com/expo/sentry-expo/assets/23102186/4762998b-0f63-4429-b401-941a6b1a71c7)

I get this sent every time the app reloads

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

6.2.0

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.1 - ~\AppData\Roaming\npm\npm.CMD
    IDEs:
      Android Studio: AI-212.5712.43.2112.8609683
    npmPackages:
      @expo/webpack-config: ^18.0.4 => 18.0.4
      expo: ~48.0.16 => 48.0.16
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.7 => 0.71.7
      react-native-web: ~0.18.10 => 0.18.12
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

-

**Comment by alessandrocapra** [comment]
To add to this, I confirm I have installed the following packages following the installation guide for sentry-expo:
```
"sentry-expo": "~6.2.0",
"@sentry/react-native": "4.15.2",
```

**Comment by RSNFreud** [comment]
Not stale.

**Comment by krystofwoldrich** [comment]
@RSNFreud Thank you for the message.

It looks like you have Sentry disabled for a development environment. What is the expected behavior? Only the first log message and no working?

Or is this a mistake and you enabled Sentry for dev?

**Comment by RSNFreud** [comment]
The expected behaviour is for it not to show that error every time the app
is rerendered

**Comment by krystofwoldrich** [comment]
@RSNFreud Got it, we will take a look if we can make the log less intrusive.

**Comment by krystofwoldrich** [comment]
Hi @RSNFreud ,
`sentry-expo` was recently deprecated in favor of `@sentry/react-native` which supports Expo out of the box now.

And this warning is not present in the `@sentry/react-native`. We reworked the Expo integration and the logs and warnings are now much more pleasant and less intrusive for Expo Go users.

https://github.com/getsentry/sentry-react-native/pull/3466
