### ISSUE TITLE
sentry-expo 7.0.1 causes fastlane error during production build

### ISSUE THREAD

**Issue by pkayfire** [expo/sentry-expo#359]
### Summary

Seeing a fastlane error when trying to build an Expo project with sentry-expo 7.0.1. Downgrading back 6.2.1 resolves the error.

<img width="946" alt="image" src="https://github.com/expo/sentry-expo/assets/2524873/87401fa6-6eab-4da8-9ddc-8058a5afb194">

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

7.0.1

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.16.0 - /usr/local/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.8.4 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.3
        System Images: android-29 | Google Play Intel x86 Atom
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.16 => 48.0.19
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
      react-native-web: ~0.18.9 => 0.18.12
    npmGlobalPackages:
      eas-cli: 3.14.0
      expo-cli: 6.3.8
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Build expo project for production with sentry-expo 7.0.1

**Comment by sebastiancrossa** [comment]
running into the same issue!

**Comment by winstromming** [comment]
@pkayfire @sebastiancrossa We were able to resolve this issue by removing the `postPublish` hook for uploading sourcemaps.

**Comment by jsfuentes** [comment]
Downgrading to different versions did not solve the issue for me, literally just adding sentry-expo to the package.json causes the entire build to fail

**Comment by krystofwoldrich** [comment]
@pkayfire Can you share the whole build log, hopefully from there we will be able to identify what's happening.
