### ISSUE TITLE
[iOS][Expo@49][v7] Upload Source Maps Fails: `Found argument 'debug-files' which wasn't expected`

### ISSUE THREAD

**Issue by psteinroe** [expo/sentry-expo#360]
### Summary

After updating to the latest of expo and expo-sentry, the production build for iOS fails at `Upload Source Maps` with `Found argument 'debug-files' which wasn't expected`. It worked before the update. 

I disabled the post-publish plugin for now to have a working build.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

49

### Environment

```
 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
      Watchman: 2023.07.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9971841
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

I can provide one if required, but since there was no change other than updating the projects dependencies I suppose this might be a general issue.

**Comment by felixaa** [comment]
I have the same issue. PhaseScriptExecution Upload\ Debug\ Symbols\ to\ Sentry fails

**Comment by claudiofus** [comment]
I'm facing the same error after the creation of Expo secret and removing `authToken` from my `app.json`. With `authToken` in my `app.json` I have a security alert but no error and the build works fine.
