### ISSUE TITLE
Build failure - 403 error 

### ISSUE THREAD

**Issue by dev-agile** [expo/sentry-expo#365]
### Summary

The build is created successfully in my local but the build generated on expo.dev is failing with a 403 error.Below is the error I am getting 

`> Task :app:createBundleReleaseJsAndAssets_SentryUpload_com.apolloBuyerSalamiSlicing@1.1.16+73_73
Processing react-native sourcemaps for Sentry upload.
> Analyzing 2 sources
[stderr] 
INFO    2023-08-22 10:31:12.642197089 +00:00 Loaded file referenced by SENTRY_PROPERTIES (/home/expo/workingdir/build/android/sentry.properties)
> Rewriting sources
> Adding source map references
[stderr] 
error: API request failed
[stderr] 
  caused by: sentry reported an error: You do not have permission to perform this action. (http status: 403)
[stderr] 
Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
[stderr] 

> Task :app:createBundleReleaseJsAndAssets_SentryUpload_com.apolloBuyerSalamiSlicing@1.1.16+73_73 FAILED`

Execution failed for task ':app:createBundleReleaseJsAndAssets_SentryUpload_com.apolloBuyerSalamiSlicing@1.1.16+73_73'.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.18 => 48.0.20 
      react: 18.2.0 => 18.2.0 
      react-dom: ^18.1.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Getting this error while generating an eas build. Using ./gradlew :app:assembleRelease command to generate build locally.

**Comment by Dwikavindra** [comment]
Getting the same issue any fix yet ? @kbrandwijk @dev-agile
