### ISSUE TITLE
Unable to strip prefixes from sourcemaps (no way to use --strip-prefix, --strip-common-prefix)

### ISSUE THREAD

**Issue by alminde** [expo/sentry-expo#37]
In order to not end up with paths like `/Users/You/Projects/Something/src/some/path.js` in Sentry, there should be a way to use the `--strip-prefix` and `--strip-common-prefix` options for `sentry-cli releases files upload-sourcemaps` when uploading sourcemaps.

Currently this does not seem to be possible, [cf. this section of `upload-sourcemaps.js`](https://github.com/expo/sentry-expo/blob/69c6ef8ac4395e55a19a64380fedf3d39658cd6a/upload-sourcemaps.js#L61).

**Comment by brentvatne** [comment]
hi! what do you need it for? you can submit a pull request to add that as an option if you like, be sure to explain why though
