### ISSUE TITLE
Sentry - Unhandled JS Exception

### ISSUE THREAD

**Issue by LouisJS** [expo/sentry-expo#38]
I followed [this guide](https://docs.expo.io/versions/latest/guides/using-sentry) to implement sentry in my Expo App.
I did setup my “hooks” in app.json and when i published my app, everything went fine with the sourcemaps and i can even see the version of my published app in the ‘Releases’ tab in my Sentry project.

So for now, everything looks fine.

I’ve created a Button that looks like this

    <Button onPress={() => {throw new Error('sample error from expo')}} title="broken"/>

When `Sentry.enableInExpoDevelopment = false;` and i press my button, the result is
[like this](https://res.cloudinary.com/dsb83qpj8/image/upload/v1541414105/Screenshot_2018-11-05_at_11.23.58.png)

So my Error is triggered successfully. Now i want to catch the error with sentry so i’m updating my code to `Sentry.enableInExpoDevelopment = true;`
And when i do so, it gives me this [error](https://res.cloudinary.com/dsb83qpj8/image/upload/v1541414105/Screenshot_2018-11-05_at_11.25.18.png)

And nothing seems to happen in my Sentry Dashboard.

Anyone faced the issue already ?

I’m on my default channel.
Tested on virtual device (iphone 8) & real device (iphone 6)
Using `sentry-expo@1.10.0`

**Comment by LouisJS** [comment]
https://github.com/getsentry/react-native-sentry/issues/498

Could be related to this issue

**Comment by LouisJS** [comment]
![screenshot_20181109-170707](https://user-images.githubusercontent.com/6095371/48274499-c262d980-e443-11e8-98eb-c3313241a75b.png)

Result on Android as well

**Comment by iamrommel** [comment]
@LouisJS , i'm using SDK31 as reported at #43 and having the same issue. Do you have updates on this issue?

**Comment by LouisJS** [comment]
@iamrommel Still none :/

**Comment by brentvatne** [comment]
i published sentry-expo@1.11.1 which adds the following lines to sentry-expo/index.js

```js
import Raven from 'raven-js';
Raven._hasDocument = false;
```

tested it and it worked as expected

![screen shot 2019-01-08 at 11 05 01 am](https://user-images.githubusercontent.com/90494/50852774-5dd5d500-1335-11e9-9909-7d1dc1aadb02.png)
