### ISSUE TITLE
Importing expo-sentry causes "There was an error sending log messages..." in dev

### ISSUE THREAD

**Issue by chriskaya** [expo/sentry-expo#39]
Hello there,

First of all, everything works well in prod, thank you all for your work ! :)

However, every time I start the app in dev, using `expo start`, I can't get the app running on my phones/simulators.

On android: I'm stuck on "Downloading JavaScript bundle 100.00%"
On iOS: I get the message "There was an error sending log messages to your development environment".

Commenting out the import fixes the issue.

Here's my .babelrc (see #31):
```javascript
{
  presets: ["babel-preset-expo"]
}
```

Here's my package.json:
```javascript
{
  "name": "tripartie",
  "version": "1.0.0",
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "eject": "expo eject",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "email-regex": "^3.0.0",
    "expo": "^31.0.0",
    "fuzzy": "^0.1.3",
    "intl": "^1.2.5",
    "libphonenumber-js": "^1.6.4",
    "lodash": "^4.17.11",
    "mangopay-cardregistration-js-kit": "^1.2.2",
    "moment": "^2.22.2",
    "react": "16.5.0",
    "react-intl": "^2.7.2",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz",
    "react-native-animatable": "^1.3.0",
    "react-native-keyboard-aware-scroll-view": "^0.7.4",
    "react-native-loading-spinner-overlay": "^0.5.2",
    "react-native-modal": "^6.5.0",
    "react-native-modal-datetime-picker": "^6.0.0",
    "react-native-slider": "^0.11.0",
    "react-native-status-bar-height": "^2.1.0",
    "react-redux": "^5.0.7",
    "react-router-native": "^4.3.0",
    "react-swipeable-views-native": "^0.13.0",
    "redux": "^4.0.0",
    "redux-form": "^7.4.2",
    "redux-persist": "^5.10.0",
    "redux-thunk": "^2.3.0",
    "sentry-expo": "^1.10.0",
    "styled-components": "^3.4.2"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0",
    "jest-expo": "^31.0.0"
  }
}
```

And the begginning of my App.js:
```javascript
import React from "react";
import { StyleSheet, Text, View, StatusBar } from "react-native";
import { Font, Asset } from "expo";
import Sentry from "sentry-expo";
import Main from "./src/Main";

Sentry.config('https://846f2b57912b439b932f809f6ee63249@sentry.io/1321997').install();

console.disableYellowBox = true;
```

Any ideas ?

Thx!

**Comment by fkanout** [comment]
I'm having this problem now

**Comment by chriskaya** [comment]
Hello @fkanout 
I've had this error message a lot recently, and it seems to appear when you try to console.log a complex object
Try to console.log strings, or simple arrays or object (Object.keys, etc.)

**Comment by fkanout** [comment]
Hi @chriskaya  
I'm not sure if it's really related to a "big" `console.log`. I've none of them unless if there is another lib that I'm using is printing out these objects.

Are you using `Sentry` in your App ? when I pulled it out, the error message disappeared.

**Comment by chriskaya** [comment]
> 
> 
> Well, I forgot to comment the import line this morning, no issue so far.
> Seems like the problem disappeared.

It might be linked to a console.log in sentry lob
As I said in a previous post, it resolved itself for me. Maybe linked to an order of operations, import, or something like that.
If you could pinpoint the location of the troublesome console.log, it could be useful to the contributors :)
