### ISSUE TITLE
Latest sentry sdk

### ISSUE THREAD

**Issue by brownbl1** [expo/sentry-expo#50]
Is there a plan to upgrade to the latest Sentry node sdk? The API is completely different.

**Comment by brentvatne** [comment]
can you clarify the question please? this project doesn't depend on the latest sentry node sdk. this is a thin wrapper around https://github.com/getsentry/react-native-sentry - we could bump that verison to 0.42.0 though!

**Comment by brownbl1** [comment]
Ah okay. I see now. I was looking at the node.js documentation for Sentry and it looks like the method names are different from what comes with this project. But if it's not relevant to this repo then disregard.
