### ISSUE TITLE
Problem with Exp Publish Since Recent Change in expo-constants

### ISSUE THREAD

**Issue by larkintuckerllc** [expo/sentry-expo#63]
Tracking down a recent (TODAY) error that just appeared in our older Expo project: 28.0.0 related to expo-constants.

Noticed that sentry-expo just changed (YESTERDAY) and the change appears to be highly correlated.

The problem is when trying to run `exp publish`

```
[19:54:06] 500 - "{\"originModulePath\":\"/Users/johntucker/Documents/digital/stryker-product-usage-mobile/node_modules/sentry-expo/index.js\",\"targetModuleName\":\"expo-constants\",\"message\":\"Unable to resolve module `expo-constants` from `/Users/johntucker/Documents/digital/stryker-product-usage-mobile/node_modules/sentry-expo/index.js`: Module `expo-constants`
```

Have been doing everything in my power to remove Sentry from my project as it is less important to the build from what I can tell it is all gone.  Yet I get these errors still

**Comment by cruzach** [comment]
Hi @larkintuckerllc ! Sorry you're running into this error 

`sentry-expo` was updated recently to use the new modular importing style for Expo's SDK 33. I would imagine this would update automatically, but deleting `node_modules` and rerunning `npm install` or `yarn install` _should_ do the trick

**Comment by larkintuckerllc** [comment]
BTW... I ended up resolving this by removing react-native Sentry and using expo-sentry instead.  Was a particular artifact of our funky build process.
