### ISSUE TITLE
undefined is not an object (evaluating '_expo Constants.default.manifest.releaseChannel

### ISSUE THREAD

**Issue by borgogelli** [expo/sentry-expo#64]
package.json:
```
    "expo": "^31.0.5",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz",
    "sentry-expo": "^1.13.0"
```
App.js:
```
Sentry.enableInExpoDevelopment = true;
Sentry.config('https://......@sentry.io/.....').install();
```

Error is:
```
...\index.js: 20:45
"undefined is not an object (evaluating '_expo Constants.default.manifest.releaseChannel')
```

**Comment by ty525** [comment]
I got the same error after upgrading sentry-expo to 1.13.0. The error disappeared after I locked sentry-expo version to 1.12.0.

**Comment by wardjk87** [comment]
I had same issue and had same package.json setup but with sentry-expo: ^1.10.0 and got the same error. I changed to 1.12.0 and that fixed it. Thanks @ty525.

**Comment by ty525** [comment]
I think the error was introduced by the commit https://github.com/expo/sentry-expo/commit/7f3f13b55cbcf21b066d82ff33c583591abce2c7

According to expo sdk documentation https://docs.expo.io/versions/v33.0.0/sdk/constants/ , `import Constants from 'expo-constants';` is available in sdk33, partially available to bare apps in sdk32. However, it's not available in sdk31 or lower.

**Comment by cruzach** [comment]
Yeah, it looks like `sentry-expo` v1.13 is assuming you have Expo SDK>=32 installed

**Comment by borgogelli** [comment]
Thank you @cruzach. Which version is still compatible with expo v31 ?
