### ISSUE TITLE
Postpublish hook, allow to target different Sentry projects per release channel

### ISSUE THREAD

**Issue by slorber** [expo/sentry-expo#67]
Hi,

I have a customer who prefers to have 2 distinct sentry projects for staging/production, instead of a single one with env=staging/production field.

Currently, the postpublish hook does not allow to upload the sourcemaps to a different Sentry project depending on the conf, I think that could be handy.

Note wanted to expose the usecase, more related to Sentry here, but I think this should rather be handled in a generic way for all hooks directly in expo system.

Related links:
- Canny: https://expo.canny.io/feature-requests/p/ability-to-run-postpublish-hook-only-on-some-release-channels
- Slack hook: https://github.com/expo/expo-postpublish-slack-notify/issues/4
- Sentry hook: https://github.com/expo/sentry-expo/issues/67

**Comment by cruzach** [comment]
Do you think it might be preferable to instead have two different releases of the same project, rather than two wholly separate projects? Correlating release channels with the release may be possible, but I'm not sure how widely applicable it is to maintain two separate sentry projects just for release and production channels

**Comment by slorber** [comment]
Hi,

This is my client requirement, they want to use 2 separate sentry projects for sandboxing. Also considering the Sentry UI, having staging events popping into a single Sentry project means we are more likely to see melted staging/production events. There are filters to only see production events but still. If you look at other SaaS (Intercom, Mixpanel, Stripes, Chargebee, Apple APNS, OneSignal...), they tend to offer api keys for production and test, and have 2 sandboxed environments. Sentry does not offer that, yet we want this behavior for Sentry (we already use sentry this way for the backend anyway).

What I'd like is something like this:

```
 "hooks": {
      "postPublish": [
        {
          "releaseChannel": "production-.*"
          "file": "expo-postpublish-slack-notify",
          "config": {
            "webhookUrl": "https://hooks.slack.com/services/x"
          }
        },
        {
          "releaseChannel": "staging-.*"
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "x",
            "project": "x-mobile-app",
            "authToken": "x"
          }
        },
        {
          "releaseChannel": "staging-.*"
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "x",
            "project": "x-mobile-app-staging",
            "authToken": "x-staging"
          }
        }
      ]
    }
  }
```

**Comment by cruzach** [comment]
you can now do this using [app config](https://docs.expo.io/workflow/configuration/?redirected#app-config) which will allow you to add logic into your app configuration

**Comment by slorber** [comment]
thanks, didn't know it was possible ;)

**Comment by CharlyPoppins** [comment]
@slorber what solution have you use ? **custom post publish hook** or **app config** ?

Can you provide a sample :) ?

**Comment by slorber** [comment]
I didn't do anything yet on this subject, but will likely do this using code in the config directly

**Comment by siarheipashkevich** [comment]
@slorber @CharlyPoppins did you find the solution?

**Comment by CharlyPoppins** [comment]
Nope... I manually change project name before publishing

**Comment by CharlyPoppins** [comment]
@siarheipashkevich as you took the subject out of oblivion I spent some time to figure out how to do the job.

According to sentry doc I use env variables : https://docs.expo.dev/guides/using-sentry/

So i remove the config from app.json
```
...
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps"
        }
      ]
    }
...
```

And define env variables SENTRY_ORG, SENTRY_PROJECT and SENTRY_AUTH_TOKEN in my CI.

**Comment by siarheipashkevich** [comment]
@CharlyPoppins I did the same. But if you remove hook then sourcemaps will not be uploaded to sentry.

**Comment by CharlyPoppins** [comment]
Yes, don't remove the hook, remove only the "config" part. (I edited the code)

**Comment by siarheipashkevich** [comment]
@CharlyPoppins yes, I did the same also )

In that case when I publish app then sourcemaps will be uploaded to sentry.
But...I don't want upload sourcemaps if I publish app to the special channel.

For example: `expo p --release-channel stage` in that case I not needed to upload sourcemaps to sentry.

**Comment by CharlyPoppins** [comment]
Try to allow env variables SENTRY_ORG, SENTRY_PROJECT and SENTRY_AUTH_TOKEN for your production environnement only.
I did not try it, but maybe Sentry hook will not be processus due to missing variables.
