### ISSUE TITLE
Unable to setup Sentry (undefined is not an object on first call)

### ISSUE THREAD

**Issue by Doychev** [expo/sentry-expo#69]
Hey all,

I am trying to setup sentry-expo and I'm following the simple steps in the [guide](https://docs.expo.io/versions/latest/guides/using-sentry/).

Here are my calls in App.js:
```
    Sentry.enableInExpoDevelopment = true;
    Sentry.config('XXX').install();
```

And here is what I get running it on Android device:

`TypeError: undefined is not an object (evaluating '_sentryExpo.default.enableInExpoDevelopment = true')`

Also, if I remove the enableInExpoDevelopment call, I get this:

`TypeError: undefined is not an object (evaluating '_sentryExpo.default.config')` (at least it's consistent)

Here's my package.json dependencies:

```
  "dependencies": {
    "awesome-phonenumber": "^2.15.0",
    "expo": "^34.0.1",
    "expo-analytics-amplitude": "~6.0.0",
    "expo-font": "^6.0.1",
    "expo-linear-gradient": "~6.0.0",
    "moment": "^2.24.0",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-easy-toast": "^1.2.0",
    "react-native-elements": "^1.1.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-popup-dialog": "^0.18.3",
    "react-native-swiper": "^1.5.14",
    "react-native-vector-icons": "^6.6.0",
    "react-native-version-check-expo": "^3.3.0",
    "react-native-web": "^0.11.4",
    "react-navigation": "^3.11.1",
    "sentry-expo": "^2.0.0"
  },
```

Let me know if I can provide further info.

**Comment by HazAT** [comment]
Hey, please see new usage in this PR
https://github.com/expo/sentry-expo/pull/58

**Comment by Doychev** [comment]
@HazAT thanks! For some reason, it's not noted in the latest Expo guides.

Here's the resolution for anyone else who might be in the same case:

```
import * as Sentry from 'sentry-expo';
...
Sentry.init({
  dsn: 'https://00d51de1c629418ab759202582b78a3c@sentry.io/1546052',
  enableInExpoDevelopment: true,
  debug: true
});
```

**Comment by HazAT** [comment]
Hmm, I wonder why
cc @cruzach

**Comment by cruzach** [comment]
The docs haven't been deployed yet, that's why.

I'll deploy them today! Sorry for the confusion @Doychev

**Comment by tzs007** [comment]
I use SDK38 but if I use with the new syntax, it's crashing on every start... If I use the old syntax, I got this error:

TypeError: undefined is not an object (evaluating '_sentryExpo.default.enableInExpoDevelopment = true')

What happend with expo after SDK35?
