### ISSUE TITLE
docs for 2.0 don't seem correct

### ISSUE THREAD

**Issue by chrisdrackett** [expo/sentry-expo#70]
from what I can tell (still trying to figure it out) 

```
import Sentry from 'sentry-expo';

// Remove this once Sentry is correctly setup.
Sentry.enableInExpoDevelopment = true;

Sentry.config('your Public DSN goes here').install();
```

needs to become:

```
import Sentry from 'sentry-expo'

Sentry.init({
  dsn: 'your Public DSN goes here',
})
```

I'm not sure what other changes are needed, still debugging!

**Comment by HazAT** [comment]
See https://github.com/expo/sentry-expo/issues/69#issuecomment-528024741

**Comment by cruzach** [comment]
Closing since docs have been deployed -> https://docs.expo.io/versions/latest/guides/using-sentry/#install-and-configure-sentry
