### ISSUE TITLE
Transpile for web

### ISSUE THREAD

**Issue by hanford** [expo/sentry-expo#77]
Thanks for this plugin!

Was wondering if we could add a transpiled version w/ ES5 support for the web

**Comment by wardjk87** [comment]
@hanford it is fairly easy to setup with@sentry/browser for web. I created separate web files that import from @sentry/browser instead. Importing expo-sentry breaks for web, so I separated my App.ts and App.web.ts files (where I initialize sentry) and error boundaries.

https://docs.sentry.io/platforms/javascript/

**Comment by georgiosd** [comment]
@wardjk87 just started with expo web and not sure how I'd go about that - could you give us a sample?

**Comment by wardjk87** [comment]
for example: home.screen.jsx (or could have one for ios/ android)

- import * as Sentry from 'sentry-expo';
-       Sentry.captureException(error);

example home.web.jsx
- import * as SentryWeb from '@sentry/browser'; [importing sentry-expo will break web]
-       SentryWeb.captureException(error);

**Comment by sandrina-p** [comment]
@wardjk87, your solution made me find an even better solution where we don't need to "duplicate" component files.

1. Create a folder `Sentry/` with two files inside: `Sentry.js` and a `Sentry.web.js`

```
/utils
    — Sentry/
       |— Sentry.js
       |— Sentry.web.js
```

2. Each file imports the respective Sentry package:

```js
// Sentry.js
import * as Sentry from 'sentry-expo'

export default Sentry
```


```js
// Sentry.web.js
import * as Sentry from '@sentry/browser'

export default Sentry
```

3. Finally, import  `Sentry` from the custom `Sentry/` folder without the file extension. Expo will be smart enough to handle the correct extension based on the Platform!

```js
import Sentry from '../utils/Sentry'

// ....

SentryWeb.init({ dsn: 'INSERT_DSN' });

Sentry.captureMessage('Cats sent from web or native.')

```

**Comment by zmays** [comment]
worked for me with:

```
import Sentry from '../utils/Sentry/Sentry'
```

**Comment by sandrina-p** [comment]
@zmays. I forgot to document the creation of `index.js`. After that `/utils/Sentry` is enough! (Original comment updated)

**Comment by cruzach** [comment]
Published a new major version of `sentry-expo` as `next` (3.0.0-rc1) which has support for Web (along with other things like better bare workflow support, and is all in Typescript) 🎉 

Definitely try it out, and open a new issue if you run into any problems with it so we can address them before publishing as `latest`. 

Instructions for setup **if you're using the bare workflow** can be found [here](https://github.com/expo/sentry-expo#bare-workflow-setup)

**Comment by chriskaya** [comment]
For anyone passing by:
I had the same issue trying to run an existing expo project on web:

```
Module parse failed: Unexpected token (26:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| class ExpoIntegration {
>   static id = 'ExpoIntegration';
|   name = ExpoIntegration.id;
```

I tried a few things including adding @babel/plugin-proposal-class-properties in babel.config.js, without results (and I discovered it's already included in babel-preset-expo).


### Solution:
Turns out that expo is setup so that babel is used only for packages that start with react-native-* by default. Any other package you need to add its name in app.json, like that:

```
{
  "expo": {
    "name": "acme",
    "version": "1.0.0",
    "slug": "acme",
    "platforms": [
      "ios",
      "android",
      "web"
    ],
    "web": {
      "build": {
        "babel": {
          "include": ["static-container", "sentry-expo"]
        }
      }
    }
  }
}
```

All credits to @EvanBacon here: https://github.com/expo/expo/issues/4751#issuecomment-506884410

**Comment by berkaygurbuz** [comment]
> 



> @wardjk87, your solution made me find an even better solution where we don't need to "duplicate" component files.
> 
> 1. Create a folder `Sentry/` with two 3 inside: `Sentry.js`, `Sentry.web.js` and `index.js`
> 
> ```
> /utils
>     — Sentry/
>        |— index.js
>        |— Sentry.js
>        |— Sentry.web.js
> ```
> 
> 1.1. Each file imports the respective Sentry package:
> 
> ```js
> // Sentry.js
> import * as Sentry from 'sentry-expo'
> 
> export default Sentry
> ```
> 
> ```js
> // Sentry.web.js
> import * as Sentry from '@sentry/browser'
> 
> export default Sentry
> ```
> 
> 1.2 The `index.js` works as a bridge to export `Sentry`.
> 
> ```js
> // index.js
> export { default } from './Sentry' // no extension!
> ```
> 
> 2. Finally, import  `Sentry` from the custom `Sentry/` folder without the file extension. Expo will be smart enough to handle the correct extension based on the Platform!
> 
> ```js
> import Sentry from '../utils/Sentry'
> 
> // ....
> 
> SentryWeb.init({ dsn: 'INSERT_DSN' });
> 
> Sentry.captureMessage('Cats sent from web or native.')
> ```

@sandrina-p  Your solution seems like great but it is not working for me. I still get same error so I have some questions.
1- In last step you import Sentry but use SentryWeb to init sentry? How can you do that? 
2- Where do you check platform is web or ios,android ?

**Comment by sandrina-p** [comment]
@berkaygurbuz By default, it seems like Expo knows the difference from native to the web automatically in the [app import](https://github.com/sandrina-p/papers-game/blob/41bb9308c064a1e6387296f4ec7a6ea13147c07d/App.js) I didn't do any condition.

**Comment by berkaygurbuz** [comment]
@sandrina-p Your repo is very helpful for finding my wrong. I was still using ```@sentry/react-native```. It is enough to use ```sentry-expo``` and ```@sentry/browser``` in our utils files.

**Comment by berkaygurbuz** [comment]
@sandrina-p when i send captureException or captureMessage it always warn but captureException log will show in sentry.io 

Warning as follows :
 ```
undefined is not an object (evaluating 'Sentry.captureException.apply')
at utils\Sentry.js:11:8 in captureException
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:294:29 in invoke
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:155:27 in invoke
at node_modules\regenerator-runtime\runtime.js:165:18 in PromiseImpl.resolve.then$argument_0
at node_modules\react-native\node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
at node_modules\react-native\node_modules\promise\setimmediate\core.js:123:24 in setImmediate$argument_0
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:123:14 in _callTimer
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:177:14 in _callImmediatesPass
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:437:30 in callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:388:6 in __callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:132:6 in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:365:10 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:131:4 in flushedQueue
```

**Comment by sandrina-p** [comment]
@berkaygurbuz weird... I didn't notice if that happened to me or not. I'm sorry but I don't have the bandwidth to help you debug that now. If you find the solution, please share it with us :)

**Comment by berkaygurbuz** [comment]
@sandrina-p I think we have to use ```Sentry.Native.CaptureMessage```.

 **In documentation of sentry-expo,** 
> Unless enableInExpoDevelopment: true is set, all your dev/local errors will be ignored and only app releases will report errors to Sentry. You can call methods like Sentry.Native.captureException(new Error('Oops!')) but these methods will be no-op.

So it means we have to use Sentry.Native.*

I solve as follows : 
```
import * as Sentry from 'sentry-expo';

export default {
    init: Sentry.init,
    captureMessage: Sentry.Native.captureMessage,
    captureException(...args) {
        if (__DEV__) {
            console.log('‼️ S.Exp', ...args);
        }
        Sentry.Native.captureException(...args);
    },
};
```
