### ISSUE TITLE
New API for Sentry.setUserContext and Sentry.setExtraContext

### ISSUE THREAD

**Issue by ppetrick** [expo/sentry-expo#78]
I've been upgrading Expo from 32 to 35 (painful). I see that the Expo docs have changed for initializing Sentry. I've changed those. Now I'm getting errors when calling Sentry.setUserContext and Sentry.setExtraContext. Have those APIs changed too? If so, is there documentation somewhere?

Tried this and got an error:
```          
Sentry.configureScope(scope => {
  scope.setUser({
    userID: user.uid,
  });
});
```

results in: `undefined is not an object (evaluating '_sentryExpo.default.configureScope')`

Running v.2.0

**Comment by markholland** [comment]
Are you doing `import * as Sentry from sentry-expo`?

I still had the old import of `import Sentry from sentry-expo`

**Comment by ppetrick** [comment]
That was it. Changed it elsewhere but missed it there. Thanks @markholland
