### ISSUE TITLE
Expose Raven client instance for integrations with other packages/services

### ISSUE THREAD

**Issue by jhalborg** [expo/sentry-expo#8]
Hey all, 

Creating a feature request to expose the Raven client through the SDK somehow, as it seems to be required for a lot of integrations to other services, i.e. LogRocket and/or the raven-for-redux NPM package. I also created a forum post for discussion, not sure where this belongs to be honest. 

https://forums.expo.io/t/sentry-logrocket-setup/1554

Any ideas/input is welcome :-)

**Comment by brentvatne** [comment]
hiya! this seems reasonable, I will investigate

**Comment by brentvatne** [comment]
you can call `Sentry.setDataCallback` and it will work as expected in sentry-expo@1.6.0, but logrocket doesn't support react-native yet :)

**Comment by jhalborg** [comment]
Darn it - thanks for checking it out :-) We'll just have to wait. 

How about the raven-for-redux package that also needs the Raven client, how would I go about using that? https://github.com/captbaritone/raven-for-redux

**Comment by brentvatne** [comment]
same as you would with react-native-sentry, that repo is probably a better place to ask. or you can experiment and try to figure it out :)
