### ISSUE TITLE
Expo 35: undefined is not an object(evaluating '_sentryExpo.default.config')

### ISSUE THREAD

**Issue by hemantasapkota** [expo/sentry-expo#80]
I'm getting this error after upgrading to Expo 35.  

sentry-expo version is  **2.0.1**.

<img width="512" alt="Screen Shot 2019-10-01 at 9 30 37 am" src="https://user-images.githubusercontent.com/896157/65961325-ab810780-e499-11e9-890d-f099dad7c578.png">

**Comment by cruzach** [comment]
There were breaking changes to how `sentry-expo` is to be configured, you can see the new example [here](https://docs.expo.io/versions/latest/guides/using-sentry/#install-and-configure-sentry).

**Comment by hemantasapkota** [comment]
Great, thanks!. Resolved by switching to the new way configuring Sentry.

Old way:
```
Sentry.config(
    'DSN URL'
).install();
```

New way:
```
Sentry.init({
    dsn: 'DSN URL'
});
```
