### ISSUE TITLE
Integrate with native sentry code

### ISSUE THREAD

**Issue by SimenB** [expo/sentry-expo#87]
I was under the impression we would get native crash reports by using this, but it seems that's not true.

Currently, the warning from sentry is silenced per https://github.com/expo/sentry-expo/blob/c608249c8bddac3bab58339120f15027d93f4ad4/index.js#L158-L159, but native is not actually turned off by passing `{enableNative: false}`.

That means that calling `Sentry.nativeCrash()` (to test reports) fails with `TypeError: null is not an object (evaluating 'RNSentry.crash')`. Is it possible to get native crash reports without ejecting from Expo? If not, [the guide](https://docs.expo.io/versions/latest/guides/using-sentry/) and the readme in this repo should really be updated with this info. And calling out Sentry support in Expo as "first class" is a bit of an exaggeration... If it _is_ possible I'd be eternally grateful if you could tell me how and I'll happily send a PR adding that to the docs! 😀

**Comment by cruzach** [comment]
Unfortunately, it's not planned for the managed workflow at the moment. We give the reasons [here in the docs](https://docs.expo.io/versions/latest/guides/errors/#what-about-native-errors)

**Comment by SimenB** [comment]
Wow, dunno how I missed that 😬 Sorry! Also sorry about the slow response, I completely missed the notification about this issue.

This makes me very sad though, as we currently have a user that has a native crash, either when calling `ImagePicker.launchCameraAsync` or `ImageManipulator.manipulateAsync`. The only reason we know this is because she contacted customer support. I'm also unable to reproduce her issue on the same device, but I was hoping to be able to use the error to understand what was going on. Probably a bug on our side, but it would be nice to give Expo a nice bug report as well, as I don't think anything we do via the JS APIs should cause a native crash, no?

Any hope of you reconsidering this stance for a future version of expo?

**Comment by SimenB** [comment]
When it comes to the linked workaround doc about Fabric - googling it doesn't inspire much confidence that will work 😛 

![image](https://user-images.githubusercontent.com/1404810/68882296-31d26f80-070f-11ea-8c6d-2d3a99aa56f0.png)

It says to migrate to firebase, but afaik Expo has no plans to work with it, right? Seeing as https://www.npmjs.com/package/expo-firebase-crashlytics is deprecated, linking to https://gist.github.com/brentvatne/9038b16b4f42a21cea40ad5c35fdb74c

**Comment by cruzach** [comment]
> I don't think anything we do via the JS APIs should cause a native crash, no?

It's tough to crash the native code just by writing JS, but it's possible. Is it possible your crash is similar to [this one](https://github.com/expo/expo/issues/6135)?

> Any hope of you reconsidering this stance for a future version of expo?

In the future, it's possible. But that most likely won't be coming soon, so if you need native crash logs or any kind of fine tuned control over your native code, it's best to use the bare workflow

**Comment by SimenB** [comment]
I'd guess it's related to https://github.com/expo/expo/issues/2925, but since I've never been able to reproduce it (and we have zero stack traces, ref this issue), I don't really know... The issue you linked is for iOS, so at least that one shouldn't be the culprit in our case

**Comment by awinograd** [comment]
👍 for being able to get native crash reports. Even if it's related to expo / rn code that we don't have control over in the managed workflow we'd get two benefits:

1. Notifications when our users experience native crashes. As of now, we're not getting anything at all for native crashes
2. Debug information to both (a) code a workaround until the native issue is fixed (b) add helpful context to any issues we file

**Comment by wodin** [comment]
After poking around a bit I get the impression that Firebase Crashlytics might work for this for standalone apps. It looks like it's already included:

https://github.com/expo/expo/blob/199ffb41abe30e1869a2b43ffff492399cac7c02/android/versioned-abis/expoview-abi36_0_0/build.gradle#L95-L97

So if I understand correctly you should be able to do the necessary setup in the Firebase console, get a `google-services.json` file (or `GoogleService-Info.plist` for iOS) and point to it in `app.json`. Unfortunately I don't have time to test this at the moment.

If you want to cause a crash to test this then the following should do the trick:

Use a string where a number is expected in a style:
```
<View style={{padding: "64px"}}>...</View>
```

Or manually corrupt a bundle used for OTA updates:
```
$ expo export --public-url https://example.com/blah/
$ rsync -avxz --progress --delete --stats dist/ example.com:/blah/
$ rm -r dist
$ expo ba --public-url https://example.com/blah/android-index.json
$ expo export --public-url https://example.com/blah/
[Manually truncate dist/bundles/android-*.js] 
$ rsync -avxz --progress --delete --stats dist/ example.com:/blah/
[Install APK, wait for it to download the bad bundle and restart it.]
```

@cruzach should Crashlytics work or am I missing something?

**Comment by cruzach** [comment]
crashlytics works for Android, just not for iOS 😕

**Comment by wodin** [comment]
Sorry, I should have been more specific. Is Firebase Crashlytics expected to work (at least on standalone Android apps)? I see the docs you pointed at mention Fabric.

**Comment by cruzach** [comment]
For firebase crashlytics you'd need to use the bare workflow

**Comment by cruzach** [comment]
To integrate `sentry-expo` with native code, you'll need to use the bare workflow. We don't plan on adding Sentry native support to the managed workflow right now, so I'm going to close this issue.

However, in regards to the bare workflow, we've just published a new major version of `sentry-expo` as `next` (3.0.0-rc1) which has better bare workflow support (along with other things like Web support, and is all in Typescript) 🎉 

Definitely try it out, and open a new issue if you run into any problems with it so we can address them before publishing as `latest`. 

Instructions for setup **if you're using the bare workflow** can be found [here](https://github.com/expo/sentry-expo#bare-workflow-setup)

**Comment by janbiasi** [comment]
@cruzach small question related to your *"... right now."* statement; Is it planned to add Sentry native support for crash reports anytime in the future or is it just not on the near-future roadmap? 😸

**Comment by cruzach** [comment]
We don’t plan on adding Sentry native support in the managed workflow (native code isn’t under your control in the managed workflow so I’m not sure what good native crash reports would do you?)

**Comment by janbiasi** [comment]
@cruzach you're right, should have thought once more about the sentence I wrote 😆
