### ISSUE TITLE
Associating git commits to release.

### ISSUE THREAD

**Issue by alialaa** [expo/sentry-expo#88]
Hello, I am publishing my app on CI and since expo is responsible for creating a unique release id, I can't find a way to associate certain git commits to the latest release. I need to call:

`sentry-cli releases set-commits --auto $version`

My problem is I don't know the version since it's generated by expo. Is there any way I can get the revisionID that expo generates and use it on CI not in the actual app?

**Comment by bradbumbalough** [comment]
I solved this by adding my own postPublish script based on upload-sourcemaps.js. Would it be acceptable submit a PR which would add the process to this file and toggle it via the config? 

Something like this...

```js
if (config.setCommits) {
  let commitsResult = await spawnAsync(
    sentryCliBinaryPath,
    ['releases', 'set-commits', '--auto', version],
    {
      env: childProcessEnv,
    }
  );

  output = commitsResult.stdout.toString();
  log(output);
}
```

and invoked in app.json...

```json
{
"hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "setCommits": true
           }
        }
    ]
}
```

**Comment by alialaa** [comment]
I did it the same way as well, here is mine if anybody is interested. It has some stuff specific to my case (release channel names for example) but it could be useful:
app.json:
```javascript
"hooks": {
     "postPublish": [
        {
            "file": "sentry-expo/upload-sourcemaps",
                "config": {}
        },
        {
              "file": "./hooks/set-commits"
         }
       ]
 }
```
hooks/set-commits.js
```javascript
/* eslint-disable */
const spawnAsync = require("@expo/spawn-async");

const getEnv = releaseChannel => {
    if (releaseChannel === undefined) return "development";
    if (releaseChannel.indexOf("prod") !== -1) return "production";
    if (releaseChannel.indexOf("staging") !== -1) return "staging";
    return "staging";
};

module.exports = async ({ iosManifest, log }) => {
    // if (getEnv(iosManifest.releaseChannel) !== "production") return;
    try {
        let setCommits = await spawnAsync("npx", [
            "sentry-cli",
            "releases",
            "set-commits",
            "--auto",
            iosManifest.revisionId
        ]);
        log(setCommits.stdout.toString());

        let deploys = await spawnAsync("npx", [
            "sentry-cli",
            "releases",
            "deploys",
            iosManifest.revisionId,
            "new",
            "-e",
            getEnv(iosManifest.releaseChannel)
        ]);
        log(deploys.stdout.toString());
    } catch (error) {
        log(error);
    }
};
```
```

**Comment by cruzach** [comment]
I'm guessing you are also changing how the release is set when running `Sentry.init`?
Otherwise, issues or events will still be classified as under the [`revisionId`](https://github.com/expo/sentry-expo/blob/master/index.js#L147)

**Comment by cruzach** [comment]
@bradbumbalough that seems like a good idea to me! Request a review from me once you open the PR

**Comment by okeybond** [comment]
Sorry to disturb, any update on this, please?

**Comment by pybuche** [comment]
Same question ! Very interested in being able to have commits set on the release !

**Comment by bradbumbalough** [comment]
@cruzach I finally got around to opening a PR for this. Based on @alialaa's shared code I also included the ability to set deploys.

**Comment by pybuche** [comment]
Hope this gets merged, thanks for the PR 💪
