### ISSUE TITLE
Sentry Logger [Error]: Error while sending event: TypeError: Network request failed

### ISSUE THREAD

**Issue by WillzMu** [expo/sentry-expo#94]
I am using sentry-expo version 2.0.0 and I get this red screen error when I try to turn off my internet connection of the app in development. I use the following methods from Sentry: `configureScope`, `setExtra`, `setTags`, `captureException`.

![image](https://user-images.githubusercontent.com/16624002/70604096-a6aaa380-1c00-11ea-976a-1cde0ef48676.png)

**Comment by cruzach** [comment]
You should check if the device has a network connection (see [this Expo module](https://docs.expo.io/versions/latest/sdk/network/)), and if it doesn't then queue messages to send to Sentry once it does have a connection

**Comment by WillzMu** [comment]
thanks for the info. I will do that

**Comment by Infinitism** [comment]
Could we get an example of what you mean by "queue" error when network is back online?

**Comment by Infinitism** [comment]
@WillzMu : Could you share any code samples on how you solved this?

@others
Could we get an example of what you mean by "queue" error when network is back online? Like what's the best practice on this?

**Comment by WillzMu** [comment]
sorry @Infinitism . I dont have a code sample using Sentry at the moment. If I come across this issue again, I can re-open the issue

**Comment by Infinitism** [comment]
@WillzMu That'd be great! It feels like a blocker for us to have an app crash because of Sentry due to poor network.

**Comment by ivangafa** [comment]
How can I queue Sentry messages when my device has no connection?

**Comment by cokealmonacid** [comment]
Any solution on this, my device has connection
