### ISSUE TITLE
Missing documentation for "debug"

### ISSUE THREAD

**Issue by AdamGerthel** [expo/sentry-expo#97]
[The Expo page for Sentry](https://docs.expo.io/versions/latest/guides/using-sentry/) states that the configuration object should set `debug` to true, like this:

```
Sentry.init({
  dsn: 'YOUR DSN HERE',
  enableInExpoDevelopment: true,
  debug: true
});
```

But there is no mention as to what `debug: true` actually does. I assumed it was something that you'd enable in development but not in production, but it seems as if uncaught errors are not sent to Sentry unless it's set to `true`. 

Could we perhaps have a little bit more documentation regarding this config value? It doesn't seem to be a requirement of [sentry-react-native](https://github.com/getsentry/sentry-react-native).

**Comment by cruzach** [comment]
https://docs.sentry.io/error-reporting/configuration/?platform=javascript#debug

If you'd like to submit a PR to the docs, that would be greatly appreciated! Right now, the documentation is pretty expo-specific and we're relying on devs going to the Sentry docs as well, but I see how that could be a pain

**Comment by AdamGerthel** [comment]
@cruzach Thanks for the clarification regarding the debug option. I don't think that there's a problem for anyone to read the Sentry documentation (I'm not sure why I couldn't find that option there myself..). The problem is probably the opposite: It's better that you simply describe any difference between the Expo-module and the "original" module, and then link to that module's documentation for the specific version.
