### ISSUE TITLE
Sentry expo uses user oriented auth token instead of organisation oriented auth token and secret

### ISSUE THREAD

**Issue by itsgauravjain22** [expo/sentry-expo#99]
Sentry expo should use organization based auth token instead of user-based auth tokens.

**Comment by cruzach** [comment]
Hi! Could you explain a little more behind what you'd like added and why? References to sentry's documentation are also helpful. Basically anything that makes incorporating this easier for anyone looking at this issue

**Comment by eridr** [comment]
I concur even tough it might be harmless in this instance it feels bad to have authToken exposed in the app.json

**Comment by cruzach** [comment]
Without more info on this, there's nothing to be done so I'm closing this for now. If you can provide more specifics I'm happy to investigate

@eridr not sure why it feels bad to have authToken in app.json, but if you'd prefer you can always use `SENTRY_AUTH_TOKEN` env variable instead- [docs](https://docs.expo.io/guides/using-sentry/)
